import { FormEvent, useCallback, useEffect, useState } from 'react';
import { billingService } from '../services/billingService';
import { workOrdersService } from '../services/workOrdersService';

type Mode = 'invoices' | 'collections';
type Action = { kind: 'draft' | 'view' | 'payment' | 'cancel' | 'reverse'; row: any } | null;
type DraftLine = { work_order_id?: string | null; description: string; quantity: number; unit_price: number; discount: number; tax_rate: number };

function money(value: unknown) { return `${Number(value ?? 0).toLocaleString('es-ES', { minimumFractionDigits: 2, maximumFractionDigits: 2 })} €`; }
function date(value?: string | null) { return value ? new Date(value).toLocaleDateString('es-ES') : '-'; }
function errorText(error: unknown) { return error instanceof Error ? error.message : 'No se ha podido completar la operación.'; }
function lineFrom(row: any, tax = 21): DraftLine { return { work_order_id: row.work_order_id ?? null, description: row.description ?? '', quantity: Number(row.quantity ?? 1), unit_price: Number(row.unit_price ?? 0), discount: Number(row.discount ?? 0), tax_rate: Number(row.tax_rate ?? tax) }; }
async function loadDraft(invoiceId: string) {
  const invoice = await billingService.invoice(invoiceId);
  const workOrderId = invoice.invoice_work_orders?.find((line: any) => line.work_order_id)?.work_order_id;
  if (!workOrderId) return invoice;
  try { return { ...invoice, context: await workOrdersService.getWorkOrderFullDetail(workOrderId) }; }
  catch (error: any) { console.error('DMP invoice draft context failed', { code: error?.code, message: error?.message, details: error?.details, hint: error?.hint, operation: 'Cargar contexto de borrador', resource: workOrderId }); return invoice; }
}

export function BillingModule({ mode }: { mode: Mode }) {
  const [invoices, setInvoices] = useState<any[]>([]); const [invoiceable, setInvoiceable] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [available, setAvailable] = useState<boolean | null>(null); const [error, setError] = useState(''); const [action, setAction] = useState<Action>(null);
  const reload = useCallback(async () => { setLoading(true); setError(''); try { const nextAvailable = await billingService.isAvailable(); setAvailable(nextAvailable); if (!nextAvailable) { setInvoices([]); setInvoiceable([]); return; } const [nextInvoices, nextInvoiceable] = await Promise.all([billingService.invoices(), billingService.invoiceableWorkOrders()]); setInvoices(nextInvoices); setInvoiceable(nextInvoiceable); } catch (err) { setError(errorText(err)); } finally { setLoading(false); } }, []);
  useEffect(() => { reload(); }, [reload]);
  const prepare = async (work: any) => { setError(''); try { const id = await billingService.prepareInvoice(work.id, { tax_rate: 21 }); setAction({ kind: 'draft', row: await loadDraft(id) }); } catch (err) { setError(errorText(err)); } };
  const visible = mode === 'collections' ? invoices.filter((row) => !['borrador', 'cancelada'].includes(row.status) && Number(row.paid_amount) < Number(row.total_amount)) : invoices.filter((row) => row.status !== 'borrador');
  const drafts = invoices.filter((row) => row.status === 'borrador'); const issued = invoices.filter((row) => row.status !== 'borrador' && row.status !== 'cancelada').reduce((sum, row) => sum + Number(row.total_amount ?? 0), 0); const collected = invoices.filter((row) => row.status !== 'borrador' && row.status !== 'cancelada').reduce((sum, row) => sum + Number(row.paid_amount ?? 0), 0);
  if (available === false) return <section className="page billing-page"><div className="page-head"><div><p className="eyebrow">Oficina</p><h2>{mode === 'invoices' ? 'Facturación' : 'Cobros'}</h2></div><button onClick={reload} disabled={loading}>Actualizar</button></div><div className="card"><h3>Facturación pendiente de activación</h3><p className="large-note">Este módulo estará disponible cuando se active el backend de facturación y validación de oficina.</p></div></section>;
  return <section className="page billing-page"><div className="page-head"><div><p className="eyebrow">Oficina</p><h2>{mode === 'invoices' ? 'Facturación' : 'Cobros'}</h2><p>{mode === 'invoices' ? 'Preparación, revisión y emisión trazable desde partes validados.' : 'Registro y conciliación de cobros de cliente.'}</p></div><button onClick={reload} disabled={loading}>Actualizar</button></div><div className="stats-grid"><div className="metric info"><span>Emitido con IVA</span><strong>{money(issued)}</strong></div><div className="metric ok"><span>Cobrado</span><strong>{money(collected)}</strong></div><div className="metric warn"><span>Pendiente</span><strong>{money(issued - collected)}</strong></div><div className="metric commercial"><span>Preparables</span><strong>{invoiceable.length}</strong></div></div>{error && <p className="form-error">{error}</p>}{loading && <p className="large-note">Cargando información económica…</p>}
    {mode === 'invoices' && <><section className="card"><h3>Partes preparados para facturar</h3><div className="compact-list">{invoiceable.map((work) => <article key={work.id}><div><strong>{work.code} · {work.title}</strong><p>{work.clients?.legal_name ?? 'Cliente'} · Venta registrada {money(work.sale_amount)}{Number(work.sale_amount) === 0 && Number(work.estimated_sale_amount) > 0 ? ` · Referencia estimada ${money(work.estimated_sale_amount)}` : ''}</p></div><button className="primary" onClick={() => prepare(work)}>Preparar factura</button></article>)}</div>{!invoiceable.length && !loading && <p className="large-note">No hay partes validados pendientes de preparar.</p>}</section>{drafts.length > 0 && <section className="card"><h3>Borradores editables</h3><div className="compact-list">{drafts.map((invoice) => <article key={invoice.id}><div><strong>Borrador · {invoice.clients?.legal_name ?? '-'}</strong><p>Base {money(invoice.subtotal)} · Total {money(invoice.total_amount)} · Actualizado {date(invoice.updated_at)}</p></div><button className="primary" onClick={async () => { try { setAction({ kind: 'draft', row: await loadDraft(invoice.id) }); } catch (err) { setError(errorText(err)); } }}>Abrir borrador</button></article>)}</div></section>}</>}
    <section className="card"><h3>{mode === 'invoices' ? 'Facturas emitidas' : 'Facturas pendientes de cobro'}</h3><div className="table-card"><table><thead><tr><th>Factura</th><th>Cliente</th><th>Emisión</th><th>Vencimiento</th><th>Estado</th><th>Total</th><th>Cobrado</th><th>Saldo</th><th></th></tr></thead><tbody>{visible.map((invoice) => <tr key={invoice.id}><td>{invoice.code}</td><td>{invoice.clients?.legal_name ?? '-'}</td><td>{date(invoice.issue_date)}</td><td>{date(invoice.due_date)}</td><td>{invoice.status.replaceAll('_', ' ')}</td><td>{money(invoice.total_amount)}</td><td>{money(invoice.paid_amount)}</td><td>{money(Number(invoice.total_amount) - Number(invoice.paid_amount))}</td><td><div className="row-actions"><button onClick={async () => { try { setAction({ kind: 'view', row: await billingService.invoice(invoice.id) }); } catch (err) { setError(errorText(err)); } }}>Ver</button>{invoice.status !== 'cancelada' && Number(invoice.paid_amount) < Number(invoice.total_amount) && <button className="primary" onClick={() => setAction({ kind: 'payment', row: invoice })}>Registrar cobro</button>}{mode === 'invoices' && invoice.status !== 'cancelada' && <button className="danger" onClick={() => setAction({ kind: 'cancel', row: invoice })}>Cancelar factura</button>}</div></td></tr>)}</tbody></table></div>{!visible.length && !loading && <p className="large-note">Sin registros.</p>}</section>
    {invoices.some((invoice) => (invoice.invoice_payments ?? []).length) && <section className="card"><h3>Movimientos de cobro</h3><div className="compact-list">{invoices.flatMap((invoice) => (invoice.invoice_payments ?? []).map((payment: any) => ({ invoice, payment }))).map(({ invoice, payment }) => <article key={payment.id}><div><strong>{invoice.code} · {money(payment.amount)}</strong><p>{date(payment.paid_at)} · {payment.method} · {payment.reference ?? 'Sin referencia'}{payment.reversed_at ? ' · ANULADO' : ''}</p></div>{!payment.reversed_at && <button className="danger" onClick={() => setAction({ kind: 'reverse', row: payment })}>Anular cobro</button>}</article>)}</div></section>}
    {action?.kind === 'draft' && <InvoiceDraftModal invoice={action.row} onClose={() => setAction(null)} onSaved={() => { setAction(null); reload(); }} />}{action?.kind === 'view' && <InvoiceView invoice={action.row} onClose={() => setAction(null)} />}{action?.kind === 'payment' && <PaymentModal invoice={action.row} onClose={() => setAction(null)} onSaved={() => { setAction(null); reload(); }} />}{(action?.kind === 'cancel' || action?.kind === 'reverse') && <ReasonModal title={action.kind === 'cancel' ? 'Cancelar factura' : 'Anular cobro'} onClose={() => setAction(null)} onConfirm={async (reason) => { if (action.kind === 'cancel') await billingService.cancelInvoice(action.row.id, reason); else await billingService.reversePayment(action.row.id, reason); setAction(null); reload(); }} />}</section>;
}

function InvoiceDraftModal({ invoice, onClose, onSaved }: { invoice: any; onClose: () => void; onSaved: () => void }) {
  const [tax, setTax] = useState(String(invoice.tax_rate ?? 21)); const [due, setDue] = useState(invoice.due_date ?? ''); const [notes, setNotes] = useState(invoice.notes ?? ''); const [lines, setLines] = useState<DraftLine[]>((invoice.invoice_work_orders ?? []).map((line: any) => lineFrom(line, invoice.tax_rate))); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const setLine = (index: number, key: keyof DraftLine, value: string) => setLines((current) => current.map((line, position) => position === index ? { ...line, [key]: key === 'description' ? value : Number(value) } : line));
  const save = async (issue: boolean) => { setSaving(true); setError(''); try { await billingService.updateDraft(invoice.id, { lines, tax_rate: Number(tax), due_date: due, notes }); if (issue) { if (!window.confirm('La factura se emitirá y dejará de ser editable. ¿Continuar?')) { setSaving(false); return; } await billingService.issueInvoice(invoice.id); } onSaved(); } catch (err) { setError(errorText(err)); } finally { setSaving(false); } };
  const subtotal = lines.reduce((sum, line) => sum + line.quantity * line.unit_price * (1 - line.discount / 100), 0); const taxTotal = lines.reduce((sum, line) => sum + line.quantity * line.unit_price * (1 - line.discount / 100) * line.tax_rate / 100, 0);
  return <div className="mini-modal invoice-draft-modal" role="dialog" aria-modal="true"><div className="card"><h3>Preparar factura · {invoice.clients?.legal_name ?? '-'}</h3><InvoiceContext context={invoice.context} warning={invoice.notes?.includes('ADVERTENCIA') ? invoice.notes : undefined} /><p className="large-note">Borrador editable. Parte asociado: {(lines.find((line) => line.work_order_id)?.description ?? 'Conceptos manuales')}</p><div className="form-grid"><label>IVA por defecto<input type="number" min="0" step="0.01" value={tax} onChange={(event) => setTax(event.target.value)} /></label><label>Vencimiento<input type="date" value={due} onChange={(event) => setDue(event.target.value)} /></label></div><label>Notas<textarea value={notes} onChange={(event) => setNotes(event.target.value)} /></label><div className="compact-list">{lines.map((line, index) => <article key={`${index}-${line.work_order_id ?? 'manual'}`}><label>Descripción<textarea value={line.description} onChange={(event) => setLine(index, 'description', event.target.value)} /></label><div className="form-grid"><label>Cantidad<input type="number" min="0" step="0.001" value={line.quantity} onChange={(event) => setLine(index, 'quantity', event.target.value)} /></label><label>Precio unitario<input type="number" min="0" step="0.01" value={line.unit_price} onChange={(event) => setLine(index, 'unit_price', event.target.value)} /></label><label>Descuento %<input type="number" min="0" max="100" step="0.01" value={line.discount} onChange={(event) => setLine(index, 'discount', event.target.value)} /></label><label>IVA %<input type="number" min="0" step="0.01" value={line.tax_rate} onChange={(event) => setLine(index, 'tax_rate', event.target.value)} /></label></div><p>Base: {money(line.quantity * line.unit_price * (1 - line.discount / 100))} · IVA: {money(line.quantity * line.unit_price * (1 - line.discount / 100) * line.tax_rate / 100)} · Total: {money(line.quantity * line.unit_price * (1 - line.discount / 100) * (1 + line.tax_rate / 100))}</p><button type="button" className="danger" onClick={() => setLines((current) => current.filter((_, position) => position !== index))}>Eliminar línea</button></article>)}</div><button type="button" onClick={() => setLines((current) => [...current, { description: '', quantity: 1, unit_price: 0, discount: 0, tax_rate: Number(tax) }])}>Añadir línea</button><section className="invoice-totals"><strong>Base imponible: {money(subtotal)}</strong><strong>IVA: {money(taxTotal)}</strong><strong>Total: {money(subtotal + taxTotal)}</strong></section>{error && <p className="form-error">{error}</p>}<div className="modal-footer"><button type="button" onClick={onClose} disabled={saving}>Cancelar</button><button type="button" onClick={() => save(false)} disabled={saving}>Guardar borrador</button><button type="button" className="primary" onClick={() => save(true)} disabled={saving}>Emitir factura</button></div></div></div>;
}

function personName(profile: any) { return [profile?.first_name, profile?.last_name].filter(Boolean).join(' ') || 'Trabajador no informado'; }
function InvoiceContext({ context, warning }: { context?: any; warning?: string }) {
  if (!context) return <p className="state-warning">No se ha podido cargar el contexto completo del parte. Puedes revisar las líneas y reintentar la carga.</p>;
  const client = context.client ?? context.clients; const site = context.site ?? context.sites; const work = context.work_order ?? context; const timeEntries = context.time_entries ?? []; const technicians = (context.assignments ?? []).map((item: any) => { const minutes = timeEntries.filter((time: any) => time.profile_id === item.technician_id).reduce((sum: number, time: any) => sum + Number(time.duration_minutes ?? 0), 0); return `${personName(item.profiles)}${item.role ? ` · ${item.role}` : ''}${minutes ? ` · ${(minutes / 60).toFixed(2)} h` : ''}`; }).filter(Boolean); const times = timeEntries.reduce((sum: number, item: any) => sum + Number(item.duration_minutes ?? 0), 0);
  return <div className="invoice-context-grid"><section><h4>DATOS DE FACTURACIÓN</h4><p><strong>{client?.legal_name ?? '-'}</strong>{client?.trade_name ? ` · ${client.trade_name}` : ''}</p><p>Código: {client?.code ?? '-'} · CIF/NIF: {client?.tax_id ?? '-'}</p><p>{[client?.address, client?.postal_code, client?.city, client?.province, client?.country].filter(Boolean).join(', ') || 'Sin dirección fiscal informada'}</p><p>Email: {client?.email ?? '-'} · Teléfono: {client?.phone ?? '-'}</p></section><section><h4>CENTRO DEL TRABAJO</h4><p><strong>{site?.name ?? '-'}</strong> · Código: {site?.code ?? '-'}</p><p>{[site?.address, site?.postal_code, site?.city, site?.province, site?.country].filter(Boolean).join(', ') || 'Sin dirección de centro informada'}</p></section><section><h4>PARTE</h4><p><strong>{work.code ?? '-'}</strong> · {work.title ?? '-'}</p><p>Tipo: {work.type ?? '-'} · Estado: {work.status ?? '-'}</p><p>Apertura: {date(work.created_at)} · Finalización: {date(work.finished_at)}</p><p>{work.description ?? 'Sin descripción'}{work.diagnosis ? ` · Diagnóstico: ${work.diagnosis}` : ''}</p><p>{work.work_performed ?? work.result ?? work.observations ?? 'Sin observaciones técnicas adicionales'}</p><p>Presupuesto: {work.quotes?.code ?? work.quote_id ?? 'Sin presupuesto'} · Equipo: {work.primary_equipment?.code ?? work.main_equipment_id ?? 'Sin equipo'}</p><p>Origen: {work.origin ?? work.cases?.code ?? 'No informado'}</p></section><section><h4>TÉCNICOS</h4><p>{technicians.length ? technicians.join(' · ') : 'No hay técnicos asociados'}</p><p>Tiempo registrado: {times ? `${(times / 60).toFixed(2)} h` : 'Sin tiempo registrado'}</p></section>{warning && <p className="state-warning"><strong>Revisión necesaria:</strong> {warning}</p>}</div>;
}

function InvoiceView({ invoice, onClose }: { invoice: any; onClose: () => void }) { return <div className="mini-modal" role="dialog" aria-modal="true"><div className="card"><h3>Factura {invoice.code ?? 'Borrador'}</h3><p>Cliente: {invoice.clients?.legal_name ?? '-'} · Estado: {invoice.status}</p><div className="compact-list">{(invoice.invoice_work_orders ?? []).map((line: any) => <article key={line.id}><strong>{line.description}</strong><p>{line.quantity} × {money(line.unit_price)} · Base {money(line.subtotal)} · IVA {money(line.tax_amount)} · Total {money(line.total_amount)}</p></article>)}</div><p>Base imponible: {money(invoice.subtotal)} · IVA: {money(invoice.tax_amount)} · Total: {money(invoice.total_amount)}</p><p>Emisión: {date(invoice.issue_date)} · Vencimiento: {date(invoice.due_date)}</p><p>{invoice.notes ?? 'Sin notas'}</p><div className="modal-footer"><button type="button" onClick={onClose}>Cerrar</button></div></div></div>; }

function PaymentModal({ invoice, onClose, onSaved }: { invoice: any; onClose: () => void; onSaved: () => void }) { const balance = Math.max(Number(invoice.total_amount) - Number(invoice.paid_amount), 0); const [amount, setAmount] = useState(String(balance)); const [paidAt, setPaidAt] = useState(new Date().toISOString().slice(0, 10)); const [method, setMethod] = useState('transferencia'); const [reference, setReference] = useState(''); const [notes, setNotes] = useState(''); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const submit = async (event: FormEvent) => { event.preventDefault(); if (Number(amount) <= 0 || Number(amount) > balance) { setError('El importe debe ser positivo y no superar el saldo.'); return; } setSaving(true); setError(''); try { await billingService.recordPayment(invoice.id, { amount: Number(amount), paid_at: paidAt, method, reference, notes }); onSaved(); } catch (err) { setError(errorText(err)); } finally { setSaving(false); } }; return <div className="mini-modal" role="dialog" aria-modal="true"><form onSubmit={submit}><h3>Registrar cobro · {invoice.code}</h3><p>Saldo pendiente: {money(balance)}</p><div className="form-grid"><label>Importe<input type="number" min="0.01" max={balance} step="0.01" value={amount} onChange={(event) => setAmount(event.target.value)} required /></label><label>Fecha<input type="date" value={paidAt} onChange={(event) => setPaidAt(event.target.value)} required /></label><label>Método<select value={method} onChange={(event) => setMethod(event.target.value)}><option value="transferencia">Transferencia</option><option value="tarjeta">Tarjeta</option><option value="efectivo">Efectivo</option><option value="domiciliacion">Domiciliación</option><option value="otro">Otro</option></select></label></div><label>Referencia<input value={reference} onChange={(event) => setReference(event.target.value)} /></label><label>Notas<textarea value={notes} onChange={(event) => setNotes(event.target.value)} /></label>{error && <p className="form-error">{error}</p>}<div className="modal-footer"><button type="button" onClick={onClose} disabled={saving}>Cancelar</button><button className="primary" disabled={saving}>Registrar cobro</button></div></form></div>; }

function ReasonModal({ title, onClose, onConfirm }: { title: string; onClose: () => void; onConfirm: (reason: string) => Promise<void> }) { const [reason, setReason] = useState(''); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const submit = async (event: FormEvent) => { event.preventDefault(); if (!reason.trim()) { setError('El motivo es obligatorio.'); return; } setSaving(true); setError(''); try { await onConfirm(reason.trim()); } catch (err) { setError(errorText(err)); setSaving(false); } }; return <div className="mini-modal" role="dialog" aria-modal="true"><form onSubmit={submit}><h3>{title}</h3><label>Motivo obligatorio<textarea value={reason} onChange={(event) => setReason(event.target.value)} /></label>{error && <p className="form-error">{error}</p>}<div className="modal-footer"><button type="button" onClick={onClose} disabled={saving}>Cancelar</button><button className="danger" disabled={saving}>Confirmar</button></div></form></div>; }
