import type { Profile } from '../shared/types';
import { pendingPaymentAttempt, recordPaymentOperation, type PaymentAttempt } from '../services/paymentOperations';
import { localDateKey } from '../shared/localDate';
import { useEffect, useRef, useState, type FormEvent } from 'react';
import { billingService } from '../services/billingService';
import { treasuryService } from '../services/treasuryService';
import { ModalShell } from '../components/FormPrimitives';

const money = (value: unknown) => `${Number(value ?? 0).toLocaleString('es-ES', { minimumFractionDigits: 2, maximumFractionDigits: 2 })} €`;

export function CustomerPaymentModal({ profile, invoice, onClose, onSaved }: { profile: Profile | null; invoice: any; onClose: () => void; onSaved: () => void }) {
  const submitting = useRef(false);
  const scope = { profileId: profile?.id ?? '', companyId: profile?.company_id ?? '' };
  const [pending, setPending] = useState<PaymentAttempt | null>(null);
  const refreshAttempt = () => { try { setPending(pendingPaymentAttempt(scope, 'customer', invoice.id)); } catch (err) { setError(err instanceof Error ? err.message : 'No se puede recuperar el envío.'); } };
  useEffect(() => { refreshAttempt(); }, [profile?.id, profile?.company_id, invoice.id]);
  const balance = Math.max(Number(invoice.total_amount) - Number(invoice.paid_amount), 0);
  const [accounts, setAccounts] = useState<any[]>([]); const [accountId, setAccountId] = useState(''); const [amount, setAmount] = useState(String(balance)); const [paidAt, setPaidAt] = useState(localDateKey()); const [method, setMethod] = useState('transferencia'); const [reference, setReference] = useState(''); const [notes, setNotes] = useState(''); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  useEffect(() => { treasuryService.accounts().then((rows) => setAccounts(rows.filter((row) => row.active && row.currency_code === 'EUR'))).catch((err) => setError(err instanceof Error ? err.message : 'No se han podido cargar las cuentas.')); }, []);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (submitting.current) return; if (!pending && !accountId) { setError('Selecciona la cuenta destino.'); return; } if (!pending && (Number(amount) <= 0 || Number(amount) > balance)) { setError('El importe debe ser positivo y no superar el saldo.'); return; } submitting.current = true; setSaving(true); setError(''); try { if (pending) await recordPaymentOperation(scope, 'customer', pending.payload); else await billingService.recordPayment(invoice.id, { amount: Number(amount), paid_at: paidAt, method, reference, notes, treasury_account_id: accountId }, scope); setPending(null); onSaved(); } catch (err) { refreshAttempt(); setError(err instanceof Error ? err.message : 'No se ha podido registrar el cobro.'); } finally { submitting.current = false; setSaving(false); } };
  return <ModalShell title={`Registrar cobro · ${invoice.code}`} onClose={onClose} canClose={!saving}><form onSubmit={submit}>{pending && <p role="status">Envío pendiente de confirmar: {money(pending.payload.amount)} · {pending.payload.date}. Recuperar conserva los datos del envío original.</p>}<fieldset disabled={saving || Boolean(pending)} style={{ border: 0, padding: 0, margin: 0, minWidth: 0 }}><p>Saldo pendiente: {money(balance)}</p><div className="form-grid"><label>Cuenta destino *<select value={accountId} onChange={(event) => setAccountId(event.target.value)} required><option value="">Selecciona cuenta</option>{accounts.map((account) => <option key={account.treasury_account_id} value={account.treasury_account_id}>{account.name} · Saldo DMP {money(account.balance)}</option>)}</select></label><label>Importe<input type="number" min="0.01" max={balance} step="0.01" value={amount} onChange={(event) => setAmount(event.target.value)} required /></label><label>Fecha<input type="date" value={paidAt} onChange={(event) => setPaidAt(event.target.value)} required /></label><label>Método<select value={method} onChange={(event) => setMethod(event.target.value)}><option value="transferencia">Transferencia</option><option value="tarjeta">Tarjeta</option><option value="efectivo">Efectivo</option><option value="domiciliacion">Domiciliación</option><option value="otro">Otro</option></select></label></div><label>Referencia<input value={reference} onChange={(event) => setReference(event.target.value)} /></label><label>Notas<textarea value={notes} onChange={(event) => setNotes(event.target.value)} /></label></fieldset>{error && <p className="form-error" role="alert">{error}</p>}<div className="modal-footer"><button type="button" onClick={onClose} disabled={saving}>Cancelar</button><button className="primary" disabled={saving}>{saving ? 'Guardando...' : pending ? 'Recuperar envío pendiente' : 'Registrar cobro'}</button></div></form></ModalShell>;
}
