import { useEffect, useState, type FormEvent } from 'react';
import { billingService } from '../services/billingService';
import { treasuryService } from '../services/treasuryService';

const money = (value: unknown) => `${Number(value ?? 0).toLocaleString('es-ES', { minimumFractionDigits: 2, maximumFractionDigits: 2 })} €`;

export function CustomerPaymentModal({ invoice, onClose, onSaved }: { invoice: any; onClose: () => void; onSaved: () => void }) {
  const balance = Math.max(Number(invoice.total_amount) - Number(invoice.paid_amount), 0);
  const [accounts, setAccounts] = useState<any[]>([]); const [accountId, setAccountId] = useState(''); const [amount, setAmount] = useState(String(balance)); const [paidAt, setPaidAt] = useState(new Date().toISOString().slice(0, 10)); const [method, setMethod] = useState('transferencia'); const [reference, setReference] = useState(''); const [notes, setNotes] = useState(''); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  useEffect(() => { treasuryService.accounts().then((rows) => setAccounts(rows.filter((row) => row.active && row.currency_code === 'EUR'))).catch((err) => setError(err instanceof Error ? err.message : 'No se han podido cargar las cuentas.')); }, []);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!accountId) { setError('Selecciona la cuenta destino.'); return; } if (Number(amount) <= 0 || Number(amount) > balance) { setError('El importe debe ser positivo y no superar el saldo.'); return; } setSaving(true); setError(''); try { await billingService.recordPayment(invoice.id, { amount: Number(amount), paid_at: paidAt, method, reference, notes, treasury_account_id: accountId }); onSaved(); } catch (err) { setError(err instanceof Error ? err.message : 'No se ha podido registrar el cobro.'); } finally { setSaving(false); } };
  return <div className="mini-modal" role="dialog" aria-modal="true"><form onSubmit={submit}><h3>Registrar cobro · {invoice.code}</h3><p>Saldo pendiente: {money(balance)}</p><div className="form-grid"><label>Cuenta destino *<select value={accountId} onChange={(event) => setAccountId(event.target.value)} required><option value="">Selecciona cuenta</option>{accounts.map((account) => <option key={account.treasury_account_id} value={account.treasury_account_id}>{account.name} · Saldo DMP {money(account.balance)}</option>)}</select></label><label>Importe<input type="number" min="0.01" max={balance} step="0.01" value={amount} onChange={(event) => setAmount(event.target.value)} required /></label><label>Fecha<input type="date" value={paidAt} onChange={(event) => setPaidAt(event.target.value)} required /></label><label>Método<select value={method} onChange={(event) => setMethod(event.target.value)}><option value="transferencia">Transferencia</option><option value="tarjeta">Tarjeta</option><option value="efectivo">Efectivo</option><option value="domiciliacion">Domiciliación</option><option value="otro">Otro</option></select></label></div><label>Referencia<input value={reference} onChange={(event) => setReference(event.target.value)} /></label><label>Notas<textarea value={notes} onChange={(event) => setNotes(event.target.value)} /></label>{error && <p className="form-error">{error}</p>}<div className="modal-footer"><button type="button" onClick={onClose} disabled={saving}>Cancelar</button><button className="primary" disabled={saving}>Registrar cobro</button></div></form></div>;
}
