import { useEffect, useState } from 'react';
import type { Profile } from '../shared/types';
import { hasPermission } from '../auth/permissions';
import { supplierInvoicesService } from '../services/supplierInvoicesService';
import { supplierPaymentMethods, supplierPaymentSummary, supplierPaymentsService } from '../services/supplierPaymentsService';
import { treasuryService } from '../services/treasuryService';

const money = (value: unknown) => `${Number(value ?? 0).toLocaleString('es-ES', { minimumFractionDigits: 2, maximumFractionDigits: 2 })} €`;
const date = (value: unknown) => value ? new Date(`${String(value).slice(0, 10)}T00:00:00`).toLocaleDateString('es-ES') : '-';
const labels: Record<string, string> = { transferencia: 'Transferencia', tarjeta: 'Tarjeta', efectivo: 'Efectivo', domiciliacion: 'Domiciliación', otro: 'Otro' };
const paymentStatusLabel = 'Estado de pago';
const reversalLabel = 'Revertir pago';

export function SupplierPaymentsPanel({ profile, invoiceId }: { profile: Profile | null; invoiceId: string }) {
  const canRead = hasPermission(profile, 'supplier_payments.read'); const canCreate = hasPermission(profile, 'supplier_payments.create'); const canReverse = hasPermission(profile, 'supplier_payments.reverse');
  const [invoice, setInvoice] = useState<any>(null); const [payments, setPayments] = useState<any[]>([]); const [accounts, setAccounts] = useState<any[]>([]); const [accountId, setAccountId] = useState(''); const [amount, setAmount] = useState(''); const [paymentDate, setPaymentDate] = useState(new Date().toISOString().slice(0, 10)); const [method, setMethod] = useState<(typeof supplierPaymentMethods)[number]>('transferencia'); const [reference, setReference] = useState(''); const [notes, setNotes] = useState(''); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const [reversalId, setReversalId] = useState(''); const [reason, setReason] = useState('');
  const load = async () => { try { const [nextInvoice, nextPayments, nextAccounts] = await Promise.all([supplierInvoicesService.get(invoiceId), supplierPaymentsService.list(invoiceId), treasuryService.accounts()]); setInvoice(nextInvoice); setPayments(nextPayments); setAccounts(nextAccounts.filter((row) => row.active && row.currency_code === nextInvoice.currency_code)); setAmount(supplierPaymentSummary({ ...nextInvoice, supplier_invoice_payments: nextPayments }).outstanding_amount.toFixed(2)); } catch (err) { setError(err instanceof Error ? err.message : 'No se han podido cargar los pagos.'); } };
  useEffect(() => { if (canRead) void load(); }, [invoiceId, canRead]);
  if (!canRead) return null;
  if (!invoice) return <section className="card"><h3>Pagos</h3><p className={error ? 'form-error' : 'large-note'}>{error || 'Cargando pagos...'}</p></section>;
  const summary = supplierPaymentSummary({ ...invoice, supplier_invoice_payments: payments });
  const record = async (event: React.FormEvent) => { event.preventDefault(); if (!accountId) { setError('Selecciona la cuenta de origen.'); return; } setSaving(true); setError(''); try { await supplierPaymentsService.record(invoiceId, { amount: Number(amount), payment_date: paymentDate, payment_method: method, reference, notes, treasury_account_id: accountId }); await load(); } catch (err) { setError(err instanceof Error ? err.message : 'No se ha podido registrar el pago.'); } finally { setSaving(false); } };
  const reverse = async (paymentId: string) => { if (!reason.trim()) { setError('El motivo de reversión es obligatorio.'); return; } setSaving(true); setError(''); try { await supplierPaymentsService.reverse(paymentId, reason); setReversalId(''); setReason(''); await load(); } catch (err) { setError(err instanceof Error ? err.message : 'No se ha podido revertir el pago.'); } finally { setSaving(false); } };
  return <section className="card supplier-payments-panel"><header><h3>Pagos</h3></header><div className="info-grid"><div><dt>Total factura</dt><dd>{money(summary.total_amount)}</dd></div><div><dt>Pagado</dt><dd>{money(summary.paid_amount)}</dd></div><div><dt>Pendiente</dt><dd>{money(summary.outstanding_amount)}</dd></div><div><dt>Vencimiento</dt><dd>{date(invoice.due_date)}</dd></div></div>{error && <p className="form-error">{error}</p>}{invoice.status === 'registered' && summary.outstanding_amount > 0 && canCreate && <form onSubmit={record}><h4>Registrar pago</h4><div className="form-grid"><label>Cuenta de origen *<select value={accountId} onChange={(event) => setAccountId(event.target.value)} required><option value="">Selecciona cuenta</option>{accounts.map((account) => <option key={account.treasury_account_id} value={account.treasury_account_id}>{account.name} · Saldo DMP {money(account.balance)}</option>)}</select></label><label>Fecha<input type="date" value={paymentDate} onChange={(event) => setPaymentDate(event.target.value)} required /></label><label>Importe<input type="number" min="0.01" max={summary.outstanding_amount} step="0.01" value={amount} onChange={(event) => setAmount(event.target.value)} required /></label><label>Método<select value={method} onChange={(event) => setMethod(event.target.value as (typeof supplierPaymentMethods)[number])}>{supplierPaymentMethods.map((value) => <option key={value} value={value}>{labels[value]}</option>)}</select></label></div><label>Referencia<input value={reference} onChange={(event) => setReference(event.target.value)} /></label><label>Notas<textarea value={notes} onChange={(event) => setNotes(event.target.value)} /></label><button className="primary" disabled={saving}>Registrar pago</button></form>}{payments.length > 0 && <div className="table-card"><table><thead><tr><th>Fecha</th><th>Importe</th><th>Método</th><th>Referencia</th><th>Estado</th><th></th></tr></thead><tbody>{payments.map((payment) => <tr key={payment.id}><td>{date(payment.payment_date)}</td><td>{money(payment.amount)}</td><td>{labels[payment.payment_method] ?? payment.payment_method}</td><td>{payment.reference ?? '-'}</td><td>{payment.reversed_at ? 'Revertido' : 'Activo'}{!payment.reversed_at && !payment.treasury_transaction_id && ' · Sin movimiento de tesorería asociado'}</td><td>{canReverse && !payment.reversed_at && <button onClick={() => setReversalId(payment.id)}>Revertir</button>}</td></tr>)}</tbody></table></div>}{reversalId && <div className="form-grid"><label>Motivo de reversión *<input value={reason} onChange={(event) => setReason(event.target.value)} /></label><button className="danger" onClick={() => void reverse(reversalId)} disabled={saving}>Confirmar reversión</button></div>}</section>;
}

export function SupplierPaymentOverview({ profile }: { profile: Profile | null }) { const [rows, setRows] = useState<any[]>([]); const canRead = hasPermission(profile, 'supplier_payments.read'); useEffect(() => { if (canRead) supplierInvoicesService.list().then(setRows).catch(() => setRows([])); }, [canRead]); if (!canRead) return null; const visible = rows.filter((row) => row.status !== 'draft'); return <section className="card supplier-payment-overview"><header><h3>Resumen de pagos de proveedor</h3></header>{visible.length ? <div className="table-card"><table><thead><tr><th>Proveedor</th><th>Nº factura</th><th>Total</th><th>Pagado</th><th>Pendiente</th><th>Estado</th></tr></thead><tbody>{visible.map((row) => { const summary = row.payment_summary ?? supplierPaymentSummary(row); return <tr key={row.id}><td>{row.suppliers?.name ?? '-'}</td><td>{row.supplier_invoice_number ?? '-'}</td><td>{money(summary.total_amount)}</td><td>{money(summary.paid_amount)}</td><td>{money(summary.outstanding_amount)}</td><td>{summary.payment_status === 'paid' ? 'Pagada' : summary.payment_status === 'partially_paid' ? 'Pago parcial' : 'Sin pagar'}</td></tr>; })}</tbody></table></div> : <p className="large-note">No hay facturas registradas.</p>}</section>; }
