import { useEffect, useState } from 'react';
import type { Profile } from '../shared/types';
import { hasPermission } from '../auth/permissions';
import { supplierInvoicesService } from '../services/supplierInvoicesService';
import { supplierPaymentMethods, supplierPaymentSummary, supplierPaymentsService } from '../services/supplierPaymentsService';

const money = (value: unknown) => `${Number(value ?? 0).toLocaleString('es-ES', { minimumFractionDigits: 2, maximumFractionDigits: 2 })} €`;
const date = (value: unknown) => value ? new Date(`${String(value).slice(0, 10)}T00:00:00`).toLocaleDateString('es-ES') : '-';
const methodLabels: Record<string, string> = { transferencia: 'Transferencia', tarjeta: 'Tarjeta', efectivo: 'Efectivo', domiciliacion: 'Domiciliación', otro: 'Otro' };

export function SupplierPaymentsPanel({ profile, invoiceId }: { profile: Profile | null; invoiceId: string }) {
  const [invoice, setInvoice] = useState<any>(null); const [payments, setPayments] = useState<any[]>([]); const [error, setError] = useState(''); const [saving, setSaving] = useState(false); const [amount, setAmount] = useState(''); const [paymentDate, setPaymentDate] = useState(new Date().toISOString().slice(0, 10)); const [method, setMethod] = useState<(typeof supplierPaymentMethods)[number]>('transferencia'); const [reference, setReference] = useState(''); const [notes, setNotes] = useState(''); const [reversalId, setReversalId] = useState(''); const [reason, setReason] = useState('');
  const canRead = hasPermission(profile, 'supplier_payments.read'); const canCreate = hasPermission(profile, 'supplier_payments.create'); const canReverse = hasPermission(profile, 'supplier_payments.reverse');
  const load = async () => { try { const [nextInvoice, nextPayments] = await Promise.all([supplierInvoicesService.get(invoiceId), supplierPaymentsService.list(invoiceId)]); setInvoice(nextInvoice); setPayments(nextPayments); const nextSummary = supplierPaymentSummary({ ...nextInvoice, supplier_invoice_payments: nextPayments }); setAmount(nextSummary.outstanding_amount.toFixed(2)); } catch (err) { setError(err instanceof Error ? err.message : 'No se han podido cargar los pagos.'); } };
  useEffect(() => { if (canRead) void load(); }, [invoiceId, canRead]);
  if (!canRead) return null;
  if (!invoice) return <section className="card"><h3>Pagos</h3><p className={error ? 'form-error' : 'large-note'}>{error || 'Cargando pagos...'}</p></section>;
  const summary = supplierPaymentSummary({ ...invoice, supplier_invoice_payments: payments });
  const record = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setError(''); try { await supplierPaymentsService.record(invoiceId, { amount: Number(amount), payment_date: paymentDate, payment_method: method, reference, notes }); await load(); } catch (err) { setError(err instanceof Error ? err.message : 'No se ha podido registrar el pago.'); } finally { setSaving(false); } };
  const reverse = async (paymentId: string) => { if (!reason.trim()) { setError('El motivo de reversión es obligatorio.'); return; } setSaving(true); setError(''); try { await supplierPaymentsService.reverse(paymentId, reason); setReversalId(''); setReason(''); await load(); } catch (err) { setError(err instanceof Error ? err.message : 'No se ha podido revertir el pago.'); } finally { setSaving(false); } };
  return <section className="card supplier-payments-panel"><header><h3>Pagos</h3></header><div className="info-grid"><div><dt>Total factura</dt><dd>{money(summary.total_amount)}</dd></div><div><dt>Pagado</dt><dd>{money(summary.paid_amount)}</dd></div><div><dt>Pendiente</dt><dd>{money(summary.outstanding_amount)}</dd></div><div><dt>Vencimiento</dt><dd>{date(invoice.due_date)} {summary.overdue && <strong className="form-error">· Vencida</strong>}</dd></div><div><dt>Estado de pago</dt><dd>{summary.payment_status === 'paid' ? 'Pagada' : summary.payment_status === 'partially_paid' ? 'Pago parcial' : 'Sin pagar'}{summary.overdue && ' · Vencida'}</dd></div></div>{error && <p className="form-error">{error}</p>}{invoice.status === 'registered' && summary.outstanding_amount > 0 && canCreate && <form onSubmit={record}><h4>Registrar pago</h4><div className="form-grid"><label>Fecha<input type="date" value={paymentDate} onChange={(event) => setPaymentDate(event.target.value)} required /></label><label>Importe<input type="number" min="0.01" max={summary.outstanding_amount} step="0.01" value={amount} onChange={(event) => setAmount(event.target.value)} required /></label><label>Método<select value={method} onChange={(event) => setMethod(event.target.value as (typeof supplierPaymentMethods)[number])}>{supplierPaymentMethods.map((value) => <option key={value} value={value}>{methodLabels[value]}</option>)}</select></label></div><label>Referencia<input value={reference} onChange={(event) => setReference(event.target.value)} placeholder="Referencia bancaria u operación" /></label><label>Notas<textarea value={notes} onChange={(event) => setNotes(event.target.value)} /></label><button className="primary" disabled={saving}>{saving ? 'GUARDANDO...' : 'REGISTRAR PAGO'}</button></form>}{payments.length > 0 && <div className="table-card"><table><thead><tr><th>Fecha</th><th>Importe</th><th>Método</th><th>Referencia</th><th>Estado</th><th></th></tr></thead><tbody>{payments.map((payment) => <tr key={payment.id}><td>{date(payment.payment_date)}</td><td>{money(payment.amount)}</td><td>{methodLabels[payment.payment_method] ?? payment.payment_method}</td><td>{payment.reference ?? '-'}</td><td>{payment.reversed_at ? 'Revertido' : 'Activo'}</td><td>{!payment.reversed_at && canReverse && (reversalId === payment.id ? <span><input placeholder="Motivo obligatorio" value={reason} onChange={(event) => setReason(event.target.value)} /><button className="danger" type="button" onClick={() => reverse(payment.id)} disabled={saving}>Confirmar</button></span> : <button className="danger" type="button" onClick={() => setReversalId(payment.id)}>Revertir pago</button>)}</td></tr>)}</tbody></table></div>}{!payments.length && <p className="large-note">No hay pagos registrados.</p>}</section>;
}

export function SupplierPaymentOverview({ profile }: { profile: Profile | null }) {
  const [rows, setRows] = useState<any[]>([]); const [error, setError] = useState('');
  const canRead = hasPermission(profile, 'supplier_payments.read');
  useEffect(() => { if (canRead) supplierInvoicesService.list().then(setRows).catch((err) => setError(err instanceof Error ? err.message : 'No se ha podido cargar el resumen de pagos.')); }, [canRead]);
  if (!canRead) return null;
  const visible = rows.filter((row) => row.status !== 'draft');
  return <section className="card supplier-payment-overview"><header><h3>Resumen de pagos de proveedor</h3></header>{error && <p className="form-error">{error}</p>}{visible.length ? <div className="table-card"><table><thead><tr><th>Proveedor</th><th>Nº factura</th><th>Total</th><th>Pagado</th><th>Pendiente</th><th>Vencimiento</th><th>Estado</th></tr></thead><tbody>{visible.map((row) => { const summary = row.payment_summary ?? supplierPaymentSummary(row); return <tr key={row.id}><td>{row.suppliers?.name ?? '-'}</td><td>{row.supplier_invoice_number ?? '-'}</td><td>{money(summary.total_amount)}</td><td>{money(summary.paid_amount)}</td><td>{money(summary.outstanding_amount)}</td><td>{date(row.due_date)}{summary.overdue && ' · Vencida'}</td><td>{summary.payment_status === 'paid' ? 'Pagada' : summary.payment_status === 'partially_paid' ? 'Pago parcial' : 'Sin pagar'}{summary.overdue && ' · Vencida'}</td></tr>; })}</tbody></table></div> : <p className="large-note">No hay facturas registradas.</p>}</section>;
}
