import { localDateKey } from '../shared/localDate';
import { useState, type FormEvent } from 'react';
import { treasuryService } from '../services/treasuryService';
import { ModalShell } from '../components/FormPrimitives';

type Account = { treasury_account_id: string; name: string; currency_code: string; active: boolean };
type FormProps = { onClose: () => void; onSaved: () => void };
const today = () => localDateKey();
const message = (error: unknown, fallback: string) => error instanceof Error ? error.message : fallback;

export function SavingAccountForm({ onClose, onSaved }: FormProps) {
  const [value, setValue] = useState({ name: '', account_type: 'bank', iban: '', currency_code: 'EUR', opening_balance: '0', opening_balance_date: today(), notes: '' });
  const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (saving) return; setSaving(true); setError(''); try { await treasuryService.createAccount({ ...value, opening_balance: Number(value.opening_balance) }); onSaved(); } catch (err) { setError(message(err, 'No se ha podido crear la cuenta.')); } finally { setSaving(false); } };
  return <ModalShell title="Nueva cuenta de empresa" onClose={onClose} canClose={!saving}><form onSubmit={submit}><div className="form-grid"><label>Nombre *<input value={value.name} onChange={(e) => setValue({ ...value, name: e.target.value })} required /></label><label>Tipo<select value={value.account_type} onChange={(e) => setValue({ ...value, account_type: e.target.value })}><option value="bank">Banco</option><option value="cash">Caja</option></select></label><label>IBAN<input value={value.iban} onChange={(e) => setValue({ ...value, iban: e.target.value })} /></label><label>Moneda<input value={value.currency_code} maxLength={3} onChange={(e) => setValue({ ...value, currency_code: e.target.value.toUpperCase() })} required /></label><label>Saldo inicial<input type="number" step="0.01" value={value.opening_balance} onChange={(e) => setValue({ ...value, opening_balance: e.target.value })} /></label><label>Fecha saldo inicial<input type="date" value={value.opening_balance_date} onChange={(e) => setValue({ ...value, opening_balance_date: e.target.value })} required /></label></div>{error && <p className="form-error" role="alert">{error}</p>}<div className="modal-footer"><button type="button" onClick={onClose} disabled={saving}>Cancelar</button><button className="primary" disabled={saving}>{saving ? 'Guardando…' : 'Crear cuenta'}</button></div></form></ModalShell>;
}

export function SavingMovementForm({ accounts, onClose, onSaved }: FormProps & { accounts: Account[] }) {
  const [value, setValue] = useState({ accountId: '', direction: 'outflow' as 'inflow' | 'outflow', amount: '', date: today(), concept: '', reference: '' });
  const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (saving) return; setSaving(true); setError(''); try { await treasuryService.manual({ ...value, amount: Number(value.amount) }); onSaved(); } catch (err) { setError(message(err, 'No se ha podido registrar el movimiento.')); } finally { setSaving(false); } };
  return <ModalShell title="Nuevo movimiento manual" onClose={onClose} canClose={!saving}><form onSubmit={submit}><div className="form-grid"><label>Cuenta *<select value={value.accountId} onChange={(e) => setValue({ ...value, accountId: e.target.value })} required><option value="">Selecciona cuenta</option>{accounts.filter((a) => a.active).map((a) => <option key={a.treasury_account_id} value={a.treasury_account_id}>{a.name} · {a.currency_code}</option>)}</select></label><label>Tipo<select value={value.direction} onChange={(e) => setValue({ ...value, direction: e.target.value as 'inflow' | 'outflow' })}><option value="inflow">Entrada</option><option value="outflow">Salida</option></select></label><label>Importe<input type="number" min="0.01" step="0.01" value={value.amount} onChange={(e) => setValue({ ...value, amount: e.target.value })} required /></label><label>Fecha<input type="date" value={value.date} onChange={(e) => setValue({ ...value, date: e.target.value })} required /></label></div><label>Concepto / motivo *<input value={value.concept} onChange={(e) => setValue({ ...value, concept: e.target.value })} required /></label><label>Referencia<input value={value.reference} onChange={(e) => setValue({ ...value, reference: e.target.value })} /></label>{error && <p className="form-error" role="alert">{error}</p>}<div className="modal-footer"><button type="button" onClick={onClose} disabled={saving}>Cancelar</button><button className="primary" disabled={saving}>{saving ? 'Guardando…' : 'Registrar'}</button></div></form></ModalShell>;
}

export function SavingTransferForm({ accounts, onClose, onSaved }: FormProps & { accounts: Account[] }) {
  const [value, setValue] = useState({ fromAccountId: '', toAccountId: '', amount: '', date: today(), reference: '', notes: '' });
  const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (saving) return; setSaving(true); setError(''); try { await treasuryService.transfer({ ...value, amount: Number(value.amount) }); onSaved(); } catch (err) { setError(message(err, 'No se ha podido transferir.')); } finally { setSaving(false); } };
  return <ModalShell title="Transferir entre cuentas" onClose={onClose} canClose={!saving}><form onSubmit={submit}><p className="large-note">La transferencia mueve dinero entre cuentas propias y no cambia el saldo total por moneda.</p><div className="form-grid"><label>Cuenta origen *<select value={value.fromAccountId} onChange={(e) => setValue({ ...value, fromAccountId: e.target.value })} required><option value="">Selecciona cuenta</option>{accounts.filter((a) => a.active).map((a) => <option key={a.treasury_account_id} value={a.treasury_account_id}>{a.name} · {a.currency_code}</option>)}</select></label><label>Cuenta destino *<select value={value.toAccountId} onChange={(e) => setValue({ ...value, toAccountId: e.target.value })} required><option value="">Selecciona cuenta</option>{accounts.filter((a) => a.active).map((a) => <option key={a.treasury_account_id} value={a.treasury_account_id}>{a.name} · {a.currency_code}</option>)}</select></label><label>Importe<input type="number" min="0.01" step="0.01" value={value.amount} onChange={(e) => setValue({ ...value, amount: e.target.value })} required /></label><label>Fecha<input type="date" value={value.date} onChange={(e) => setValue({ ...value, date: e.target.value })} required /></label></div><label>Referencia<input value={value.reference} onChange={(e) => setValue({ ...value, reference: e.target.value })} /></label><label>Notas<textarea value={value.notes} onChange={(e) => setValue({ ...value, notes: e.target.value })} /></label>{error && <p className="form-error" role="alert">{error}</p>}<div className="modal-footer"><button type="button" onClick={onClose} disabled={saving}>Cancelar</button><button className="primary" disabled={saving}>{saving ? 'Guardando…' : 'Transferir'}</button></div></form></ModalShell>;
}
