-- 094 postflight: lectura exclusiva, un result set.
with checks as (
  select 'schema' category,'billing_decision columns' check_name,count(*)::text actual_value,'2' expected_value,case when count(*)=2 then 'OK' else 'REVISAR' end status from information_schema.columns where table_schema='public' and column_name='billing_decision' and table_name in ('work_order_planned_material_decisions','work_order_quote_line_decisions')
  union all select 'constraints','billing checks',count(*)::text,'2',case when count(*)=2 then 'OK' else 'REVISAR' end from information_schema.table_constraints where constraint_schema='public' and constraint_name in ('work_order_planned_material_decisions_billing_check','work_order_quote_line_decisions_billing_check')
  union all select 'rpc','decision RPC',count(*)::text,'1',case when count(*)=1 then 'OK' else 'REVISAR' end from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='dmp_set_work_order_billing_decision' and pg_get_function_identity_arguments(p.oid)='uuid, text, uuid, text'
  union all select 'rpc','recalculation RPC',count(*)::text,'1',case when count(*)=1 then 'OK' else 'REVISAR' end from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='dmp_recalculate_work_order_economics'
  union all select 'grants','decision authenticated execute',count(*)::text,'1',case when count(*)=1 then 'OK' else 'REVISAR' end from information_schema.routine_privileges where specific_schema='public' and routine_name='dmp_set_work_order_billing_decision' and grantee='authenticated' and privilege_type='EXECUTE'
  union all select 'security','decision RPC security definer',count(*)::text,'1',case when count(*)=1 then 'OK' else 'REVISAR' end from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='dmp_set_work_order_billing_decision' and p.prosecdef
  union all select 'security','eligibility security definer',count(*)::text,'1',case when count(*)=1 then 'OK' else 'REVISAR' end from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='dmp_guided_billing_eligible' and p.prosecdef
  union all select 'security','preparation security definer',count(*)::text,'1',case when count(*)=1 then 'OK' else 'REVISAR' end from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='dmp_prepare_invoice_from_work_order' and p.prosecdef
  union all select 'safety','active warranty drafts',count(*)::text,'0 or reviewed','REVISAR' from public.invoice_work_orders l join public.invoices i on i.id=l.invoice_id join public.work_orders w on w.id=l.work_order_id where l.deleted_at is null and i.status='borrador' and w.warranty
  union all select 'safety','warranty issued invoice rows changed by 094',count(*)::text,'NO AUTOMATIC CHECK','MANUAL' from public.invoice_work_orders l join public.invoices i on i.id=l.invoice_id join public.work_orders w on w.id=l.work_order_id where l.deleted_at is null and i.status<>'borrador' and w.warranty
  union all select 'tenant','decision tenant mismatches',count(*)::text,'0',case when count(*)=0 then 'OK' else 'BLOQUEAR' end from public.work_order_quote_line_decisions d join public.work_orders w on w.id=d.work_order_id where d.company_id<>w.company_id
  union all select 'orphan','orphan material decisions',count(*)::text,'0',case when count(*)=0 then 'OK' else 'REVISAR' end from public.work_order_planned_material_decisions d left join public.work_orders w on w.id=d.work_order_id where w.id is null
)
select category,check_name,actual_value,expected_value,status from checks order by category,check_name;
-- NO APLICAR. REFERENCIA DE BORRADOR. DISENO SUPERADO POR AUDITORIA FUNDACIONAL.
