-- Read-only postflight for 079. Run after applying 079.

with checks(check_group,check_name,status,affected_rows,details) as (
  select 'DEPENDENCIES','draft_prepare_rpc',case when to_regprocedure('public.dmp_prepare_invoice_from_work_order(uuid,date,text,numeric)') is not null then 'OK' else 'BLOCKER' end,1,'RPC de preparar disponible'
  union all select 'DEPENDENCIES','detail_source_logic',case when position('quote_lines' in lower(pg_get_functiondef(p.oid)))>0 and position('work_order_materials' in lower(pg_get_functiondef(p.oid)))>0 and position('work_order_time_entries' in lower(pg_get_functiondef(p.oid)))>0 and position('work_order_cost_entries' in lower(pg_get_functiondef(p.oid)))>0 then 'OK' else 'BLOCKER' end,1,'RPC contempla fuentes economicas persistidas' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='dmp_prepare_invoice_from_work_order'
  union all select 'GENERAL','active_invoice_duplicates',case when count(*)=0 then 'OK' else 'BLOCKER' end,count(*)::bigint,count(*)::text||' partes con enlaces activos duplicados' from(select work_order_id from public.invoice_work_orders where deleted_at is null and work_order_id is not null group by work_order_id having count(*)>1)d
  union all select 'GENERAL','invoice_tenant_mismatch',case when count(*)=0 then 'OK' else 'BLOCKER' end,count(*)::bigint,count(*)::text||' enlaces con tenant incompatible' from public.invoice_work_orders l join public.invoices i on i.id=l.invoice_id join public.work_orders w on w.id=l.work_order_id where l.company_id is distinct from i.company_id or l.company_id is distinct from w.company_id
  union all select 'GENERAL','drafts_with_payments',case when count(*)=0 then 'OK' else 'BLOCKER' end,count(*)::bigint,count(*)::text||' borradores con cobros' from public.invoice_payments p join public.invoices i on i.id=p.invoice_id where i.status='borrador'
  union all select 'GENERAL','drafts_without_source',case when count(*)=0 then 'OK' else 'REVIEW' end,count(*)::bigint,count(*)::text||' borradores sin parte asociado; revisar si son manuales' from public.invoices i left join public.invoice_work_orders l on l.invoice_id=i.id and l.deleted_at is null and l.work_order_id is not null where i.status='borrador' and l.id is null
  union all select 'GENERAL','ambiguous_amounts',case when count(*)=0 then 'OK' else 'REVIEW' end,count(*)::bigint,count(*)::text||' partes sin sale_amount real siguen requiriendo revision' from public.work_orders where deleted_at is null and office_validation_status='validated' and economic_status='pendiente_facturar' and coalesce(warranty,false)=false and coalesce(billable,true)=true and coalesce(sale_amount,0)=0 and not exists(select 1 from public.invoice_work_orders l where l.work_order_id=work_orders.id and l.deleted_at is null)
  union all select 'GENERAL','drafts_with_fiscal_code',case when count(*)=0 then 'OK' else 'BLOCKER' end,count(*)::bigint,count(*)::text||' borradores con codigo fiscal' from public.invoices where status='borrador' and code is not null
  union all select 'GENERAL','drafts_mark_work_order_invoiced',case when count(*)=0 then 'OK' else 'BLOCKER' end,count(*)::bigint,count(*)::text||' partes facturados antes de emitir' from public.invoice_work_orders l join public.invoices i on i.id=l.invoice_id join public.work_orders w on w.id=l.work_order_id where i.status='borrador' and w.economic_status='facturado'
  union all select 'GENERAL','negative_amounts',case when count(*)=0 then 'OK' else 'BLOCKER' end,count(*)::bigint,count(*)::text||' importes negativos' from(select id from public.invoices where subtotal<0 or tax_amount<0 or total_amount<0 union all select id from public.invoice_work_orders where subtotal<0 or tax_amount<0 or total_amount<0)x
)
,summary as(select 'SUMMARY'::text check_group,'postcheck_079'::text check_name,case when count(*) filter(where status='BLOCKER')>0 then 'BLOCKER' when count(*) filter(where status='REVIEW')>0 then 'REVIEW' else 'OK' end status,count(*) filter(where status<>'OK')::bigint affected_rows,case when count(*) filter(where status='BLOCKER')>0 then 'Se han detectado BLOCKER.' when count(*) filter(where status='REVIEW')>0 then 'No hay BLOCKER, pero existen REVIEW.' else '079 validada sin BLOCKER ni REVIEW.' end details from checks)
select check_group,check_name,status,affected_rows,details from (select * from checks union all select * from summary) result order by case check_group when 'SUMMARY' then 2 else 1 end,case status when 'BLOCKER' then 1 when 'REVIEW' then 2 when 'INFO' then 3 else 4 end,check_name;
