-- 092 postflight. Read-only; execute after applying migration 092 in a controlled environment.
with checks as (
  select 'RPC'::text as area, 'delete_draft_rpc'::text as check_name, case when exists(select 1 from pg_proc where pronamespace='public'::regnamespace and proname='dmp_delete_invoice_draft' and pg_get_function_identity_arguments(oid)='p_invoice_id uuid') then 'OK' else 'BLOCKER' end as status, count(*)::bigint as finding_count, 'RPC y firma esperada'::text as detail from pg_proc where pronamespace='public'::regnamespace and proname='dmp_delete_invoice_draft' and pg_get_function_identity_arguments(oid)='p_invoice_id uuid'
  union all select 'RPC','authenticated_execute',case when has_function_privilege('authenticated','public.dmp_delete_invoice_draft(uuid)','execute') then 'OK' else 'BLOCKER' end,1,'authenticated puede invocar la RPC'
  union all select 'RPC','anon_execute_revoked',case when not has_function_privilege('anon','public.dmp_delete_invoice_draft(uuid)','execute') then 'OK' else 'BLOCKER' end,1,'anon no puede invocar la RPC'
  union all select 'DATA','issued_with_fiscal_snapshot_intact',case when count(*) filter(where i.status in('emitida','parcialmente_cobrada','cobrada','cancelada') and i.fiscal_snapshot is null)>0 then 'REVIEW' else 'OK' end,count(*) filter(where i.status in('emitida','parcialmente_cobrada','cobrada','cancelada') and i.fiscal_snapshot is null)::bigint,'No se modifican facturas emitidas; snapshots historicos previos a 081 pueden requerir revision' from public.invoices i
  union all select 'DATA','invoice_work_orders_orphans',case when count(*)=0 then 'OK' else 'BLOCKER' end,count(*)::bigint,'No hay enlaces sin invoice padre' from public.invoice_work_orders l left join public.invoices i on i.id=l.invoice_id where i.id is null
  union all select 'DATA','invoice_payments_orphans',case when count(*)=0 then 'OK' else 'BLOCKER' end,count(*)::bigint,'No hay pagos sin invoice padre' from public.invoice_payments p left join public.invoices i on i.id=p.invoice_id where i.id is null
  union all select 'DATA','invoice_lines_model',case when to_regclass('public.invoice_lines') is null then 'OK' else 'REVIEW' end,case when to_regclass('public.invoice_lines') is null then 0 else 1 end,'El modelo canonico usa invoice_work_orders'
  union all select 'STRUCTURE','draft_status_constraint',case when exists(select 1 from pg_constraint c join pg_class r on r.oid=c.conrelid join pg_namespace n on n.oid=r.relnamespace where n.nspname='public' and r.relname='invoices' and c.conname='invoices_status_check' and pg_get_constraintdef(c.oid) ilike '%borrador%') then 'OK' else 'BLOCKER' end,1,'La constraint de estados conserva borrador'
  union all select 'STRUCTURE','fiscal_snapshot_column',case when exists(select 1 from information_schema.columns c where c.table_schema='public' and c.table_name='invoices' and c.column_name='fiscal_snapshot') then 'OK' else 'BLOCKER' end,1,'fiscal_snapshot sigue disponible'
  union all select 'STRUCTURE','draft_code_nullable',case when exists(select 1 from information_schema.columns c where c.table_schema='public' and c.table_name='invoices' and c.column_name='code' and c.is_nullable='YES') then 'OK' else 'BLOCKER' end,1,'Los borradores no tienen numeracion obligatoria'
  union all select 'DATA','drafts_with_payments',case when count(*)=0 then 'OK' else 'BLOCKER' end,count(*)::bigint,'No hay movimientos asociados a borradores' from public.invoice_payments p join public.invoices i on i.id=p.invoice_id where i.status='borrador'
  union all select 'DATA','drafts_with_fiscal_snapshot',case when count(*)=0 then 'OK' else 'BLOCKER' end,count(*)::bigint,'No hay snapshots fiscales en borradores' from public.invoices i where i.status='borrador' and i.fiscal_snapshot is not null
  union all select 'DATA','drafts_with_fiscal_number',case when count(*)=0 then 'OK' else 'BLOCKER' end,count(*)::bigint,'No hay numeros fiscales en borradores' from public.invoices i where i.status='borrador' and i.code is not null
  union all select 'SECURITY','direct_delete_policies',case when count(*)=3 then 'OK' else 'BLOCKER' end,count(*)::bigint,'DELETE directo sigue denegado en las tres tablas de facturacion' from pg_policies where schemaname='public' and policyname in ('invoices_direct_delete_denied','invoice_work_orders_direct_delete_denied','invoice_payments_direct_delete_denied')
  union all select 'SECURITY','delete_rpc_security_definer',case when p.prosecdef then 'OK' else 'BLOCKER' end,1,'La RPC 092 corre con permisos del propietario' from pg_proc p where p.pronamespace='public'::regnamespace and p.proname='dmp_delete_invoice_draft' and pg_get_function_identity_arguments(p.oid)='p_invoice_id uuid'
  union all select 'SECURITY','delete_rpc_search_path',case when p.proconfig @> array['search_path=public'] then 'OK' else 'BLOCKER' end,1,'La RPC 092 fija search_path=public' from pg_proc p where p.pronamespace='public'::regnamespace and p.proname='dmp_delete_invoice_draft' and pg_get_function_identity_arguments(p.oid)='p_invoice_id uuid'
  union all select 'DATA','active_invoice_duplicates',case when count(*)=0 then 'OK' else 'BLOCKER' end,count(*)::bigint,'No hay partes con multiples enlaces activos' from (select l.work_order_id from public.invoice_work_orders l where l.deleted_at is null and l.work_order_id is not null group by l.work_order_id having count(*)>1) d
  union all select 'DATA','invoice_tenant_mismatch',case when count(*)=0 then 'OK' else 'BLOCKER' end,count(*)::bigint,'No hay enlaces con tenant incompatible' from public.invoice_work_orders l join public.invoices i on i.id=l.invoice_id join public.work_orders w on w.id=l.work_order_id where l.company_id is distinct from i.company_id or l.company_id is distinct from w.company_id
  union all select 'COMPATIBILITY','required_rpc_078_079_081_091',case when count(*) >= 4 then 'OK' else 'BLOCKER' end,count(*)::bigint,coalesce(string_agg(distinct proname,', ' order by proname),'Faltan RPC protegidas') from pg_proc where pronamespace='public'::regnamespace and proname in ('dmp_prepare_invoice_from_work_order','dmp_update_invoice_draft','dmp_issue_invoice','dmp_guided_billing_eligible')
  union all select 'AUDIT','delete_operation_allowed',case when exists(select 1 from pg_constraint c join pg_class r on r.oid=c.conrelid join pg_namespace n on n.oid=r.relnamespace where n.nspname='public' and r.relname='audit_log' and c.conname='audit_log_operation_check' and pg_get_constraintdef(c.oid) ilike '%DELETE%') then 'OK' else 'BLOCKER' end,1,'La auditoria usa DELETE sin ampliar el catalogo'
)
select area, check_name, status, finding_count, detail from checks order by area, check_name;
