-- READ ONLY postflight for 089. Does not execute business RPCs. Returns one result set.
with checks as (
  select 'sat_rpc_signature' check_name, case when to_regprocedure('public.dmp_review_work_order_sat(uuid,text,text,uuid,jsonb,text)') is not null then 'OK' else 'BLOCKER' end status, 'RPC SAT con commercial_profile_id' detail
  union all select 'sat_rpc_grant', case when has_function_privilege('authenticated','public.dmp_review_work_order_sat(uuid,text,text,uuid,jsonb,text)','EXECUTE') and not has_function_privilege('anon','public.dmp_review_work_order_sat(uuid,text,text,uuid,jsonb,text)','EXECUTE') then 'OK' else 'BLOCKER' end, 'Solo authenticated ejecuta la RPC SAT'
  union all select 'queue_rpc_signature', case when to_regprocedure('public.dmp_department_routing_queue(text)') is not null then 'OK' else 'BLOCKER' end, 'Cola departamental segura presente'
  union all select 'reassignment_rpc_signature', case when to_regprocedure('public.dmp_reassign_work_order_commercial(uuid,uuid)') is not null then 'OK' else 'BLOCKER' end, 'RPC de reasignacion presente'
  union all select 'sat_function_guardrails', case when position('p_commercial_profile_id' in lower(coalesce((select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='dmp_review_work_order_sat' limit 1),'')))>0 and position('p_destination=''comercial''' in lower(coalesce((select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='dmp_review_work_order_sat' limit 1),'')))>0 and position('current_responsible_id' in lower(coalesce((select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='dmp_review_work_order_sat' limit 1),'')))>0 then 'OK' else 'BLOCKER' end, 'SAT valida destino, comercial y asignacion atomica'
  union all select 'commercial_function_guardrails', case when position('current_responsible_id' in lower(coalesce((select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='dmp_review_work_order_commercial' limit 1),'')))>0 and position('commercial_review_status' in lower(coalesce((select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='dmp_review_work_order_commercial' limit 1),'')))>0 then 'OK' else 'BLOCKER' end, 'Comercial valida responsable antes de aprobar'
  union all select 'queue_isolation_guardrail', case when position('current_responsible_id=public.current_profile_id()' in lower(coalesce((select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='dmp_department_routing_queue' limit 1),'')))>0 and position('v_supervisor' in lower(coalesce((select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='dmp_department_routing_queue' limit 1),'')))>0 then 'OK' else 'BLOCKER' end, 'Cola Comercial distingue actor y supervisor'
  union all select 'pending_assignment_coherence', case when count(*)=0 then 'OK' else 'BLOCKER' end, count(*)::text||' pendientes Comerciales incoherentes' from public.work_orders wo where wo.deleted_at is null and wo.commercial_review_status='pending' and (wo.sat_review_destination<>'comercial' or wo.current_responsible_id is null)
  union all select 'legacy_requeue_coherence', case when count(*)=0 then 'OK' else 'BLOCKER' end, count(*)::text||' candidatos historicos siguen en Comercial sin responsable' from public.work_orders wo where wo.deleted_at is null and wo.commercial_review_status='pending' and wo.sat_review_status='approved' and wo.sat_review_destination='comercial' and (wo.current_responsible_id is null or not exists (select 1 from public.profiles p where p.id=wo.current_responsible_id and p.company_id=wo.company_id and p.active=true and p.deleted_at is null and (p.primary_area='Comercial' or exists (select 1 from public.profile_roles pr join public.roles r on r.id=pr.role_id where pr.profile_id=p.id and r.name='Comercial'))))
  union all select 'sat_requeue_destination_coherence', case when count(*)=0 then 'OK' else 'BLOCKER' end, count(*)::text||' partes pendientes SAT con destino residual' from public.work_orders where deleted_at is null and sat_review_status='pending' and sat_review_destination is not null
  union all select 'billing_legacy_population', 'REVIEW', count(*)::text||' partes historicos sin routing 088/089' from public.work_orders wo where wo.deleted_at is null and wo.office_validation_status='pending' and wo.sat_review_status='not_started' and wo.sat_review_destination is null and wo.sat_reviewed_at is null and wo.commercial_review_status='not_started' and wo.commercial_reviewed_at is null
  union all select 'billing_origins_coherence', case when count(*)=0 then 'OK' else 'BLOCKER' end, count(*)::text||' contradicciones nuevas con intencion de Facturacion sin routing aprobado' from public.work_orders wo where wo.deleted_at is null and not (wo.sat_review_status='not_started' and wo.sat_review_destination is null and wo.sat_reviewed_at is null and wo.commercial_review_status='not_started' and wo.commercial_reviewed_at is null) and not (wo.sat_review_status='pending' and wo.sat_review_destination is null and wo.commercial_review_status='not_started') and (wo.office_validation_status='validated' or wo.economic_status='pendiente_facturar' or (wo.sat_review_status='approved' and (wo.sat_review_destination is null or (wo.sat_review_destination='facturacion' and wo.commercial_review_status<>'not_started') or (wo.sat_review_destination='comercial' and wo.commercial_review_status not in ('pending','approved'))))) and not (wo.sat_review_status='approved' and ((wo.sat_review_destination='facturacion' and wo.commercial_review_status='not_started') or (wo.sat_review_destination='comercial' and wo.commercial_review_status='approved')))
  union all select 'commercial_approval_assignment_guard', case when position('v_work.current_responsible_id<>v_actor.id' in lower(coalesce((select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='dmp_review_work_order_commercial' limit 1),'')))>0 then 'OK' else 'BLOCKER' end, 'Comercial no asignado no puede aprobar'
  union all select 'billing_objects_intact', case when to_regclass('public.invoices') is not null and to_regclass('public.invoice_work_orders') is not null then 'OK' else 'BLOCKER' end, 'Facturacion e invoices intactos'
  union all select 'work_order_equipment_orphans', case when count(*)=0 then 'OK' else 'BLOCKER' end, count(*)::text||' vinculos de equipo huerfanos' from public.work_order_equipment we left join public.work_orders wo on wo.id=we.work_order_id left join public.equipment e on e.id=we.equipment_id where wo.id is null or e.id is null
  union all select 'routing_status_values', case when count(*)=0 then 'OK' else 'BLOCKER' end, count(*)::text||' partes con routing incoherente' from public.work_orders where deleted_at is null and ((sat_review_status='approved' and sat_review_destination is null) or (sat_review_destination='comercial' and commercial_review_status='pending' and current_responsible_id is null) or (sat_review_destination='facturacion' and commercial_review_status<>'not_started'))
)
select check_name,status,detail from checks order by check_name;
