-- Read-only postflight for 075. Run after applying the material write boundary.

with required_material_columns(column_name) as (
  values ('id'),('company_id'),('code'),('description'),('manufacturer'),('reference'),('unit'),('cost'),('price'),('minimum_stock'),('active'),('created_at'),('updated_at'),('deleted_at'),('stock_quantity'),('stock_controlled'),('allow_negative_stock'),('last_stock_movement_at')
),
required_movement_columns(column_name) as (
  values ('id'),('company_id'),('material_id'),('work_order_id'),('work_order_material_id'),('quote_id'),('movement_type'),('quantity'),('previous_stock'),('new_stock'),('unit_cost'),('reason'),('source'),('created_by'),('created_at'),('deleted_at')
),
constraint_state as (
  select pg_get_constraintdef(c.oid) as definition from pg_constraint c join pg_class r on r.oid=c.conrelid join pg_namespace n on n.oid=r.relnamespace where n.nspname='public' and r.relname='audit_log' and c.conname='audit_log_operation_check'
),
checks(check_group,check_name,status,affected_rows,details) as (
  select 'GENERAL','materials_table',case when to_regclass('public.materials') is not null then 'OK' else 'BLOCKER' end,case when to_regclass('public.materials') is not null then 1 else 0 end,coalesce(to_regclass('public.materials')::text,'Falta public.materials')
  union all select 'GENERAL','stock_movements_table',case when to_regclass('public.material_stock_movements') is not null then 'OK' else 'BLOCKER' end,case when to_regclass('public.material_stock_movements') is not null then 1 else 0 end,coalesce(to_regclass('public.material_stock_movements')::text,'Falta public.material_stock_movements')
  union all select 'GENERAL','materials_required_columns',case when count(*)=18 then 'OK' else 'BLOCKER' end,count(*)::bigint,count(*)::text||' de 18 columnas requeridas' from required_material_columns e join information_schema.columns c on c.table_schema='public' and c.table_name='materials' and c.column_name=e.column_name
  union all select 'GENERAL','stock_movements_required_columns',case when count(*)=16 then 'OK' else 'BLOCKER' end,count(*)::bigint,count(*)::text||' de 16 columnas requeridas' from required_movement_columns e join information_schema.columns c on c.table_schema='public' and c.table_name='material_stock_movements' and c.column_name=e.column_name
  union all select 'RPC','create_material_with_stock',case when to_regprocedure('public.dmp_create_material_with_stock(jsonb)') is not null then 'OK' else 'BLOCKER' end,case when to_regprocedure('public.dmp_create_material_with_stock(jsonb)') is not null then 1 else 0 end,coalesce(to_regprocedure('public.dmp_create_material_with_stock(jsonb)')::text,'Falta RPC 075')
  union all select 'RPC','stock_dependencies',case when to_regprocedure('public.dmp_adjust_material_stock(uuid,text,numeric,text,numeric)') is not null and to_regprocedure('public.dmp_apply_material_stock_movement(uuid,text,numeric,text,text,uuid,uuid,uuid,numeric,uuid)') is not null then 'OK' else 'BLOCKER' end,case when to_regprocedure('public.dmp_adjust_material_stock(uuid,text,numeric,text,numeric)') is not null and to_regprocedure('public.dmp_apply_material_stock_movement(uuid,text,numeric,text,text,uuid,uuid,uuid,numeric,uuid)') is not null then 2 else 0 end,'RPCs de stock 035 requeridas por 075'
  union all select 'AUDIT','material_create_operation',case when exists(select 1 from constraint_state where definition ilike '%MATERIAL_CREATE%') then 'OK' else 'BLOCKER' end,case when exists(select 1 from constraint_state where definition ilike '%MATERIAL_CREATE%') then 1 else 0 end,coalesce((select definition from constraint_state),'Falta MATERIAL_CREATE en audit_log_operation_check')
  union all select 'AUDIT','current_incompatible_audit_rows',case when count(*)=0 then 'OK' else 'BLOCKER' end,count(*)::bigint,coalesce(string_agg(distinct operation, ', ' order by operation),'Ninguna') from public.audit_log where operation not in ('INSERT','UPDATE','DELETE','SOFT_DELETE','OPERATIONAL_UPDATE','TECHNICAL_FINALIZE','TECHNICAL_FINALIZE_PENDING_OFFICE','OFFICE_VALIDATE','OFFICE_REJECT','INVOICE_ISSUE','PAYMENT_RECORD','MATERIAL_CREATE')
  union all select 'SECURITY','stock_update_column_revoked',case when count(*)=0 then 'OK' else 'BLOCKER' end,count(*)::bigint,count(*)::text||' privilegios UPDATE de authenticated sobre stock_quantity' from information_schema.column_privileges where table_schema='public' and table_name='materials' and column_name='stock_quantity' and grantee='authenticated' and privilege_type='UPDATE'
  union all select 'SECURITY','create_material_grant',case when has_function_privilege('authenticated','public.dmp_create_material_with_stock(jsonb)','EXECUTE') and not has_function_privilege('anon','public.dmp_create_material_with_stock(jsonb)','EXECUTE') then 'OK' else 'BLOCKER' end,case when has_function_privilege('authenticated','public.dmp_create_material_with_stock(jsonb)','EXECUTE') and not has_function_privilege('anon','public.dmp_create_material_with_stock(jsonb)','EXECUTE') then 1 else 0 end,'EXECUTE para authenticated y no para anon'
  union all select 'SECURITY','movement_rls',case when c.relrowsecurity then 'OK' else 'BLOCKER' end,case when c.relrowsecurity then 1 else 0 end,'RLS habilitado en material_stock_movements' from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname='material_stock_movements'
  union all select 'DATA','null_stock_values',case when count(*)=0 then 'OK' else 'BLOCKER' end,count(*)::bigint,count(*)::text||' materiales con stock_quantity NULL' from public.materials where stock_quantity is null
  union all select 'DATA','negative_stock_without_permission',case when count(*)=0 then 'OK' else 'BLOCKER' end,count(*)::bigint,count(*)::text||' materiales con stock negativo sin allow_negative_stock' from public.materials where stock_quantity<0 and not allow_negative_stock
  union all select 'DATA','movement_material_or_tenant_mismatch',case when count(*)=0 then 'OK' else 'BLOCKER' end,count(*)::bigint,count(*)::text||' movimientos sin material valido o con empresa incompatible' from public.material_stock_movements sm left join public.materials m on m.id=sm.material_id where m.id is null or sm.company_id is distinct from m.company_id
  union all select 'DATA','duplicate_material_codes',case when count(*)=0 then 'OK' else 'BLOCKER' end,count(*)::bigint,count(*)::text||' codigos de material duplicados por empresa' from (select company_id,code from public.materials group by company_id,code having count(*)>1) duplicates
  union all select 'DATA','invalid_movement_chain',case when count(*)=0 then 'OK' else 'BLOCKER' end,count(*)::bigint,count(*)::text||' movimientos con cantidad o stock final invalido' from public.material_stock_movements where quantity<=0 or new_stock<0
),
summary as (
  select 'SUMMARY'::text as check_group,'postcheck_075'::text as check_name,case when count(*) filter(where status='BLOCKER')>0 then 'BLOCKER' when count(*) filter(where status='REVIEW')>0 then 'REVIEW' else 'OK' end as status,count(*) filter(where status<>'OK')::bigint as affected_rows,case when count(*) filter(where status='BLOCKER')>0 then 'Se han detectado BLOCKER.' when count(*) filter(where status='REVIEW')>0 then 'No hay BLOCKER, pero existen REVIEW.' else '075 validada sin BLOCKER ni REVIEW.' end as details from checks
)
select check_group,check_name,status,affected_rows,details from (select * from checks union all select * from summary) result
order by case check_group when 'SUMMARY' then 2 else 1 end,case status when 'BLOCKER' then 1 when 'REVIEW' then 2 when 'INFO' then 3 else 4 end,check_name;
