-- Read-only postflight for 099. Returns one result set.
with rpc as (
  select p.oid, p.proname, pg_get_function_identity_arguments(p.oid) as signature, pg_get_functiondef(p.oid) as definition, p.prosecdef, p.proconfig
  from pg_proc p join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public' and p.proname in ('dmp_calculate_work_order_economics','dmp_review_work_order_economic','dmp_finalize_work_order_technical','dmp_prepare_invoice_from_work_order','dmp_update_invoice_draft','dmp_issue_invoice')
), historical_operations as (
  select distinct operation from public.audit_log where operation is not null
), target_operations(operation) as (
  values ('INSERT'),('UPDATE'),('DELETE'),('SOFT_DELETE'),('OPERATIONAL_UPDATE'),('TECHNICAL_FINALIZE'),
    ('TECHNICAL_FINALIZE_PENDING_OFFICE'),('OFFICE_VALIDATE'),('OFFICE_REJECT'),('INVOICE_DRAFT_CREATE'),
    ('INVOICE_DRAFT_UPDATE'),('INVOICE_ISSUE'),('INVOICE_ISSUE_OVERRIDE'),('PAYMENT_RECORD'),
    ('MATERIAL_CREATE'),('WAREHOUSE_STOCK_RECONCILE'),('ECONOMIC_REVIEW_APPROVE')
), checks as (
  select 'review_columns' check_name, (select count(*) = 4 from information_schema.columns where table_schema = 'public' and table_name = 'work_orders' and column_name in ('economic_review_status','economic_reviewed_at','economic_reviewed_by','economic_review_reason')) passed, 'work-order review metadata installed' detail
  union all select 'invoice_exception_columns', (select count(*) = 6 from information_schema.columns where table_schema = 'public' and table_name = 'invoices' and column_name in ('economic_detail_status','economic_expected_amount','economic_actual_amount','economic_override_reason','economic_override_by','economic_override_at')), 'invoice exception metadata installed'
  union all select 'unique_index_removed', not exists (select 1 from pg_indexes where schemaname = 'public' and indexname = 'invoice_work_orders_active_work_unique'), 'same work order can have multiple active lines'
  union all select 'lookup_index', exists (select 1 from pg_indexes where schemaname = 'public' and indexname = 'invoice_work_orders_active_work_lookup'), 'active line lookup installed'
  union all select 'calculate_tenant_guard', exists (select 1 from rpc where proname = 'dmp_calculate_work_order_economics' and signature = 'p_work_order_id uuid' and position('assert_member_of_current_company' in definition) > 0), 'calculate asserts active company membership'
  union all select 'calculate_direct_access_denied', not has_function_privilege('authenticated','public.dmp_calculate_work_order_economics(uuid)','execute'), 'authenticated cannot call administrative calculator directly'
  union all select 'technician_direct_access_denied', not has_function_privilege('authenticated','public.dmp_calculate_work_order_economics(uuid)','execute'), 'Technico has no direct calculator EXECUTE path'
  union all select 'economic_roles', exists (select 1 from rpc where proname = 'dmp_review_work_order_economic' and position('superadmin' in definition) > 0 and position('SAT' in definition) > 0 and position('Comercial' in definition) > 0 and position('Gerencia' in definition) > 0 and position('Oficina' in definition) = 0), 'economic modification excludes Oficina'
  union all select 'source_is_preserved', exists (select 1 from rpc where proname = 'dmp_review_work_order_economic' and position('source pertenece al snapshot historico' in definition) > 0) and not exists (select 1 from rpc where proname = 'dmp_review_work_order_economic' and position('source =' in lower(definition)) > 0), 'review does not rewrite source from facturability'
  union all select 'no_quote_source_formula', exists (select 1 from rpc where proname = 'dmp_calculate_work_order_economics' and position('coalesce(source, ''manual'') <> ''quote''' in lower(definition)) > 0) and exists (select 1 from rpc where proname = 'dmp_prepare_invoice_from_work_order' and position('coalesce(m.source, ''manual'') <> ''quote''' in lower(definition)) > 0), 'no-quote sale excludes quote-origin snapshots'
  union all select 'sellable_null_guard', exists (select 1 from rpc where proname = 'dmp_review_work_order_economic' and position('total_price is null' in lower(definition)) > 0 and position('duration_minutes is null' in lower(definition)) > 0 and position('used_quantity is null' in lower(definition)) > 0 and position('quantity is null' in lower(definition)) > 0), 'sellable null snapshots are rejected'
  union all select 'complete_review_guard', exists (select 1 from rpc where proname = 'dmp_review_work_order_economic' and position('jsonb_array_length' in lower(definition)) > 0 and position('no se puede repetir un concepto' in lower(definition)) > 0 and position('debe cubrir todos los conceptos' in lower(definition)) > 0), 'review requires complete unique decisions'
  union all select 'review_own_entries', exists (select 1 from rpc where proname = 'dmp_review_work_order_economic' and position('concepto ajeno al parte' in lower(definition)) > 0), 'review rejects foreign entry ids'
  union all select 'multiline_work_order_links', exists (select 1 from rpc where proname = 'dmp_prepare_invoice_from_work_order' and definition like '%v_invoice, v_work.id%' and lower(definition) not like '%case when not v_attached then v_work.id else null end%'), 'every prepared line keeps its work order id'
  union all select 'prepare_idempotency', exists (select 1 from rpc where proname = 'dmp_prepare_invoice_from_work_order' and position('for update' in lower(definition)) > 0 and position('count(distinct i.id)' in lower(definition)) > 0 and position('varias facturas activas' in lower(definition)) > 0), 'prepare is locked and cardinality-safe'
  union all select 'draft_single_work_order', exists (select 1 from rpc where proname = 'dmp_update_invoice_draft' and position('mezcla varios partes' in lower(definition)) > 0 and position('mismo parte' in lower(definition)) > 0), 'draft updates cannot create hybrid multi-work-order invoices'
  union all select 'invoiced_amount_aggregate', exists (select 1 from rpc where proname = 'dmp_issue_invoice' and position('group by work_order_id' in lower(definition)) > 0 and position('invoiced_amount = totals.subtotal' in lower(definition)) > 0), 'invoiced amount sums all lines per work order'
  union all select 'economic_freeze', exists (select 1 from rpc where proname = 'dmp_review_work_order_economic' and position('borrador o factura' in lower(definition)) > 0 and position('status <> ''cancelada''' in lower(definition)) > 0), 'review is blocked after draft or issued association'
  union all select 'issued_fiscal_snapshot', (select count(*) from public.invoices where status <> 'borrador' and fiscal_snapshot is not null) >= 0, (select 'non-draft invoices with fiscal snapshot=' || count(*)::text from public.invoices where status <> 'borrador' and fiscal_snapshot is not null)
  union all select 'issue_revalidation', exists (select 1 from rpc where proname = 'dmp_issue_invoice' and position('dmp_guided_billing_eligible' in lower(definition)) > 0 and position('dmp_calculate_work_order_economics' in lower(definition)) > 0 and position('economic_expected_amount' in lower(definition)) > 0 and position('borrador esta obsoleto' in lower(definition)) > 0), 'issue revalidates eligibility, current sale and stale lines'
  union all select 'issue_work_order_traceability', exists (select 1 from rpc where proname = 'dmp_issue_invoice' and position('todas las lineas activas deben conservar el parte asociado' in lower(definition)) > 0 and position('set work_order_id' in lower(definition)) = 0), 'issue rejects null or foreign work-order line links without repairing them'
  union all select 'override_only_for_mismatch', exists (select 1 from rpc where proname = 'dmp_issue_invoice' and position('excepcion solo aplica a una inconsistencia' in lower(definition)) > 0 and position('INVOICE_ISSUE_OVERRIDE' in definition) > 0), 'coherent invoices are not unnecessarily overridden'
  union all select 'issue_audit_revalidated_amounts', exists (select 1 from rpc where proname = 'dmp_issue_invoice' and position('expected_amount'', v_current_sale' in definition) > 0 and position('actual_amount'', v_subtotal' in definition) > 0), 'issue audit stores the amounts actually revalidated'
  union all select 'audit_line_before_after', exists (select 1 from rpc where proname = 'dmp_review_work_order_economic' and position('line_before' in definition) > 0 and position('line_after' in definition) > 0), 'economic review audit contains line before/after snapshots'
  union all select 'historical_audit_operations_supported', not exists (select 1 from historical_operations h where not exists (select 1 from target_operations t where t.operation = h.operation)), '099 operation set supports historical audit rows'
  union all select 'audit_constraint_present', exists (select 1 from pg_constraint c join pg_class r on r.oid = c.conrelid where r.relname = 'audit_log' and c.conname = 'audit_log_operation_check'), 'new audit operation constraint exists'
  union all select 'legacy_issue_wrapper', to_regprocedure('public.dmp_issue_invoice(uuid)') is not null and to_regprocedure('public.dmp_issue_invoice(uuid,boolean,text)') is not null, '091 one-argument issue RPC remains compatible'
  union all select 'draft_delete_present', exists (select 1 from pg_proc p join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public' and p.proname = 'dmp_delete_invoice_draft'), '092/093 draft deletion remains available'
  union all select 'authenticated_grants', (not has_function_privilege('authenticated','public.dmp_calculate_work_order_economics(uuid)','execute') and has_function_privilege('authenticated','public.dmp_review_work_order_economic(uuid,jsonb,text)','execute') and has_function_privilege('authenticated','public.dmp_issue_invoice(uuid,boolean,text)','execute')), 'calculate is private while public RPCs remain executable'
  union all select 'security_definer_search_path', (select count(*) = 7 from rpc where prosecdef and position('search_path' in coalesce(array_to_string(proconfig, ','), '')) > 0), '099 RPC overloads are security definer with search_path'
  union all select 'invoice_rls', (select relrowsecurity from pg_class where oid = 'public.invoice_work_orders'::regclass), 'invoice_work_orders RLS remains enabled'
)
select check_name, passed, detail from checks order by check_name;
