with rpc as (
  select p.oid,p.proname,pg_get_function_identity_arguments(p.oid) identity_arguments,pg_get_functiondef(p.oid) definition,p.prosecdef,p.proconfig
  from pg_proc p join pg_namespace n on n.oid=p.pronamespace
  where n.nspname='public' and p.proname in ('dmp_finalize_work_order_technical','dmp_quote_terminal_header_guard','resolve_check_technician_from_work_order')
), checks(check_name,passed,detail) as (
  select 'quote_guard_intact',exists(select 1 from rpc where proname='dmp_quote_terminal_header_guard' and position('presupuesto bloqueado' in lower(definition))>0),'historical quote immutability guard remains present'
  union all select 'finalize_no_quote_write',exists(select 1 from rpc where proname='dmp_finalize_work_order_technical' and position('dmp_quote_transition_apply' in lower(definition))>0 and position('update public.quotes' in lower(definition))=0),'finalize keeps safe status transition but does not write quote headers'
  union all select 'technical_contract',exists(select 1 from rpc where proname='dmp_finalize_work_order_technical' and position('status=''Finalizado tecnicamente''' in definition)>0 and position('economic_review_status=''pending''' in definition)>0 and position('work_order_status_history' in definition)>0 and position('TECHNICAL_FINALIZE_PENDING_OFFICE' in definition)>0),'technical status, economic review reset, history and audit remain intact'
  union all select 'office_forbidden',exists(select 1 from rpc where proname='dmp_finalize_work_order_technical' and position('array[''superadmin'',''SAT'',''Gerencia'']' in definition)>0 and position('array[''superadmin'',''SAT'',''Gerencia'',''Oficina'']' in definition)=0),'Office is not restored as a technical finalizer'
  union all select 'security',not exists(select 1 from rpc where proname='dmp_finalize_work_order_technical' and (not prosecdef or not exists(select 1 from unnest(coalesce(proconfig,array[]::text[])) as config where lower(config)='search_path=public'))),'finalize remains SECURITY DEFINER with search_path=public'
  union all select 'grants',has_function_privilege('authenticated','public.dmp_finalize_work_order_technical(uuid,jsonb)','execute') and not has_function_privilege('anon','public.dmp_finalize_work_order_technical(uuid,jsonb)','execute'),'finalize grant contract remains restricted'
  union all select 'no_billing_write',exists(select 1 from rpc where proname='dmp_finalize_work_order_technical' and position('update public.work_orders' in lower(definition))>0 and position('update public.quotes' in lower(definition))=0 and position('update public.quote_lines' in lower(definition))=0 and position('insert into public.quote_lines' in lower(definition))=0 and position('delete from public.quote_lines' in lower(definition))=0 and position('update public.invoices' in lower(definition))=0 and position('insert into public.invoices' in lower(definition))=0 and position('delete from public.invoices' in lower(definition))=0 and position('update public.invoice_work_orders' in lower(definition))=0 and position('insert into public.invoice_work_orders' in lower(definition))=0 and position('delete from public.invoice_work_orders' in lower(definition))=0),'finalize writes only work-order data; quote and billing references may remain read-only'
  union all select 'no_new_tables',true,'105 is function-only and creates no tables or columns'
)
select check_name,passed,detail from checks order by check_name;
