-- Read-only postflight for 077. Run after applying historical compatibility.

with checks(check_group,check_name,status,affected_rows,details) as (
  select 'GENERAL','historical_billable_orphans',case when count(*)=0 then 'OK' else 'BLOCKER' end,count(*)::bigint,count(*)::text||' terminales facturables siguen en not_started' from public.work_orders where deleted_at is null and status in ('Finalizado tecnicamente','Enviado','Cerrado') and office_validation_status='not_started' and coalesce(warranty,false)=false and coalesce(billable,true)=true and economic_status not in ('facturado','cobrado') and coalesce(invoiced_amount,0)=0 and not exists(select 1 from public.invoice_work_orders l where l.work_order_id=work_orders.id and l.deleted_at is null)
  union all select 'GENERAL','impossible_validation_economics',case when count(*)=0 then 'OK' else 'BLOCKER' end,count(*)::bigint,count(*)::text||' combinaciones office/economic imposibles' from public.work_orders where deleted_at is null and ((office_validation_status='validated' and economic_status='pendiente_validacion') or (office_validation_status='pending' and economic_status in ('facturado','cobrado')))
  union all select 'GENERAL','warranty_preserved',case when count(*)=0 then 'OK' else 'BLOCKER' end,count(*)::bigint,count(*)::text||' garantias con estado economico facturable' from public.work_orders where deleted_at is null and coalesce(warranty,false)=true and (coalesce(billable,true)=true or economic_status='pendiente_facturar')
  union all select 'GENERAL','non_billable_preserved',case when count(*)=0 then 'OK' else 'BLOCKER' end,count(*)::bigint,count(*)::text||' partes no facturables con estado economico facturable' from public.work_orders where deleted_at is null and coalesce(billable,true)=false and economic_status='pendiente_facturar'
  union all select 'GENERAL','ambiguous_amounts',case when count(*)=0 then 'OK' else 'REVIEW' end,count(*)::bigint,count(*)::text||' terminales billables sin sale_amount; requieren gestion explicita' from public.work_orders where deleted_at is null and status in ('Finalizado tecnicamente','Enviado','Cerrado') and office_validation_status in ('pending','validated') and coalesce(warranty,false)=false and coalesce(billable,true)=true and coalesce(sale_amount,0)=0 and coalesce(invoiced_amount,0)=0
  union all select 'BILLING','active_invoice_duplicates',case when count(*)=0 then 'OK' else 'BLOCKER' end,count(*)::bigint,count(*)::text||' partes con multiples enlaces de factura activos' from (select work_order_id from public.invoice_work_orders where deleted_at is null group by work_order_id having count(*)>1) d
  union all select 'BILLING','invoice_tenant_mismatch',case when count(*)=0 then 'OK' else 'BLOCKER' end,count(*)::bigint,count(*)::text||' enlaces con tenant incompatible' from public.invoice_work_orders l join public.invoices i on i.id=l.invoice_id join public.work_orders w on w.id=l.work_order_id where l.company_id is distinct from i.company_id or l.company_id is distinct from w.company_id
  union all select 'ECONOMICS','negative_work_order_amounts',case when count(*)=0 then 'OK' else 'BLOCKER' end,count(*)::bigint,count(*)::text||' partes con importes economicos negativos' from public.work_orders where sale_amount<0 or real_cost_amount<0 or invoiced_amount<0 or paid_amount<0
  union all select 'AUDIT','audit_operation_compatibility',case when count(*)=0 then 'OK' else 'BLOCKER' end,count(*)::bigint,coalesce(string_agg(distinct operation,', ' order by operation),'Ninguna') from public.audit_log where operation not in ('INSERT','UPDATE','DELETE','SOFT_DELETE','OPERATIONAL_UPDATE','TECHNICAL_FINALIZE','TECHNICAL_FINALIZE_PENDING_OFFICE','OFFICE_VALIDATE','OFFICE_REJECT','INVOICE_ISSUE','PAYMENT_RECORD','MATERIAL_CREATE')
  union all select 'DEPENDENCIES','review_rpc_accepts_terminal_states',case when position('v_work.status not in (''finalizado tecnicamente'',''enviado'',''cerrado'')' in lower(pg_get_functiondef(p.oid)))>0 then 'OK' else 'BLOCKER' end,case when position('v_work.status not in (''finalizado tecnicamente'',''enviado'',''cerrado'')' in lower(pg_get_functiondef(p.oid)))>0 then 1 else 0 end,'RPC de oficina acepta los tres estados finalizados'
  from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='dmp_review_work_order_office' and pg_get_function_identity_arguments(p.oid)='p_work_order_id uuid, p_decision text, p_reason text'
), summary as (
  select 'SUMMARY'::text as check_group,'postcheck_077'::text as check_name,case when count(*) filter(where status='BLOCKER')>0 then 'BLOCKER' when count(*) filter(where status='REVIEW')>0 then 'REVIEW' else 'OK' end as status,count(*) filter(where status<>'OK')::bigint as affected_rows,case when count(*) filter(where status='BLOCKER')>0 then 'Se han detectado BLOCKER.' when count(*) filter(where status='REVIEW')>0 then 'No hay BLOCKER, pero existen REVIEW.' else '077 validada sin BLOCKER ni REVIEW.' end as details from checks
)
select check_group,check_name,status,affected_rows,details from (select * from checks union all select * from summary) result order by case check_group when 'SUMMARY' then 2 else 1 end,case status when 'BLOCKER' then 1 when 'REVIEW' then 2 when 'INFO' then 3 else 4 end,check_name;
