with rpc as (
  select p.oid,p.proname,pg_get_functiondef(p.oid) definition,p.prosecdef,p.proconfig
  from pg_proc p join pg_namespace n on n.oid=p.pronamespace
  where n.nspname='public' and p.proname in ('dmp_guided_billing_eligible','dmp_prepare_invoice_from_work_order','dmp_update_invoice_draft','dmp_issue_invoice','dmp_cancel_invoice','dmp_reopen_work_order_economic')
), checks(check_name,passed,detail) as (
  select 'status_ambiguity_removed',exists(select 1 from rpc where proname='dmp_update_invoice_draft' and position('v_status text' in lower(definition))>0 and position('economic_detail_status=v_status' in lower(definition))>0 and definition !~* '(^|[ ;])status[[:space:]]+text') ,'update draft no longer declares or references ambiguous status'
  union all select 'qualified_billing_aliases',exists(select 1 from rpc where proname='dmp_update_invoice_draft' and position('decision_line.value' in lower(definition))>0 and position('work_order_record.id' in lower(definition))>0 and position('billing_entry.subtotal' in lower(definition))>0 and position('invoice_record.id' in lower(definition))>0),'update draft uses explicit billing aliases'
  union all select 'billing_functions_present',not exists(select required_name from (values ('dmp_guided_billing_eligible'),('dmp_prepare_invoice_from_work_order'),('dmp_update_invoice_draft'),('dmp_issue_invoice'),('dmp_cancel_invoice'),('dmp_reopen_work_order_economic')) required(required_name) where not exists(select 1 from rpc where rpc.proname=required_name)),'all billing RPC dependencies remain present'
  union all select 'update_contract',exists(select 1 from rpc where proname='dmp_update_invoice_draft' and position('economic_expected_amount=v_expected' in lower(definition))>0 and position('v_strict_single' in definition)>0 and position('INVOICE_DRAFT_UPDATE' in definition)>0 and prosecdef and position('search_path=public' in lower(coalesce(array_to_string(proconfig,','),'')))>0),'update draft economic mode and security contract preserved'
  union all select 'prepare_contract',exists(select 1 from rpc where proname='dmp_prepare_invoice_from_work_order' and position('i.status <> ''cancelada''' in lower(definition))>0 and position('count(distinct i.id)' in lower(definition))>0 and position('dmp_guided_billing_eligible' in definition)>0),'prepare retains active association and cancelled rebill contract'
  union all select 'issue_contract',exists(select 1 from rpc where proname='dmp_issue_invoice' and position('dmp_guided_billing_eligible' in definition)>0 and position('group by billing_entry.work_order_id' in lower(definition))>0 and position('fiscal_snapshot' in definition)>0),'issue retains eligibility, qualified per-work-order aggregation and snapshot'
  union all select 'cancel_contract',exists(select 1 from rpc where proname='dmp_cancel_invoice' and position('status=''cancelada''' in lower(definition))>0 and position('invoice_work_orders set deleted_at' in lower(definition))>0),'cancellation remains historical and soft-deletes active lines'
  union all select 'known_collision_free',not exists(select 1 from rpc where position('economic_detail_status=status' in lower(definition))>0 or position('jsonb_array_elements(p_lines) l' in lower(definition))>0),'known billing identifier collisions are absent'
  union all select 'wrappers',to_regprocedure('public.dmp_review_work_order_economic(uuid,jsonb,text)') is not null and to_regprocedure('public.dmp_issue_invoice(uuid)') is not null,'legacy wrappers remain present'
  union all select 'security',not exists(select 1 from rpc where not prosecdef or position('search_path=public' in lower(coalesce(array_to_string(proconfig,','),'')))=0),'billing RPCs remain SECURITY DEFINER with public search_path'
  union all select 'grants',has_function_privilege('authenticated','public.dmp_update_invoice_draft(uuid,jsonb,date,text,numeric)','execute') and has_function_privilege('authenticated','public.dmp_issue_invoice(uuid,boolean,text)','execute') and not has_function_privilege('anon','public.dmp_issue_invoice(uuid,boolean,text)','execute'),'billing grants remain restricted correctly'
  union all select 'no_new_tables',not exists(select 1 from pg_class where relnamespace='public'::regnamespace and relname in ('economic_reviews','invoice_lines')),'103 requires no new tables'
)
select check_name,passed,detail from checks order by check_name;
