-- Read-only postflight for 078. Run after applying 078, never as part of it.

with checks(check_group,check_name,status,affected_rows,details) as (
  select 'STRUCTURE','draft_status_constraint',case when pg_get_constraintdef(c.oid) ilike '%borrador%' then 'OK' else 'BLOCKER' end,case when pg_get_constraintdef(c.oid) ilike '%borrador%' then 1 else 0 end,'Estado de borrador disponible' from pg_constraint c join pg_class r on r.oid=c.conrelid join pg_namespace n on n.oid=r.relnamespace where n.nspname='public' and r.relname='invoices' and c.conname='invoices_status_check'
  union all select 'STRUCTURE','draft_code_nullable',case when is_nullable='YES' then 'OK' else 'BLOCKER' end,case when is_nullable='YES' then 1 else 0 end,'Los borradores no tienen numero fiscal' from information_schema.columns where table_schema='public' and table_name='invoices' and column_name='code'
  union all select 'DEPENDENCIES','prepare_rpc',case when to_regprocedure('public.dmp_prepare_invoice_from_work_order(uuid,date,text,numeric)') is not null then 'OK' else 'BLOCKER' end,1,'RPC preparar disponible'
  union all select 'DEPENDENCIES','update_rpc',case when to_regprocedure('public.dmp_update_invoice_draft(uuid,jsonb,date,text,numeric)') is not null then 'OK' else 'BLOCKER' end,1,'RPC actualizar disponible'
  union all select 'DEPENDENCIES','issue_rpc',case when to_regprocedure('public.dmp_issue_invoice(uuid)') is not null then 'OK' else 'BLOCKER' end,1,'RPC emitir disponible'
  union all select 'SECURITY','legacy_direct_issue_revoked',case when exists(select 1 from information_schema.routine_privileges where specific_schema='public' and routine_name='dmp_create_invoice_from_work_order' and grantee='authenticated' and privilege_type='EXECUTE') then 'BLOCKER' else 'OK' end,case when exists(select 1 from information_schema.routine_privileges where specific_schema='public' and routine_name='dmp_create_invoice_from_work_order' and grantee='authenticated' and privilege_type='EXECUTE') then 1 else 0 end,'No debe quedar una via autenticada para saltar el borrador'
  union all select 'GENERAL','active_invoice_duplicates',case when count(*)=0 then 'OK' else 'BLOCKER' end,count(*)::bigint,count(*)::text||' partes con enlaces activos duplicados' from (select work_order_id from public.invoice_work_orders where deleted_at is null and work_order_id is not null group by work_order_id having count(*)>1) d
  union all select 'GENERAL','invoice_tenant_mismatch',case when count(*)=0 then 'OK' else 'BLOCKER' end,count(*)::bigint,count(*)::text||' enlaces con tenant incompatible' from public.invoice_work_orders l join public.invoices i on i.id=l.invoice_id join public.work_orders w on w.id=l.work_order_id where l.company_id is distinct from i.company_id or l.company_id is distinct from w.company_id
  union all select 'GENERAL','draft_has_payments',case when count(*)=0 then 'OK' else 'BLOCKER' end,count(*)::bigint,count(*)::text||' cobros enlazados a borradores' from public.invoice_payments p join public.invoices i on i.id=p.invoice_id where i.status='borrador'
  union all select 'GENERAL','drafts_with_fiscal_code',case when count(*)=0 then 'OK' else 'BLOCKER' end,count(*)::bigint,count(*)::text||' borradores con numero fiscal' from public.invoices where status='borrador' and code is not null
  union all select 'GENERAL','drafts_marked_work_order_invoiced',case when count(*)=0 then 'OK' else 'BLOCKER' end,count(*)::bigint,count(*)::text||' partes facturados asociados a borradores' from public.invoice_work_orders l join public.invoices i on i.id=l.invoice_id join public.work_orders w on w.id=l.work_order_id where i.status='borrador' and w.economic_status='facturado'
  union all select 'ECONOMICS','invalid_totals',case when count(*)=0 then 'OK' else 'BLOCKER' end,count(*)::bigint,count(*)::text||' registros con importes negativos' from (select id from public.invoices where subtotal<0 or tax_amount<0 or total_amount<0 union all select id from public.invoice_work_orders where subtotal<0 or tax_amount<0 or total_amount<0) invalid
  union all select 'ECONOMICS','ambiguous_candidates',case when count(*)=0 then 'OK' else 'REVIEW' end,count(*)::bigint,count(*)::text||' candidatos sin sale_amount; deben revisarse antes de emitir' from public.work_orders where deleted_at is null and office_validation_status='validated' and economic_status='pendiente_facturar' and coalesce(warranty,false)=false and coalesce(billable,true)=true and coalesce(sale_amount,0)=0 and not exists(select 1 from public.invoice_work_orders l where l.work_order_id=work_orders.id and l.deleted_at is null)
  union all select 'AUDIT','draft_audit_operations',case when count(*) filter(where operation in('INVOICE_DRAFT_CREATE','INVOICE_DRAFT_UPDATE'))=0 then 'OK' else 'INFO' end,count(*) filter(where operation in('INVOICE_DRAFT_CREATE','INVOICE_DRAFT_UPDATE'))::bigint,'Operaciones de borrador registradas; no se altera el historial anterior' from public.audit_log
  union all select 'SECURITY','authenticated_invoice_grant',case when exists(select 1 from information_schema.role_table_grants where table_schema='public' and table_name='invoices' and grantee='authenticated' and privilege_type='SELECT') then 'OK' else 'BLOCKER' end,1,'Acceso de lectura autenticado presente'
  union all select 'SECURITY','invoice_rls_enabled',case when count(*)=3 then 'OK' else 'BLOCKER' end,count(*)::bigint,count(*)::text||' de 3 tablas con RLS activo' from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname in ('invoices','invoice_work_orders','invoice_payments') and c.relrowsecurity
)
,summary as (
  select 'SUMMARY'::text as check_group,'postcheck_078'::text as check_name,case when count(*) filter(where status='BLOCKER')>0 then 'BLOCKER' when count(*) filter(where status='REVIEW')>0 then 'REVIEW' else 'OK' end as status,count(*) filter(where status<>'OK')::bigint as affected_rows,case when count(*) filter(where status='BLOCKER')>0 then 'Se han detectado BLOCKER.' when count(*) filter(where status='REVIEW')>0 then 'No hay BLOCKER, pero existen REVIEW.' else '078 validada sin BLOCKER ni REVIEW.' end as details from checks
)
select check_group,check_name,status,affected_rows,details from (select * from checks union all select * from summary) result order by case check_group when 'SUMMARY' then 2 else 1 end,case status when 'BLOCKER' then 1 when 'REVIEW' then 2 when 'INFO' then 3 else 4 end,check_name;
