with review_rpc as (
  select p.oid,p.pronargs,p.pronargdefaults,p.proargdefaults,pg_get_function_arguments(p.oid) arguments,pg_get_functiondef(p.oid) definition,p.prosecdef,p.proconfig
  from pg_proc p join pg_namespace n on n.oid=p.pronamespace
  where n.nspname='public' and p.proname='dmp_review_work_order_economic' and p.pronargs=4
), checks(check_name,passed,detail) as (
  select 'review_overload',exists(select 1 from review_rpc where pronargdefaults=0 and proargdefaults is null),'four-argument overload has no defaults'
  union all select 'review_wrapper',to_regprocedure('public.dmp_review_work_order_economic(uuid,jsonb,text)') is not null and exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='dmp_review_work_order_economic' and p.pronargs=3 and p.pronargdefaults=0),'three-argument wrapper remains present'
  union all select 'qualified_variables',exists(select 1 from review_rpc where position('v_actor' in definition)>0 and position('v_work' in definition)>0 and position('v_decision' in definition)>0 and position('v_kind' in definition)>0 and position('v_entry_id' in definition)>0 and position('v_sell' in definition)>0 and position('v_price' in definition)>0 and position('v_source' in definition)>0 and position('v_economics' in definition)>0 and position('v_old_work' in definition)>0 and position('v_old_lines' in definition)>0 and position('v_new_lines' in definition)>0 and position('v_expected_count' in definition)>0 and position('v_actual_count' in definition)>0 and position('v_reason' in definition)>0),'all PL/pgSQL variables use explicit v_ names'
  union all select 'qualified_aliases',exists(select 1 from review_rpc where position('decision_element.value' in lower(definition))>0 and position('decision_rows.kind' in lower(definition))>0 and position('decision_rows.entry_id' in lower(definition))>0 and position('economic_entries.entry_kind' in lower(definition))>0 and position('economic_entries.entry_id' in lower(definition))>0 and position('economic_entries.row_data' in lower(definition))>0),'all SQL aliases are explicit and qualified'
  union all select 'no_one_letter_collisions',not exists(select 1 from review_rpc where position('jsonb_array_elements(p_decisions) d' in lower(definition))>0 or position('for d in' in lower(definition))>0 or position('declare a ' in lower(definition))>0 or position(' w public.work_orders' in lower(definition))>0 or position('order by kind,entry_id' in lower(definition))>0),'known one-letter collisions are absent'
  union all select 'contract_intact',exists(select 1 from review_rpc where prosecdef and position('search_path=public' in lower(coalesce(array_to_string(proconfig,','),'')))>0 and position('ECONOMIC_REVIEW_APPROVE' in definition)>0 and position('line_before' in definition)>0 and position('line_after' in definition)>0 and position('zero_sale_confirmed' in definition)>0 and position('contributes_to_sale' in definition)>0 and position('status<>''cancelada''' in lower(definition))>0),'100/101 economic and security contract remains intact'
  union all select 'grants',has_function_privilege('authenticated','public.dmp_review_work_order_economic(uuid,jsonb,text)','execute') and has_function_privilege('authenticated','public.dmp_review_work_order_economic(uuid,jsonb,text,boolean)','execute') and not has_function_privilege('anon','public.dmp_review_work_order_economic(uuid,jsonb,text,boolean)','execute'),'review grants are preserved'
  union all select 'no_new_tables',not exists(select 1 from pg_class where relnamespace='public'::regnamespace and relname in ('economic_reviews','invoice_lines')),'102 requires no new tables'
)
select check_name,passed,detail from checks order by check_name;
