-- READ ONLY postflight for 090. Returns one result set and does not modify data.
with checks as (
  select 'queue_signature' check_name, case when to_regprocedure('public.dmp_department_routing_queue(text)') is not null then 'OK' else 'BLOCKER' end status, 'Firma dmp_department_routing_queue(text) presente' detail
  union all select 'queue_grants', case when has_function_privilege('authenticated','public.dmp_department_routing_queue(text)','EXECUTE') and not has_function_privilege('anon','public.dmp_department_routing_queue(text)','EXECUTE') then 'OK' else 'BLOCKER' end, 'Grants preservados'
  union all select 'invalid_equipment_reference_removed', case when position('e.name' in lower(coalesce((select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='dmp_department_routing_queue' limit 1),'')))=0 then 'OK' else 'BLOCKER' end, 'La función publicada no contiene e.name'
  union all select 'equipment_code_reference', case when position('e.code' in lower(coalesce((select pg_get_functiondef(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='dmp_department_routing_queue' limit 1),'')))>0 then 'OK' else 'BLOCKER' end, 'La cola usa equipment.code'
  union all select 'queue_dependencies', case when to_regclass('public.work_orders') is not null and to_regclass('public.work_order_equipment') is not null and to_regclass('public.equipment') is not null and to_regclass('public.invoice_work_orders') is not null then 'OK' else 'BLOCKER' end, 'Dependencias operativas y Billing presentes'
  union all select 'routing_coherence', case when count(*)=0 then 'OK' else 'BLOCKER' end, count(*)::text||' partes con routing incoherente' from public.work_orders where deleted_at is null and ((sat_review_status='approved' and sat_review_destination is null) or (sat_review_destination='comercial' and commercial_review_status='pending' and current_responsible_id is null) or (sat_review_destination='facturacion' and commercial_review_status<>'not_started'))
  union all select 'commercial_assignment_coherence', case when count(*)=0 then 'OK' else 'BLOCKER' end, count(*)::text||' asignaciones Comerciales incoherentes' from public.work_orders wo where wo.deleted_at is null and wo.commercial_review_status='pending' and (wo.sat_review_destination<>'comercial' or not exists (select 1 from public.profiles p where p.id=wo.current_responsible_id and p.company_id=wo.company_id and p.active=true and p.deleted_at is null and (p.primary_area='Comercial' or exists (select 1 from public.profile_roles pr join public.roles r on r.id=pr.role_id where pr.profile_id=p.id and r.name='Comercial'))))
  union all select 'billing_objects_intact', case when to_regclass('public.invoices') is not null and to_regclass('public.invoice_work_orders') is not null then 'OK' else 'BLOCKER' end, 'Facturacion intacta'
)
select check_name,status,detail from checks order by check_name;
