with rpc as (
  select p.oid,p.proname,pg_get_function_identity_arguments(p.oid) signature,pg_get_functiondef(p.oid) definition,p.prosecdef,p.proconfig
  from pg_proc p join pg_namespace n on n.oid=p.pronamespace
  where n.nspname='public' and p.proname in ('dmp_calculate_work_order_economics','dmp_guided_billing_eligible','dmp_prepare_invoice_from_work_order','dmp_review_work_order_economic','dmp_reopen_work_order_economic','dmp_finalize_work_order_technical','dmp_update_invoice_draft','dmp_issue_invoice')
), checks as (
  select 'reopen_rpc' check_name, exists(select 1 from rpc where proname='dmp_reopen_work_order_economic' and signature='p_work_order_id uuid, p_reason text') passed, 'reopen RPC installed' detail
  union all select 'review_wrapper', to_regprocedure('public.dmp_review_work_order_economic(uuid,jsonb,text)') is not null and to_regprocedure('public.dmp_review_work_order_economic(uuid,jsonb,text,boolean)') is not null, 'three and four argument review contracts exist' detail
  union all select 'review_overload_no_default', exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='dmp_review_work_order_economic' and p.pronargs=4 and p.pronargdefaults=0 and p.proargdefaults is null and position('p_zero_sale_confirmed boolean' in pg_get_function_arguments(p.oid))>0 and position('default' in lower(pg_get_function_arguments(p.oid)))=0) and exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='dmp_review_work_order_economic' and p.pronargs=3 and p.pronargdefaults=0), 'four-argument review has no default and three-argument wrapper exists' detail
  union all select 'review_roles', exists(select 1 from rpc where proname='dmp_review_work_order_economic' and position('superadmin' in definition)>0 and position('SAT' in definition)>0 and position('Gerencia' in definition)>0 and position('Oficina' in definition)=0), 'Office remains excluded from economic review' detail
  union all select 'reopen_roles', exists(select 1 from rpc where proname='dmp_reopen_work_order_economic' and position('superadmin' in definition)>0 and position('SAT' in definition)>0 and position('Gerencia' in definition)>0 and position('Comercial' in definition)>0 and position('Oficina' in definition)=0), 'reopen roles are restricted' detail
  union all select 'returned_state', exists(select 1 from information_schema.check_constraints where constraint_name='work_orders_economic_review_status_check' and check_clause like '%returned%'), 'returned reuses the existing review state' detail
  union all select 'invoice_freeze', exists(select 1 from rpc where proname='dmp_reopen_work_order_economic' and position('i.status in (''borrador'',''emitida'',''parcialmente_cobrada'',''cobrada'')' in lower(definition))>0 and position('cancelada' in lower(definition))=0), 'active invoices freeze while cancelled invoices release' detail
  union all select 'zero_sale_confirmation', exists(select 1 from rpc where proname='dmp_review_work_order_economic' and position('p_zero_sale_confirmed' in definition)>0 and position('confirma expresamente una venta cero' in definition)>0), 'zero sale requires explicit confirmation when applicable' detail
  union all select 'explicit_decision', exists(select 1 from rpc where proname='dmp_review_work_order_economic' and position('facturabilidad explicita requerida' in definition)>0 and position('jsonb_typeof(d->''contributes_to_sale'')' in definition)>0), 'each decision must carry an explicit boolean' detail
  union all select 'partial_warranty', exists(select 1 from rpc where proname='dmp_calculate_work_order_economics' and position('warranty_sale' in definition)>0 and position('warranty' in lower(definition))>0) and exists(select 1 from rpc where proname='dmp_guided_billing_eligible' and position('sale_amount' in lower(definition))>0), 'warranty can have positive explicit sale' detail
  union all select 'returned_not_eligible', exists(select 1 from rpc where proname='dmp_guided_billing_eligible' and position('economic_review_status=''approved''' in definition)>0 and position('economic_review_status=''not_started''' in definition)>0 and position('economic_review_status=''returned''' in definition)=0), 'pending/returned reviews cannot enter guided billing; only approved or bounded legacy applies' detail
  union all select 'legacy_eligibility', exists(select 1 from rpc where proname='dmp_guided_billing_eligible' and position('economic_review_status=''not_started'' and w.economic_status=''pendiente_facturar'' and w.office_validation_status=''validated''' in definition)>0), 'real pre-099 legacy route remains bounded and compatible' detail
  union all select 'no_warranty_force', not exists(select 1 from rpc where proname='dmp_finalize_work_order_technical' and position('if v_warranty then v_billable' in lower(definition))>0), 'technical finalization does not force warranty to non-billable' detail
  union all select 'manual_multiline', exists(select 1 from rpc where proname='dmp_update_invoice_draft' and position('work_order_id' in lower(definition))>0) and exists(select 1 from rpc where proname='dmp_issue_invoice' and position('work_order_id' in definition)>0), 'manual and multi-part lines remain represented' detail
  union all select 'cancelled_rebill_prepare', exists(select 1 from rpc where proname='dmp_prepare_invoice_from_work_order' and position('i.status <> ''cancelada''' in lower(definition))>0 and position('count(distinct i.id)' in lower(definition))>0), 'cancelled invoices do not block a new preparation' detail
  union all select 'active_rebill_freeze', exists(select 1 from rpc where proname='dmp_reopen_work_order_economic' and position('borrador' in definition)>0 and position('emitida' in definition)>0 and position('parcialmente_cobrada' in definition)>0 and position('cobrada' in definition)>0), 'active invoices still block reopening' detail
  union all select 'invoice_modes', exists(select 1 from rpc where proname='dmp_update_invoice_draft' and position('v_work_count' in definition)>0 and position('v_manual_line_count' in definition)>0 and position('v_strict_single' in definition)>0) and exists(select 1 from rpc where proname='dmp_issue_invoice' and position('manual_line_count' in definition)>0 and position('strict_single' in definition)>0), 'strict, hybrid, manual and multi modes are classified at runtime' detail
  union all select 'non_strict_expected_null', exists(select 1 from rpc where proname='dmp_update_invoice_draft' and position('economic_expected_amount=expected' in definition)>0 and position('expected:=null' in definition)>0) and exists(select 1 from rpc where proname='dmp_issue_invoice' and position('case when strict_single then sale else null end' in definition)>0), 'non-strict invoices do not retain a synthetic expected amount' detail
  union all select 'hybrid_no_override', exists(select 1 from rpc where proname='dmp_issue_invoice' and position('if strict_single and' in definition)>0), 'hybrid invoices do not compare manual lines against work-order sale' detail
  union all select 'guided_rpc_private', not has_function_privilege('authenticated','public.dmp_guided_billing_eligible(uuid)','execute'), 'no direct authenticated consumer was found; helper remains internal to billing RPCs' detail
  union all select 'office_finalize_rejected', exists(select 1 from rpc where proname='dmp_finalize_work_order_technical' and position('array[''superadmin'',''SAT'',''Gerencia'']' in definition)>0 and position('array[''superadmin'',''SAT'',''Gerencia'',''Oficina'']' in definition)=0), 'Office cannot execute technical finalization' detail
  union all select 'invoiced_aggregate', exists(select 1 from rpc where proname='dmp_issue_invoice' and position('group by work_order_id' in lower(definition))>0), 'invoiced amount aggregates per work order' detail
  union all select 'fiscal_line_trace', exists(select 1 from rpc where proname='dmp_issue_invoice' and position('jsonb_build_object(''work_order_id''' in definition)>0 and position('''works''' in definition)>0), 'fiscal snapshot retains line and works traceability' detail
  union all select 'audit_reopen', exists(select 1 from rpc where proname='dmp_reopen_work_order_economic' and position('ECONOMIC_REVIEW_REOPEN' in definition)>0), 'reopen is separately audited' detail
  union all select 'audit_approve_lines', exists(select 1 from rpc where proname='dmp_review_work_order_economic' and position('line_before' in definition)>0 and position('line_after' in definition)>0 and position('zero_sale_confirmed' in definition)>0), 'approval retains line audit and zero-sale flag' detail
  union all select '099_security', exists(select 1 from rpc where proname='dmp_calculate_work_order_economics' and prosecdef and position('assert_member_of_current_company' in definition)>0 and position('search_path' in coalesce(array_to_string(proconfig,','),''))>0) and not has_function_privilege('authenticated','public.dmp_calculate_work_order_economics(uuid)','execute'), '099 calculator security remains intact' detail
  union all select 'legacy_rpcs', to_regprocedure('public.dmp_delete_invoice_draft(uuid)') is not null and to_regprocedure('public.dmp_issue_invoice(uuid)') is not null, '092/093 deletion and legacy issue wrapper remain' detail
  union all select 'invoice_snapshots_untouched', (select count(*) from public.invoices where status<>'borrador' and fiscal_snapshot is not null)>=0, 'historical fiscal snapshots remain present' detail
  union all select 'no_new_tables', not exists(select 1 from pg_class where relnamespace='public'::regnamespace and relname in ('economic_reviews','invoice_lines')), 'no tables introduced' detail
)
select check_name, passed, detail from checks order by check_name;
