-- Read-only preflight for 078. Do not run together with the migration.

with checks(check_group,check_name,status,affected_rows,details) as (
  select 'DEPENDENCIES','invoice_tables',case when count(*)=3 then 'OK' else 'BLOCKER' end,count(*)::bigint,count(*)::text||' de 3 tablas 074' from information_schema.tables where table_schema='public' and table_name in ('invoices','invoice_work_orders','invoice_payments')
  union all select 'DEPENDENCIES','invoice_prepare_rpc',case when to_regprocedure('public.dmp_prepare_invoice_from_work_order(uuid,date,text,numeric)') is not null then 'OK' else 'BLOCKER' end,case when to_regprocedure('public.dmp_prepare_invoice_from_work_order(uuid,date,text,numeric)') is not null then 1 else 0 end,coalesce(to_regprocedure('public.dmp_prepare_invoice_from_work_order(uuid,date,text,numeric)')::text,'Falta RPC preparar')
  union all select 'DEPENDENCIES','invoice_update_rpc',case when to_regprocedure('public.dmp_update_invoice_draft(uuid,jsonb,date,text,numeric)') is not null then 'OK' else 'BLOCKER' end,case when to_regprocedure('public.dmp_update_invoice_draft(uuid,jsonb,date,text,numeric)') is not null then 1 else 0 end,coalesce(to_regprocedure('public.dmp_update_invoice_draft(uuid,jsonb,date,text,numeric)')::text,'Falta RPC actualizar')
  union all select 'DEPENDENCIES','invoice_issue_rpc',case when to_regprocedure('public.dmp_issue_invoice(uuid)') is not null then 'OK' else 'BLOCKER' end,case when to_regprocedure('public.dmp_issue_invoice(uuid)') is not null then 1 else 0 end,coalesce(to_regprocedure('public.dmp_issue_invoice(uuid)')::text,'Falta RPC emitir')
  union all select 'DEPENDENCIES','office_review_rpc',case when to_regprocedure('public.dmp_review_work_order_office(uuid,text,text)') is not null then 'OK' else 'BLOCKER' end,case when to_regprocedure('public.dmp_review_work_order_office(uuid,text,text)') is not null then 1 else 0 end,'Dependencia 073/077; 077 debe estar aplicada antes de preparar'
  union all select 'DEPENDENCIES','billing_issue_rpc_074',case when to_regprocedure('public.dmp_create_invoice_from_work_order(uuid,numeric,date,text)') is not null then 'OK' else 'BLOCKER' end,case when to_regprocedure('public.dmp_create_invoice_from_work_order(uuid,numeric,date,text)') is not null then 1 else 0 end,'RPC 074 existente; 078 la sustituye por preparar/emitir'
  union all select 'SECURITY','legacy_direct_issue_grant',case when exists(select 1 from information_schema.routine_privileges where specific_schema='public' and routine_name='dmp_create_invoice_from_work_order' and grantee='authenticated' and privilege_type='EXECUTE') then 'REVIEW' else 'OK' end,case when exists(select 1 from information_schema.routine_privileges where specific_schema='public' and routine_name='dmp_create_invoice_from_work_order' and grantee='authenticated' and privilege_type='EXECUTE') then 1 else 0 end,'078 debe revocar la emision directa 074'
  union all select 'DEPENDENCIES','draft_invoice_columns',case when count(*)=3 then 'OK' else 'BLOCKER' end,count(*)::bigint,count(*)::text||' de 3 columnas de linea 078' from information_schema.columns where table_schema='public' and table_name='invoice_work_orders' and column_name in ('quantity','unit_price','discount')
  union all select 'DEPENDENCIES','audit_draft_operations',case when pg_get_constraintdef(c.oid) ilike '%INVOICE_DRAFT_CREATE%' and pg_get_constraintdef(c.oid) ilike '%INVOICE_DRAFT_UPDATE%' then 'OK' else 'BLOCKER' end,case when pg_get_constraintdef(c.oid) ilike '%INVOICE_DRAFT_CREATE%' and pg_get_constraintdef(c.oid) ilike '%INVOICE_DRAFT_UPDATE%' then 1 else 0 end,'Audit compatible con operaciones de borrador' from pg_constraint c join pg_class r on r.oid=c.conrelid join pg_namespace n on n.oid=r.relnamespace where n.nspname='public' and r.relname='audit_log' and c.conname='audit_log_operation_check'
  union all select 'STRUCTURE','draft_status_constraint',case when pg_get_constraintdef(c.oid) ilike '%borrador%' then 'OK' else 'BLOCKER' end,case when pg_get_constraintdef(c.oid) ilike '%borrador%' then 1 else 0 end,'Invoices debe admitir borrador sin eliminar estados 074' from pg_constraint c join pg_class r on r.oid=c.conrelid join pg_namespace n on n.oid=r.relnamespace where n.nspname='public' and r.relname='invoices' and c.conname='invoices_status_check'
  union all select 'STRUCTURE','fiscal_code_nullable',case when is_nullable='YES' then 'OK' else 'BLOCKER' end,case when is_nullable='YES' then 1 else 0 end,'El borrador no consume numero fiscal' from information_schema.columns where table_schema='public' and table_name='invoices' and column_name='code'
  union all select 'STRUCTURE','invoice_statuses',case when count(*)>=0 then 'OK' else 'BLOCKER' end,count(*)::bigint,string_agg(status,', ' order by status) from (select status from public.invoices group by status) s
  union all select 'IMPACT','validated_pending_candidates',case when count(*)=0 then 'OK' else 'INFO' end,count(*)::bigint,count(*)::text||' partes preparados posibles' from public.work_orders where deleted_at is null and office_validation_status='validated' and economic_status='pendiente_facturar' and coalesce(warranty,false)=false and coalesce(billable,true)=true and not exists(select 1 from public.invoice_work_orders l where l.work_order_id=work_orders.id and l.deleted_at is null)
  union all select 'IMPACT','candidate_sale_positive',case when count(*)=0 then 'OK' else 'INFO' end,count(*)::bigint,count(*)::text||' candidatos con sale_amount>0' from public.work_orders where deleted_at is null and office_validation_status='validated' and economic_status='pendiente_facturar' and coalesce(warranty,false)=false and coalesce(billable,true)=true and sale_amount>0 and not exists(select 1 from public.invoice_work_orders l where l.work_order_id=work_orders.id and l.deleted_at is null)
  union all select 'IMPACT','candidate_sale_zero',case when count(*)=0 then 'OK' else 'REVIEW' end,count(*)::bigint,count(*)::text||' candidatos con sale_amount=0; se permite preparar pero no emitir sin lineas validas' from public.work_orders where deleted_at is null and office_validation_status='validated' and economic_status='pendiente_facturar' and coalesce(warranty,false)=false and coalesce(billable,true)=true and coalesce(sale_amount,0)=0 and not exists(select 1 from public.invoice_work_orders l where l.work_order_id=work_orders.id and l.deleted_at is null)
  union all select 'IMPACT','candidate_estimated_only',case when count(*)=0 then 'REVIEW' else 'REVIEW' end,count(*)::bigint,count(*)::text||' candidatos estimated-only; no se copia la estimacion' from public.work_orders where deleted_at is null and office_validation_status='validated' and economic_status='pendiente_facturar' and coalesce(warranty,false)=false and coalesce(billable,true)=true and coalesce(sale_amount,0)=0 and coalesce(estimated_sale_amount,0)>0 and not exists(select 1 from public.invoice_work_orders l where l.work_order_id=work_orders.id and l.deleted_at is null)
  union all select 'IMPACT','candidate_without_amount',case when count(*)=0 then 'REVIEW' else 'REVIEW' end,count(*)::bigint,count(*)::text||' candidatos sin importe; requieren lineas manuales antes de emitir' from public.work_orders where deleted_at is null and office_validation_status='validated' and economic_status='pendiente_facturar' and coalesce(warranty,false)=false and coalesce(billable,true)=true and coalesce(sale_amount,0)=0 and coalesce(estimated_sale_amount,0)=0 and not exists(select 1 from public.invoice_work_orders l where l.work_order_id=work_orders.id and l.deleted_at is null)
  union all select 'IMPACT','existing_invoices',case when count(*)=0 then 'OK' else 'INFO' end,count(*)::bigint,count(*)::text||' facturas existentes' from public.invoices
  union all select 'IMPACT','existing_payments',case when count(*)=0 then 'OK' else 'INFO' end,count(*)::bigint,count(*)::text||' cobros existentes; 078 no los modifica' from public.invoice_payments
  union all select 'DATA','invoice_duplicates',case when count(*)=0 then 'OK' else 'BLOCKER' end,count(*)::bigint,count(*)::text||' partes con enlaces activos duplicados' from (select work_order_id from public.invoice_work_orders where deleted_at is null and work_order_id is not null group by work_order_id having count(*)>1) d
  union all select 'DATA','invoice_tenant_mismatch',case when count(*)=0 then 'OK' else 'BLOCKER' end,count(*)::bigint,count(*)::text||' enlaces con tenant incompatible' from public.invoice_work_orders l join public.invoices i on i.id=l.invoice_id join public.work_orders w on w.id=l.work_order_id where l.company_id is distinct from i.company_id or l.company_id is distinct from w.company_id
  union all select 'DATA','orphan_invoice_links',case when count(*)=0 then 'OK' else 'BLOCKER' end,count(*)::bigint,count(*)::text||' enlaces sin factura o parte' from public.invoice_work_orders l left join public.invoices i on i.id=l.invoice_id left join public.work_orders w on w.id=l.work_order_id where l.deleted_at is null and (i.id is null or (l.work_order_id is not null and w.id is null))
  union all select 'DATA','invalid_totals',case when count(*)=0 then 'OK' else 'BLOCKER' end,count(*)::bigint,count(*)::text||' facturas/lineas con importes invalidos' from (select id from public.invoices where subtotal<0 or tax_amount<0 or total_amount<0 union all select id from public.invoice_work_orders where subtotal<0 or tax_amount<0 or total_amount<0) invalid
  union all select 'SECURITY','invoice_grants',case when exists(select 1 from information_schema.role_table_grants where table_schema='public' and table_name='invoices' and grantee='authenticated' and privilege_type='SELECT') then 'OK' else 'BLOCKER' end,case when exists(select 1 from information_schema.role_table_grants where table_schema='public' and table_name='invoices' and grantee='authenticated' and privilege_type='SELECT') then 1 else 0 end,'Lectura autenticada; escrituras deben ser RPC'
)
select check_group,check_name,status,affected_rows,details from checks order by case status when 'BLOCKER' then 1 when 'REVIEW' then 2 when 'INFO' then 3 else 4 end,check_group,check_name;
