-- 092 preflight. Read-only; execute only against an explicitly selected environment.
with checks as (
  select 'STRUCTURE'::text as area, 'invoices_exists'::text as check_name,
    case when to_regclass('public.invoices') is not null then 'OK' else 'BLOCKER' end as status,
    case when to_regclass('public.invoices') is not null then 1 else 0 end::bigint as finding_count,
    'public.invoices'::text as detail
  union all select 'STRUCTURE','invoice_work_orders_exists',case when to_regclass('public.invoice_work_orders') is not null then 'OK' else 'BLOCKER' end,case when to_regclass('public.invoice_work_orders') is not null then 1 else 0 end,'Las lineas canonicas del modelo viven en invoice_work_orders'
  union all select 'STRUCTURE','invoice_lines_model',case when to_regclass('public.invoice_lines') is null then 'OK' else 'REVIEW' end,case when to_regclass('public.invoice_lines') is null then 0 else 1 end,case when to_regclass('public.invoice_lines') is null then 'No existe invoice_lines; 092 usa invoice_work_orders' else 'Existe invoice_lines; auditar dependencia adicional antes de aplicar 092' end
  union all select 'STRUCTURE','invoice_payments_exists',case when to_regclass('public.invoice_payments') is not null then 'OK' else 'BLOCKER' end,case when to_regclass('public.invoice_payments') is not null then 1 else 0 end,'public.invoice_payments'
  union all select 'STRUCTURE','work_orders_exists',case when to_regclass('public.work_orders') is not null then 'OK' else 'BLOCKER' end,case when to_regclass('public.work_orders') is not null then 1 else 0 end,'public.work_orders'
  union all select 'STRUCTURE','fiscal_snapshot_column',case when exists(select 1 from information_schema.columns where table_schema='public' and table_name='invoices' and column_name='fiscal_snapshot') then 'OK' else 'BLOCKER' end,count(*)::bigint,'fiscal_snapshot disponible'
  union all select 'STRUCTURE','draft_status_constraint',case when exists(select 1 from pg_constraint c join pg_class r on r.oid=c.conrelid join pg_namespace n on n.oid=r.relnamespace where n.nspname='public' and r.relname='invoices' and c.conname='invoices_status_check' and pg_get_constraintdef(c.oid) ilike '%borrador%') then 'OK' else 'BLOCKER' end,count(*)::bigint,'Estado borrador canonico'
  union all select 'RELATION','invoice_fks',case when count(*) filter(where confrelid='public.invoices'::regclass)=2 then 'OK' else 'REVIEW' end,count(*)::bigint,coalesce(string_agg(format('%s.%s on_delete=%s',conrelid::regclass,conname,confdeltype),', ' order by conname),'Sin FK a invoices') from pg_constraint where contype='f' and confrelid='public.invoices'::regclass
  union all select 'RELATION','unexpected_invoice_references',case when count(*)=2 then 'OK' else 'BLOCKER' end,count(*)::bigint,coalesce(string_agg(conrelid::regclass::text||'.'||conname,', ' order by conname),'Ninguna') from pg_constraint where contype='f' and confrelid='public.invoices'::regclass
  union all select 'RPC','required_rpc_078_079_081_091',case when count(*) >= 4 then 'OK' else 'BLOCKER' end,count(*)::bigint,coalesce(string_agg(proname||'('||pg_get_function_identity_arguments(oid)||')',', ' order by proname),'Faltan RPC de facturacion') from pg_proc where pronamespace='public'::regnamespace and proname in ('dmp_prepare_invoice_from_work_order','dmp_update_invoice_draft','dmp_issue_invoice','dmp_guided_billing_eligible')
  -- Absence is the expected pre-apply state. Presence is diagnostic, never OK.
  union all select 'RPC','rpc_092_absent_before_apply',case when count(*)=0 then 'OK' else 'REVIEW' end,count(*)::bigint,case when count(*)=0 then 'No existe la RPC 092; lista para aplicar' else 'La RPC 092 ya existe; revisar si se trata de una ejecucion previa' end from pg_proc where pronamespace='public'::regnamespace and proname='dmp_delete_invoice_draft'
  union all select 'DATA','drafts_with_any_payment',case when count(*)=0 then 'OK' else 'BLOCKER' end,count(*)::bigint,count(*)::text||' borradores con cualquier movimiento de cobro' from public.invoices i join public.invoice_payments p on p.invoice_id=i.id where i.status='borrador'
  union all select 'DATA','drafts_with_snapshot',case when count(*)=0 then 'OK' else 'BLOCKER' end,count(*)::bigint,count(*)::text||' borradores con fiscal_snapshot' from public.invoices where status='borrador' and fiscal_snapshot is not null
  union all select 'DATA','drafts_with_number',case when count(*)=0 then 'OK' else 'BLOCKER' end,count(*)::bigint,count(*)::text||' borradores con numero fiscal' from public.invoices where status='borrador' and code is not null
  union all select 'DATA','drafts_with_active_links',case when count(*)=0 then 'OK' else 'REVIEW' end,count(*)::bigint,count(*)::text||' borradores con enlaces activos; 092 los elimina con sus lineas' from public.invoices i join public.invoice_work_orders l on l.invoice_id=i.id and l.deleted_at is null where i.status='borrador'
  union all select 'SECURITY','audit_delete_operation_allowed',case when exists(select 1 from pg_constraint c join pg_class r on r.oid=c.conrelid join pg_namespace n on n.oid=r.relnamespace where n.nspname='public' and r.relname='audit_log' and c.conname='audit_log_operation_check' and pg_get_constraintdef(c.oid) ilike '%DELETE%') then 'OK' else 'BLOCKER' end,1,'092 usa la operacion de auditoria DELETE existente'
  union all select 'SECURITY','direct_delete_denied',case when count(*)=3 then 'OK' else 'BLOCKER' end,count(*)::bigint,'RLS debe denegar DELETE directo en invoices, invoice_work_orders e invoice_payments' from pg_policies where schemaname='public' and policyname in ('invoices_direct_delete_denied','invoice_work_orders_direct_delete_denied','invoice_payments_direct_delete_denied')
)
select area, check_name, status, finding_count, detail from checks order by area, check_name;
