-- READ ONLY preflight for 090. Returns one result set and does not execute business RPCs.
with target as (
  select pg_get_functiondef(p.oid) as definition
  from pg_proc p
  join pg_namespace n on n.oid=p.pronamespace
  where n.nspname='public' and p.proname='dmp_department_routing_queue'
    and pg_get_function_identity_arguments(p.oid)='p_queue text'
  limit 1
), normalized as (
  select regexp_replace(lower(coalesce(definition,'')), '[[:space:]]+', ' ', 'g') as definition from target
), checks as (
  select 'queue_signature' check_name,
    case when to_regprocedure('public.dmp_department_routing_queue(text)') is not null then 'OK' else 'BLOCKER' end status,
    coalesce((select pg_get_function_identity_arguments(p.oid) from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='dmp_department_routing_queue' limit 1),'No existe') detail
  union all select 'queue_grants', case when has_function_privilege('authenticated','public.dmp_department_routing_queue(text)','EXECUTE') and not has_function_privilege('anon','public.dmp_department_routing_queue(text)','EXECUTE') then 'OK' else 'BLOCKER' end, 'authenticated ejecuta; anon no ejecuta'
  union all select 'legacy_invalid_reference', case when position('e.name' in (select definition from normalized))=0 then 'OK' else 'BLOCKER' end, case when position('e.name' in (select definition from normalized))=0 then 'La definición remota no contiene e.name' else 'La definición remota todavía contiene e.name' end
  union all select 'equipment_columns', case when (select count(*) from information_schema.columns where table_schema='public' and table_name='equipment' and column_name in ('id','code','equipment_type_id'))=3 then 'OK' else 'BLOCKER' end, 'equipment.id, code y equipment_type_id presentes'
  union all select 'queue_return_columns', case when (select count(*) from information_schema.columns where table_schema='public' and table_name='work_orders' and column_name in ('id','company_id','code','title','client_id','site_id','quote_id','description','sat_reviewed_at','sat_reviewed_by','sat_review_flags','sat_review_reason','current_responsible_id','commercial_review_status','commercial_review_reason','commercial_reviewed_at','sat_review_status','sat_review_destination'))=18 and exists (select 1 from information_schema.columns where table_schema='public' and table_name='clients' and column_name='legal_name') and exists (select 1 from information_schema.columns where table_schema='public' and table_name='sites' and column_name='name') and exists (select 1 from information_schema.columns where table_schema='public' and table_name='quotes' and column_name='code') and (select count(*) from information_schema.columns where table_schema='public' and table_name='profiles' and column_name in ('first_name','last_name'))=2 then 'OK' else 'BLOCKER' end, 'Columnas de retorno y aliases c, s, q, sp presentes'
  union all select 'queue_alias_structure', case when position('left join public.equipment e on e.id=we.equipment_id' in (select definition from normalized))>0 and position('string_agg(distinct e.code' in (select definition from normalized))>0 then 'OK' else 'BLOCKER' end, case when position('left join public.equipment e on e.id=we.equipment_id' in (select definition from normalized))>0 and position('string_agg(distinct e.code' in (select definition from normalized))>0 then 'Alias e usa equipment.code y mantiene el join esperado' else 'Falta equipment.code o el JOIN esperado del alias e' end
  union all select 'queue_join_dependencies', case when to_regclass('public.work_orders') is not null and to_regclass('public.work_order_equipment') is not null and to_regclass('public.clients') is not null and to_regclass('public.sites') is not null and to_regclass('public.equipment') is not null and to_regclass('public.quotes') is not null and to_regclass('public.profiles') is not null and to_regclass('public.invoice_work_orders') is not null then 'OK' else 'BLOCKER' end, 'Dependencias de la consulta presentes'
  union all select 'routing_088_089_dependencies', case when to_regprocedure('public.dmp_review_work_order_sat(uuid,text,text,uuid,jsonb,text)') is not null and to_regprocedure('public.dmp_review_work_order_commercial(uuid,text)') is not null then 'OK' else 'BLOCKER' end, 'RPCs SAT y Comercial compatibles presentes'
  union all select 'sat_pending_rows', 'REVIEW', count(*)::text||' partes pendientes SAT' from public.work_orders where deleted_at is null and sat_review_status='pending'
  union all select 'commercial_pending_rows', 'REVIEW', count(*)::text||' partes pendientes Comercial' from public.work_orders where deleted_at is null and commercial_review_status='pending'
  union all select 'commercial_pending_assignment', case when count(*)=0 then 'OK' else 'REVIEW' end, count(*)::text||' pendientes Comercial sin asignacion valida' from public.work_orders wo where wo.deleted_at is null and wo.commercial_review_status='pending' and (wo.sat_review_destination<>'comercial' or wo.current_responsible_id is null or not exists (select 1 from public.profiles p where p.id=wo.current_responsible_id and p.company_id=wo.company_id and p.active=true and p.deleted_at is null and (p.primary_area='Comercial' or exists (select 1 from public.profile_roles pr join public.roles r on r.id=pr.role_id where pr.profile_id=p.id and r.name='Comercial'))))
  union all select 'billing_objects_intact', case when to_regclass('public.invoices') is not null and to_regclass('public.invoice_work_orders') is not null then 'OK' else 'BLOCKER' end, 'Invoices y enlaces Billing presentes'
)
select check_name,status,detail from checks order by check_name;
