with checks(check_name,passed,detail) as (
  select 'runtime_104',to_regprocedure('public.resolve_check_technician_from_work_order()') is not null and not exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='resolve_check_technician_from_work_order' and position('min(a.technician_id)' in lower(pg_get_functiondef(p.oid)))>0),'104 runtime trigger is present without the UUID aggregate defect'
  union all select 'finalize_present',to_regprocedure('public.dmp_finalize_work_order_technical(uuid,jsonb)') is not null,'technical finalize RPC exists before 105'
  union all select 'problem_present',exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='dmp_finalize_work_order_technical' and position('update public.quotes' in lower(pg_get_functiondef(p.oid)))>0 and position('dmp_quote_transition_apply' in lower(pg_get_functiondef(p.oid)))>0),'pre-105 finalize still contains the quote link write after safe status transition'
  union all select 'quote_guard_present',exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='dmp_quote_terminal_header_guard' and position('presupuesto bloqueado' in lower(pg_get_functiondef(p.oid)))>0),'historical quote header guard remains installed'
  union all select 'security_baseline',exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='dmp_finalize_work_order_technical' and p.prosecdef and exists(select 1 from unnest(coalesce(p.proconfig,array[]::text[])) as config where lower(config)='search_path=public')),'finalize remains SECURITY DEFINER with public search_path'
  union all select 'grants_baseline',has_function_privilege('authenticated','public.dmp_finalize_work_order_technical(uuid,jsonb)','execute') and not has_function_privilege('anon','public.dmp_finalize_work_order_technical(uuid,jsonb)','execute'),'finalize grants remain restricted to authenticated'
  union all select '105_not_installed',not exists(select 1 from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='dmp_finalize_work_order_technical' and position('dmp_quote_transition_apply' in lower(pg_get_functiondef(p.oid)))>0 and position('insert into public.audit_log' in lower(pg_get_functiondef(p.oid)))>0 and position('update public.quotes' in lower(pg_get_functiondef(p.oid)))=0),'105 quote-write removal is not installed yet'
  union all select 'no_new_tables',true,'105 is function-only and creates no tables or columns'
)
select check_name,passed,detail from checks order by check_name;
