-- READ ONLY preflight for 089. Returns one result set.
with checks as (
  select 'current_responsible_id_structure' check_name,
    case when exists (select 1 from information_schema.columns where table_schema='public' and table_name='work_orders' and column_name='current_responsible_id' and data_type='uuid') then 'OK' else 'BLOCKER' end status,
    'work_orders.current_responsible_id uuid presente' detail
  union all select 'commercial_profiles', case when exists (select 1 from public.profiles p where p.active=true and p.deleted_at is null and (p.primary_area='Comercial' or exists (select 1 from public.profile_roles pr join public.roles r on r.id=pr.role_id where pr.profile_id=p.id and r.name='Comercial'))) then 'OK' else 'REVIEW' end, 'Perfiles Comerciales activos detectados'
  union all select 'commercial_responsibility_usage', case when exists (select 1 from public.work_orders wo join public.profiles p on p.id=wo.current_responsible_id where p.primary_area='Comercial' or exists (select 1 from public.profile_roles pr join public.roles r on r.id=pr.role_id where pr.profile_id=p.id and r.name='Comercial')) then 'OK' else 'REVIEW' end, 'El campo ya se usa para responsabilidad Comercial'
  union all select 'work_order_rls', case when exists (select 1 from pg_policies where schemaname='public' and tablename='work_orders' and policyname='work_orders_select_by_role') then 'OK' else 'BLOCKER' end, 'Politica actual de lectura localizada'
  union all select 'sat_rpc_088', case when to_regprocedure('public.dmp_review_work_order_sat(uuid,text,text,jsonb,text)') is not null then 'OK' else 'BLOCKER' end, 'RPC SAT 088 existente antes de reemplazo'
  union all select 'commercial_rpc_088', case when to_regprocedure('public.dmp_review_work_order_commercial(uuid,text)') is not null then 'OK' else 'BLOCKER' end, 'RPC Comercial 088 existente'
  union all select 'routing_columns', case when (select count(*) from information_schema.columns where table_schema='public' and table_name='work_orders' and column_name in ('sat_review_status','sat_review_destination','sat_review_flags','sat_review_reason','sat_reviewed_at','sat_reviewed_by','commercial_review_status','commercial_review_reason','commercial_reviewed_at','commercial_reviewed_by'))=10 then 'OK' else 'BLOCKER' end, 'Las 10 columnas 088 estan presentes'
  union all select 'sat_pending_rows', 'REVIEW', count(*)::text||' partes sat_review_status=pending' from public.work_orders where deleted_at is null and sat_review_status='pending'
  union all select 'commercial_pending_rows', 'REVIEW', count(*)::text||' partes commercial_review_status=pending' from public.work_orders where deleted_at is null and commercial_review_status='pending'
  union all select 'commercial_pending_valid_assignment_count', 'REVIEW', count(*)::text||' pendientes Comerciales con responsable Comercial valido' from public.work_orders wo where wo.deleted_at is null and wo.commercial_review_status='pending' and wo.sat_review_destination='comercial' and exists (select 1 from public.profiles p where p.id=wo.current_responsible_id and p.company_id=wo.company_id and p.active=true and p.deleted_at is null and (p.primary_area='Comercial' or exists (select 1 from public.profile_roles pr join public.roles r on r.id=pr.role_id where pr.profile_id=p.id and r.name='Comercial')))
  union all select 'commercial_pending_invalid_assignment_count', 'REVIEW', count(*)::text||' pendientes Comerciales sin responsable Comercial valido' from public.work_orders wo where wo.deleted_at is null and wo.commercial_review_status='pending' and (wo.sat_review_destination<>'comercial' or wo.current_responsible_id is null or not exists (select 1 from public.profiles p where p.id=wo.current_responsible_id and p.company_id=wo.company_id and p.active=true and p.deleted_at is null and (p.primary_area='Comercial' or exists (select 1 from public.profile_roles pr join public.roles r on r.id=pr.role_id where pr.profile_id=p.id and r.name='Comercial'))))
  union all select 'legacy_commercial_pending_requeue_candidates', 'REVIEW', count(*)::text||' candidatos historicos 088 para reenviar a SAT' from public.work_orders wo where wo.deleted_at is null and wo.commercial_review_status='pending' and wo.sat_review_status='approved' and wo.sat_review_destination='comercial' and (wo.current_responsible_id is null or not exists (select 1 from public.profiles p where p.id=wo.current_responsible_id and p.company_id=wo.company_id and p.active=true and p.deleted_at is null and (p.primary_area='Comercial' or exists (select 1 from public.profile_roles pr join public.roles r on r.id=pr.role_id where pr.profile_id=p.id and r.name='Comercial'))))
  union all select 'unresolvable_commercial_pending_count', case when count(*)=0 then 'OK' else 'BLOCKER' end, count(*)::text||' incoherencias fuera del backfill historico seguro' from public.work_orders wo where wo.deleted_at is null and wo.commercial_review_status='pending' and (wo.sat_review_destination<>'comercial' or wo.current_responsible_id is null or not exists (select 1 from public.profiles p where p.id=wo.current_responsible_id and p.company_id=wo.company_id and p.active=true and p.deleted_at is null and (p.primary_area='Comercial' or exists (select 1 from public.profile_roles pr join public.roles r on r.id=pr.profile_id and r.name='Comercial')))) and not (wo.sat_review_status='approved' and wo.sat_review_destination='comercial')
  union all select 'assignment_company_coherence', case when count(*)=0 then 'OK' else 'BLOCKER' end, count(*)::text||' responsables fuera de company' from public.work_orders wo join public.profiles p on p.id=wo.current_responsible_id where wo.deleted_at is null and p.company_id<>wo.company_id
  union all select 'assignment_semantics', case when exists (select 1 from information_schema.columns where table_schema='public' and table_name='work_order_assignments' and column_name='technician_id') then 'OK' else 'BLOCKER' end, 'work_order_assignments conserva semantica tecnica'
  union all select 'billing_objects_intact', case when to_regclass('public.invoices') is not null and to_regclass('public.invoice_work_orders') is not null then 'OK' else 'BLOCKER' end, 'Objetos de facturacion presentes'
  union all select 'new_089_objects_pre_state', case when to_regprocedure('public.dmp_reassign_work_order_commercial(uuid,uuid)') is null and to_regprocedure('public.dmp_department_routing_queue(text)') is null then 'OK' else 'REVIEW' end, 'Funciones nuevas 089 no aplicadas aun'
)
select check_name,status,detail from checks order by check_name;
