-- Read-only preflight for 079. Run only after 077 and 078 are applied.

with checks(check_group,check_name,status,affected_rows,details) as (
  select 'DEPENDENCIES','draft_prepare_rpc',case when to_regprocedure('public.dmp_prepare_invoice_from_work_order(uuid,date,text,numeric)') is not null then 'OK' else 'BLOCKER' end,case when to_regprocedure('public.dmp_prepare_invoice_from_work_order(uuid,date,text,numeric)') is not null then 1 else 0 end,'RPC de preparar disponible'
  union all select 'DEPENDENCIES','invoice_detail_tables',case when count(*)=3 then 'OK' else 'BLOCKER' end,count(*)::bigint,count(*)::text||' de 3 tablas economicas consultables' from information_schema.tables where table_schema='public' and table_name in('quote_lines','work_order_materials','work_order_time_entries')
  union all select 'DEPENDENCIES','source_columns',case when count(*)>=4 then 'OK' else 'BLOCKER' end,count(*)::bigint,count(*)::text||' columnas de origen 073/039' from information_schema.columns where table_schema='public' and ((table_name='work_order_materials' and column_name in('source','contributes_to_sale','total_price')) or (table_name='work_order_time_entries' and column_name in('source','contributes_to_sale','total_price')) or (table_name='work_order_cost_entries' and column_name in('source','contributes_to_sale','total_price')))
  union all select 'DEPENDENCIES','draft_idempotency_source',case when position('if v_existing_status=''borrador'' then return v_existing' in lower(pg_get_functiondef(p.oid)))>0 then 'OK' else 'BLOCKER' end,case when position('if v_existing_status=''borrador'' then return v_existing' in lower(pg_get_functiondef(p.oid)))>0 then 1 else 0 end,'Un borrador existente se devuelve en vez de duplicarse' from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname='dmp_prepare_invoice_from_work_order' and pg_get_function_identity_arguments(p.oid)='p_work_order_id uuid, p_due_date date, p_notes text, p_tax_rate numeric'
  union all select 'IMPACT','validated_pending_candidates',case when count(*)=0 then 'OK' else 'INFO' end,count(*)::bigint,count(*)::text||' partes candidatos a preparar' from public.work_orders where deleted_at is null and office_validation_status='validated' and economic_status='pendiente_facturar' and coalesce(warranty,false)=false and coalesce(billable,true)=true and not exists(select 1 from public.invoice_work_orders l where l.work_order_id=work_orders.id and l.deleted_at is null)
  union all select 'IMPACT','candidate_sale_zero',case when count(*)=0 then 'OK' else 'REVIEW' end,count(*)::bigint,count(*)::text||' candidatos sale_amount=0; se permite preparar' from public.work_orders where deleted_at is null and office_validation_status='validated' and economic_status='pendiente_facturar' and coalesce(warranty,false)=false and coalesce(billable,true)=true and coalesce(sale_amount,0)=0 and not exists(select 1 from public.invoice_work_orders l where l.work_order_id=work_orders.id and l.deleted_at is null)
  union all select 'IMPACT','candidate_estimated_only',case when count(*)=0 then 'REVIEW' else 'REVIEW' end,count(*)::bigint,count(*)::text||' candidatos estimated-only; nunca se copia la estimacion' from public.work_orders where deleted_at is null and office_validation_status='validated' and economic_status='pendiente_facturar' and coalesce(warranty,false)=false and coalesce(billable,true)=true and coalesce(sale_amount,0)=0 and coalesce(estimated_sale_amount,0)>0 and not exists(select 1 from public.invoice_work_orders l where l.work_order_id=work_orders.id and l.deleted_at is null)
  union all select 'IMPACT','candidate_without_amount',case when count(*)=0 then 'REVIEW' else 'REVIEW' end,count(*)::bigint,count(*)::text||' candidatos sin importe; requieren linea manual' from public.work_orders where deleted_at is null and office_validation_status='validated' and economic_status='pendiente_facturar' and coalesce(warranty,false)=false and coalesce(billable,true)=true and coalesce(sale_amount,0)=0 and coalesce(estimated_sale_amount,0)=0 and not exists(select 1 from public.invoice_work_orders l where l.work_order_id=work_orders.id and l.deleted_at is null)
  union all select 'DATA','invoice_duplicates',case when count(*)=0 then 'OK' else 'BLOCKER' end,count(*)::bigint,count(*)::text||' partes con enlaces de factura activos duplicados' from(select work_order_id from public.invoice_work_orders where deleted_at is null and work_order_id is not null group by work_order_id having count(*)>1)d
  union all select 'DATA','invoice_tenant_mismatch',case when count(*)=0 then 'OK' else 'BLOCKER' end,count(*)::bigint,count(*)::text||' enlaces con tenant incompatible' from public.invoice_work_orders l join public.invoices i on i.id=l.invoice_id join public.work_orders w on w.id=l.work_order_id where l.company_id is distinct from i.company_id or l.company_id is distinct from w.company_id
  union all select 'DATA','invalid_amounts',case when count(*)=0 then 'OK' else 'BLOCKER' end,count(*)::bigint,count(*)::text||' importes negativos en facturas o lineas' from(select id from public.invoices where subtotal<0 or tax_amount<0 or total_amount<0 union all select id from public.invoice_work_orders where subtotal<0 or tax_amount<0 or total_amount<0)x
)
select check_group,check_name,status,affected_rows,details from checks order by case status when 'BLOCKER' then 1 when 'REVIEW' then 2 when 'INFO' then 3 else 4 end,check_group,check_name;
