with function_info as (
  select p.oid,p.proname,pg_get_function_identity_arguments(p.oid) identity_arguments,p.prosecdef,p.proconfig,
    case when p.proname='dmp_create_work_order_full' then has_function_privilege('authenticated','public.dmp_create_work_order_full(jsonb)','execute') else has_function_privilege('authenticated','public.create_work_order_full(jsonb)','execute') end authenticated_execute,
    case when p.proname='dmp_create_work_order_full' then has_function_privilege('anon','public.dmp_create_work_order_full(jsonb)','execute') else has_function_privilege('anon','public.create_work_order_full(jsonb)','execute') end anon_execute
  from pg_proc p join pg_namespace n on n.oid=p.pronamespace
  where n.nspname='public' and p.proname in ('dmp_create_work_order_full','create_work_order_full')
), checks(check_name,passed,detail) as (
  select 'wrapper_exists',exists(select 1 from function_info where proname='dmp_create_work_order_full' and identity_arguments='p_payload jsonb'),'wrapper='||(select coalesce(jsonb_agg(jsonb_build_object('identity_arguments',identity_arguments,'prosecdef',prosecdef,'proconfig',proconfig,'authenticated_execute',authenticated_execute,'anon_execute',anon_execute) order by oid),'[]'::jsonb)::text from function_info where proname='dmp_create_work_order_full')
  union all select 'wrapper_security_definer',coalesce((select prosecdef from function_info where proname='dmp_create_work_order_full' and identity_arguments='p_payload jsonb'),false),'wrapper security detail='||(select coalesce(jsonb_agg(jsonb_build_object('identity_arguments',identity_arguments,'prosecdef',prosecdef,'proconfig',proconfig,'authenticated_execute',authenticated_execute,'anon_execute',anon_execute) order by oid),'[]'::jsonb)::text from function_info where proname='dmp_create_work_order_full')
  union all select 'wrapper_search_path',exists(select 1 from function_info where proname='dmp_create_work_order_full' and exists(select 1 from unnest(coalesce(proconfig,array[]::text[])) as config where lower(config)='search_path=public')),'wrapper normalized search_path detail='||(select coalesce(jsonb_agg(jsonb_build_object('identity_arguments',identity_arguments,'prosecdef',prosecdef,'proconfig',proconfig) order by oid),'[]'::jsonb)::text from function_info where proname='dmp_create_work_order_full')
  union all select 'wrapper_grants',coalesce((select authenticated_execute and not anon_execute from function_info where proname='dmp_create_work_order_full' and identity_arguments='p_payload jsonb'),false),'wrapper grants detail='||(select coalesce(jsonb_agg(jsonb_build_object('identity_arguments',identity_arguments,'authenticated_execute',authenticated_execute,'anon_execute',anon_execute) order by oid),'[]'::jsonb)::text from function_info where proname='dmp_create_work_order_full')
  union all select 'inner_exists',exists(select 1 from function_info where proname='create_work_order_full' and identity_arguments='p_payload jsonb'),'inner='||(select coalesce(jsonb_agg(jsonb_build_object('identity_arguments',identity_arguments,'prosecdef',prosecdef,'proconfig',proconfig,'authenticated_execute',authenticated_execute,'anon_execute',anon_execute) order by oid),'[]'::jsonb)::text from function_info where proname='create_work_order_full')
  union all select 'inner_security_definer',coalesce((select prosecdef from function_info where proname='create_work_order_full' and identity_arguments='p_payload jsonb'),false),'inner security detail='||(select coalesce(jsonb_agg(jsonb_build_object('identity_arguments',identity_arguments,'prosecdef',prosecdef,'proconfig',proconfig) order by oid),'[]'::jsonb)::text from function_info where proname='create_work_order_full')
  union all select 'inner_search_path',exists(select 1 from function_info where proname='create_work_order_full' and exists(select 1 from unnest(coalesce(proconfig,array[]::text[])) as config where lower(config)='search_path=public')),'inner normalized search_path detail='||(select coalesce(jsonb_agg(jsonb_build_object('identity_arguments',identity_arguments,'prosecdef',prosecdef,'proconfig',proconfig) order by oid),'[]'::jsonb)::text from function_info where proname='create_work_order_full')
)
select check_name,passed,detail from checks order by check_name;
