with function_info as (
  select p.oid,p.proname,pg_get_function_identity_arguments(p.oid) identity_arguments,p.prosecdef,p.proconfig,pg_get_functiondef(p.oid) definition,
    case when p.proname='dmp_finalize_work_order_technical' then has_function_privilege('authenticated','public.dmp_finalize_work_order_technical(uuid,jsonb)','execute') when p.proname='resolve_check_technician_from_work_order' then has_function_privilege('authenticated','public.resolve_check_technician_from_work_order()','execute') else null end authenticated_execute,
    case when p.proname='dmp_finalize_work_order_technical' then has_function_privilege('anon','public.dmp_finalize_work_order_technical(uuid,jsonb)','execute') when p.proname='resolve_check_technician_from_work_order' then has_function_privilege('anon','public.resolve_check_technician_from_work_order()','execute') else null end anon_execute
  from pg_proc p join pg_namespace n on n.oid=p.pronamespace
  where n.nspname='public' and p.proname in ('dmp_finalize_work_order_technical','dmp_quote_terminal_header_guard','resolve_check_technician_from_work_order')
), details as (
  select coalesce(jsonb_agg(jsonb_build_object('proname',proname,'identity_arguments',identity_arguments,'prosecdef',prosecdef,'proconfig',proconfig,'authenticated_execute',authenticated_execute,'anon_execute',anon_execute) order by proname,identity_arguments),'[]'::jsonb) value from function_info
), checks(check_name,passed,detail) as (
  select 'finalize_exists',exists(select 1 from function_info where proname='dmp_finalize_work_order_technical' and identity_arguments='p_work_order_id uuid, p_payload jsonb'),'function inventory='||(select value::text from details)
  union all select 'finalize_security_definer',coalesce((select prosecdef from function_info where proname='dmp_finalize_work_order_technical' and identity_arguments='p_work_order_id uuid, p_payload jsonb'),false),'finalize security='||(select value::text from details)
  union all select 'finalize_search_path',exists(select 1 from function_info where proname='dmp_finalize_work_order_technical' and exists(select 1 from unnest(coalesce(proconfig,array[]::text[])) as config where lower(config)='search_path=public')),'finalize search_path='||(select value::text from details)
  union all select 'quote_update_absent',not exists(select 1 from function_info where proname='dmp_finalize_work_order_technical' and position('update public.quotes' in lower(definition))>0),'quote DML pattern absent; read quote references='||(select count(*)::text from function_info where proname='dmp_finalize_work_order_technical' and position('quote' in lower(definition))>0)
  union all select 'quote_line_update_absent',not exists(select 1 from function_info where proname='dmp_finalize_work_order_technical' and (position('update public.quote_lines' in lower(definition))>0 or position('insert into public.quote_lines' in lower(definition))>0 or position('delete from public.quote_lines' in lower(definition))>0)),'quote_lines write patterns absent; read reference present='||(select (position('public.quote_lines' in lower(definition))>0)::text from function_info where proname='dmp_finalize_work_order_technical')
  union all select 'invoice_update_absent',not exists(select 1 from function_info where proname='dmp_finalize_work_order_technical' and (position('update public.invoices' in lower(definition))>0 or position('insert into public.invoices' in lower(definition))>0 or position('delete from public.invoices' in lower(definition))>0)),'invoice write patterns absent'
  union all select 'invoice_line_update_absent',not exists(select 1 from function_info where proname='dmp_finalize_work_order_technical' and (position('update public.invoice_work_orders' in lower(definition))>0 or position('insert into public.invoice_work_orders' in lower(definition))>0 or position('delete from public.invoice_work_orders' in lower(definition))>0)),'invoice_work_orders write patterns absent'
  union all select 'work_order_update_present',exists(select 1 from function_info where proname='dmp_finalize_work_order_technical' and position('update public.work_orders' in lower(definition))>0),'work_order update pattern present'
  union all select 'history_audit_present',exists(select 1 from function_info where proname='dmp_finalize_work_order_technical' and position('work_order_status_history' in lower(definition))>0 and position('audit_log' in lower(definition))>0),'history and audit patterns present'
)
select check_name,passed,detail from checks order by check_name;
