-- Read-only structural verification for SUPPLIER-PAYMENTS-020.
with expected_tables(table_name) as (values
  ('supplier_invoice_payments')
), expected_columns(table_name, column_name, udt_name, is_nullable, default_fragment) as (values
  ('supplier_invoice_payments','id','uuid','NO',null),
  ('supplier_invoice_payments','company_id','uuid','NO',null),
  ('supplier_invoice_payments','supplier_invoice_id','uuid','NO',null),
  ('supplier_invoice_payments','payment_date','date','NO','CURRENT_DATE'),
  ('supplier_invoice_payments','amount','numeric','NO',null),
  ('supplier_invoice_payments','payment_method','text','NO','''transferencia'''),
  ('supplier_invoice_payments','reference','text','YES',null),
  ('supplier_invoice_payments','notes','text','YES',null),
  ('supplier_invoice_payments','created_at','timestamptz','NO','now()'),
  ('supplier_invoice_payments','created_by','uuid','NO',null),
  ('supplier_invoice_payments','reversed_at','timestamptz','YES',null),
  ('supplier_invoice_payments','reversed_by','uuid','YES',null),
  ('supplier_invoice_payments','reversal_reason','text','YES',null)
), expected_fks(conname, relname, referenced, local_cols, referenced_cols) as (values
  ('supplier_invoice_payments_invoice_company_fk','supplier_invoice_payments','supplier_invoices',array['company_id','supplier_invoice_id']::text[],array['company_id','id']::text[]),
  ('supplier_invoice_payments_created_by_fkey','supplier_invoice_payments','profiles',array['created_by']::text[],array['id']::text[]),
  ('supplier_invoice_payments_reversed_by_fkey','supplier_invoice_payments','profiles',array['reversed_by']::text[],array['id']::text[])
), expected_checks(conname, required_tokens) as (values
  ('supplier_invoice_payments_amount_check',array['amount','0']::text[]),
  ('supplier_invoice_payments_method_check',array['payment_method','transferencia','tarjeta','efectivo','domiciliacion','otro']::text[]),
  ('supplier_invoice_payments_reversal_check',array['reversed_at','reversed_by','reversal_reason','null']::text[])
), expected_policies(policyname, tablename, cmd, using_fragment, check_fragment, permission_fragment, require_platform) as (values
  ('supplier_invoice_payments_select_permissions','supplier_invoice_payments','SELECT','current_company_id',null,'supplier_payments.read',true),
  ('supplier_invoice_payments_insert_denied','supplier_invoice_payments','INSERT',null,'false',null,false),
  ('supplier_invoice_payments_update_denied','supplier_invoice_payments','UPDATE','false','false',null,false),
  ('supplier_invoice_payments_delete_denied','supplier_invoice_payments','DELETE','false',null,null,false)
), expected_role_grants(role_name, permission_code) as (values
  ('superadmin','supplier_payments.read'),('superadmin','supplier_payments.create'),('superadmin','supplier_payments.reverse'),
  ('Gerencia','supplier_payments.read'),('Gerencia','supplier_payments.create'),('Gerencia','supplier_payments.reverse'),
  ('Oficina','supplier_payments.read'),('Oficina','supplier_payments.create'),('Oficina','supplier_payments.reverse')
), expected_functions(signature) as (values
  ('public.dmp_record_supplier_payment(uuid,numeric,date,text,text,text)'),
  ('public.dmp_reverse_supplier_payment(uuid,text)'),
  ('public.dmp_cancel_supplier_invoice(uuid,text)')
), expected_indexes(index_name, key_defs, desc_positions, predicate, is_unique) as (values
  ('supplier_invoice_payments_invoice_idx',array['company_id','supplier_invoice_id','payment_date']::text[],array[2]::int[],'',false),
  ('supplier_invoice_payments_active_invoice_idx',array['company_id','supplier_invoice_id']::text[],array[]::int[],'reversed_at is null',false)
), expected_audit_operations(value) as (values
  ('INSERT'),('UPDATE'),('DELETE'),('SOFT_DELETE'),('OPERATIONAL_UPDATE'),('TECHNICAL_FINALIZE'),
  ('TECHNICAL_FINALIZE_PENDING_OFFICE'),('OFFICE_VALIDATE'),('OFFICE_REJECT'),('INVOICE_DRAFT_CREATE'),
  ('INVOICE_DRAFT_UPDATE'),('INVOICE_ISSUE'),('INVOICE_ISSUE_OVERRIDE'),('PAYMENT_RECORD'),('PAYMENT_REVERSE'),
  ('MATERIAL_CREATE'),('WAREHOUSE_STOCK_RECONCILE'),('ECONOMIC_REVIEW_APPROVE'),('ECONOMIC_REVIEW_REOPEN')
), audit_operation_actual(value) as (
  select m[1] from pg_constraint c cross join lateral regexp_matches(pg_get_constraintdef(c.oid), '''([^'']+)''','g') m where c.conname='audit_log_operation_check'
), checks(check_group, check_name, status, details) as (
  select 'TABLES','supplier_invoice_payments',case when count(*)=1 then 'PASS' else 'BLOCKER' end,'payment table exists' from information_schema.tables t join expected_tables e on e.table_name=t.table_name where t.table_schema='public'
  union all select 'COLUMNS','types_nullability_defaults',case when count(*)=0 then 'PASS' else 'BLOCKER' end,coalesce(string_agg(e.column_name,', ' order by e.column_name),'all payment columns match') from expected_columns e left join information_schema.columns c on c.table_schema='public' and c.table_name=e.table_name and c.column_name=e.column_name where c.column_name is null or c.udt_name<>e.udt_name or c.is_nullable<>e.is_nullable or (e.default_fragment is not null and position(lower(e.default_fragment) in lower(coalesce(c.column_default,'')))=0)
  union all select 'FKS','tenant_and_actor_fks',case when count(*)=0 then 'PASS' else 'BLOCKER' end,coalesce(string_agg(e.conname,', ' order by e.conname),'all tenant and actor FKs match in order') from expected_fks e left join pg_constraint c on c.conname=e.conname and c.contype='f' and c.convalidated and c.conrelid=to_regclass('public.'||e.relname) and c.confrelid=to_regclass('public.'||e.referenced) and (select array_agg(a.attname::text order by k.ord) from unnest(c.conkey) with ordinality k(attnum,ord) join pg_attribute a on a.attrelid=c.conrelid and a.attnum=k.attnum and not a.attisdropped)=e.local_cols and (select array_agg(a.attname::text order by k.ord) from unnest(c.confkey) with ordinality k(attnum,ord) join pg_attribute a on a.attrelid=c.confrelid and a.attnum=k.attnum and not a.attisdropped)=e.referenced_cols where c.oid is null
  union all select 'CHECKS','payment_checks',case when count(*)=0 then 'PASS' else 'BLOCKER' end,coalesce(string_agg(e.conname,', ' order by e.conname),'positive amount, method and reversal consistency checks match') from expected_checks e left join pg_constraint c on c.conname=e.conname and c.contype='c' and c.convalidated and (select bool_and(position(regexp_replace(lower(token),'[^a-z0-9_]','','g') in regexp_replace(lower(pg_get_constraintdef(c.oid)),'[^a-z0-9_]','','g'))>0) from unnest(e.required_tokens) tokens(token)) where c.oid is null
   union all select 'INDEXES','payment_indexes',case when count(*)=0 then 'PASS' else 'BLOCKER' end,coalesce(string_agg(e.index_name,', ' order by e.index_name),'invoice and active-payment indexes match ordered keys and predicates') from expected_indexes e left join pg_index i on i.indexrelid=to_regclass('public.'||e.index_name) and i.indisunique=e.is_unique and regexp_replace(regexp_replace(regexp_replace(lower(coalesce(pg_get_expr(i.indpred,i.indrelid),'')),'\s+','','g'),'::[a-z0-9_\.\[\]]+','','g'),'[()]','','g')=regexp_replace(regexp_replace(regexp_replace(lower(coalesce(e.predicate,'')),'\s+','','g'),'::[a-z0-9_\.\[\]]+','','g'),'[()]','','g') and (select array_agg(regexp_replace(lower(pg_get_indexdef(i.indexrelid,n,true)),'\s+','','g') order by n) from generate_series(1,i.indnkeyatts) n)= (select array_agg(regexp_replace(lower(key_def),'\s+','','g') order by ord) from unnest(e.key_defs) with ordinality keys(key_def,ord)) and not exists (select 1 from unnest(e.desc_positions) desc_keys(key_position) where coalesce(i.indoption[desc_keys.key_position] & 1,0)<>1) where i.indexrelid is null
  union all select 'RLS','payments_rls',case when exists(select 1 from pg_class c where c.oid=to_regclass('public.supplier_invoice_payments') and c.relrowsecurity) then 'PASS' else 'BLOCKER' end,'supplier_invoice_payments has RLS enabled'
  union all select 'ACL','table_privileges',case when exists(select 1 from pg_class c cross join lateral aclexplode(coalesce(c.relacl,acldefault('r',c.relowner))) x where c.oid=to_regclass('public.supplier_invoice_payments') and x.grantee='authenticated'::regrole and x.privilege_type='SELECT') and not exists(select 1 from pg_class c cross join lateral aclexplode(coalesce(c.relacl,acldefault('r',c.relowner))) x where c.oid=to_regclass('public.supplier_invoice_payments') and (x.grantee in ('authenticated'::regrole,'anon'::regrole) or x.grantee=0) and x.privilege_type in ('INSERT','UPDATE','DELETE','TRUNCATE','REFERENCES','TRIGGER')) and not exists(select 1 from pg_class c cross join lateral aclexplode(coalesce(c.relacl,acldefault('r',c.relowner))) x where c.oid=to_regclass('public.supplier_invoice_payments') and ((x.grantee='anon'::regrole or x.grantee=0) and x.privilege_type is not null)) then 'PASS' else 'BLOCKER' end,'authenticated has SELECT only; authenticated INSERT/UPDATE/DELETE and anon/PUBLIC privileges are absent'
  union all select 'POLICIES','exact_payment_policies',case when (select count(*) from pg_policies where schemaname='public' and tablename='supplier_invoice_payments')=(select count(*) from expected_policies) and (select count(*) from expected_policies e join pg_policies p on p.schemaname='public' and p.tablename=e.tablename and p.policyname=e.policyname and p.cmd=e.cmd and p.roles=array['authenticated']::name[] and (e.using_fragment is null or position(e.using_fragment in lower(coalesce(p.qual,'')))>0) and (e.check_fragment is null or position(e.check_fragment in lower(coalesce(p.with_check,'')))>0) and (e.permission_fragment is null or position(e.permission_fragment in lower(coalesce(p.qual,'')||coalesce(p.with_check,'')))>0) and (not e.require_platform or position('is_platform_superadmin' in lower(coalesce(p.qual,'')||coalesce(p.with_check,'')))>0) and ((e.cmd in ('SELECT','DELETE') and p.with_check is null) or (e.cmd in ('INSERT','UPDATE') and p.with_check is not null)))=(select count(*) from expected_policies) then 'PASS' else 'BLOCKER' end,'exactly four authenticated policies; SELECT is permission-scoped and direct writes are denied'
  union all select 'PERMISSIONS','permission_keys',case when (select count(*) from public.permissions where code like 'supplier_payments.%')=3 and not exists(select 1 from public.permissions where code like 'supplier_payments.%' and code not in ('supplier_payments.read','supplier_payments.create','supplier_payments.reverse')) and (select count(*) from public.permissions where code in ('supplier_payments.read','supplier_payments.create','supplier_payments.reverse'))=3 then 'PASS' else 'BLOCKER' end,'exactly read, create and reverse permissions exist in the namespace'
  union all select 'ROLE_GRANTS','economic_roles',case when not exists(select 1 from expected_role_grants e where not exists(select 1 from public.role_permissions rp join public.roles r on r.id=rp.role_id join public.permissions p on p.id=rp.permission_id where r.name=e.role_name and p.code=e.permission_code)) and not exists(select 1 from public.role_permissions rp join public.roles r on r.id=rp.role_id join public.permissions p on p.id=rp.permission_id where p.code like 'supplier_payments.%' and not exists(select 1 from expected_role_grants e where e.role_name=r.name and e.permission_code=p.code)) then 'PASS' else 'BLOCKER' end,'exactly superadmin, Gerencia and Oficina receive exactly the three payment permissions'
  union all select 'FUNCTIONS','signatures_security',case when (select count(*) from expected_functions e join pg_proc p on p.oid=to_regprocedure(e.signature) where p.prosecdef and coalesce(array_to_string(p.proconfig,','),'') like '%search_path=public%')=3 then 'PASS' else 'BLOCKER' end,'record, reverse and cancellation signatures are SECURITY DEFINER with fixed search_path'
  union all select 'ACL','public_rpcs',case when (select count(*) from (select e.signature,coalesce(bool_or(x.grantee='authenticated'::regrole and x.privilege_type='EXECUTE'),false) auth_exec,coalesce(bool_or(x.grantee='anon'::regrole and x.privilege_type='EXECUTE'),false) anon_exec,coalesce(bool_or(x.grantee=0 and x.privilege_type='EXECUTE'),false) public_exec from (values ('public.dmp_record_supplier_payment(uuid,numeric,date,text,text,text)'),('public.dmp_reverse_supplier_payment(uuid,text)'),('public.dmp_cancel_supplier_invoice(uuid,text)')) e(signature) join pg_proc p on p.oid=to_regprocedure(e.signature) left join lateral aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) x on true group by e.signature) a where auth_exec and not anon_exec and not public_exec)=3 then 'PASS' else 'BLOCKER' end,'public payment RPCs are authenticated-only'
  union all select 'RPC','record_supplier_payment_contract',case when position('for update' in lower(pg_get_functiondef(to_regprocedure('public.dmp_record_supplier_payment(uuid,numeric,date,text,text,text)'))))>0 and position('status <> ''registered''' in lower(pg_get_functiondef(to_regprocedure('public.dmp_record_supplier_payment(uuid,numeric,date,text,text,text)'))))>0 and position('reversed_at is null' in lower(pg_get_functiondef(to_regprocedure('public.dmp_record_supplier_payment(uuid,numeric,date,text,text,text)'))))>0 and position('nullif(trim(coalesce(p_payment_method' in lower(pg_get_functiondef(to_regprocedure('public.dmp_record_supplier_payment(uuid,numeric,date,text,text,text)'))))>0 and position('supplier_invoice_payments' in lower(pg_get_functiondef(to_regprocedure('public.dmp_record_supplier_payment(uuid,numeric,date,text,text,text)'))))>0 then 'PASS' else 'BLOCKER' end,'record payment locks invoice, requires registered status, valid method and sums active payments'
  union all select 'RPC','reverse_supplier_payment_contract',case when position('supplier_invoices' in lower(pg_get_functiondef(to_regprocedure('public.dmp_reverse_supplier_payment(uuid,text)'))))>0 and position('supplier_invoice_payments' in lower(pg_get_functiondef(to_regprocedure('public.dmp_reverse_supplier_payment(uuid,text)'))))>0 and (length(lower(pg_get_functiondef(to_regprocedure('public.dmp_reverse_supplier_payment(uuid,text)'))))-length(replace(lower(pg_get_functiondef(to_regprocedure('public.dmp_reverse_supplier_payment(uuid,text)'))),'for update','')))=2*length('for update') and position('reversed_at is not null' in lower(pg_get_functiondef(to_regprocedure('public.dmp_reverse_supplier_payment(uuid,text)'))))>0 then 'PASS' else 'BLOCKER' end,'reverse payment locks invoice before payment, requires active row and records reversal'
  union all select 'CANCELLATION','active_payment_guard',case when position('supplier_invoice_payments' in lower(pg_get_functiondef(to_regprocedure('public.dmp_cancel_supplier_invoice(uuid,text)'))))>0 and position('reversed_at is null' in lower(pg_get_functiondef(to_regprocedure('public.dmp_cancel_supplier_invoice(uuid,text)'))))>0 and position('primero deben revertirse los pagos activos' in lower(pg_get_functiondef(to_regprocedure('public.dmp_cancel_supplier_invoice(uuid,text)'))))>0 then 'PASS' else 'BLOCKER' end,'active supplier payments block invoice cancellation'
  union all select 'CANCELLATION','preserved_contract',case when position('supplier_invoices.cancel' in lower(pg_get_functiondef(to_regprocedure('public.dmp_cancel_supplier_invoice(uuid,text)'))))>0 and position('is_platform_superadmin' in lower(pg_get_functiondef(to_regprocedure('public.dmp_cancel_supplier_invoice(uuid,text)'))))>0 and position('for update' in lower(pg_get_functiondef(to_regprocedure('public.dmp_cancel_supplier_invoice(uuid,text)'))))>0 and position('nullif(trim(p_reason' in lower(pg_get_functiondef(to_regprocedure('public.dmp_cancel_supplier_invoice(uuid,text)'))))>0 and position('set_config' in lower(pg_get_functiondef(to_regprocedure('public.dmp_cancel_supplier_invoice(uuid,text)'))))>0 and position('dmp.supplier_invoice_lifecycle' in lower(pg_get_functiondef(to_regprocedure('public.dmp_cancel_supplier_invoice(uuid,text)'))))>0 and position('dmp024_active_profile' in lower(pg_get_functiondef(to_regprocedure('public.dmp_cancel_supplier_invoice(uuid,text)'))))>0 and position('audit_log' in lower(pg_get_functiondef(to_regprocedure('public.dmp_cancel_supplier_invoice(uuid,text)'))))>0 then 'PASS' else 'BLOCKER' end,'130 cancellation permission, platform, tenant, lock, actor, lifecycle and audit contract is preserved'
  union all select 'AUDIT','canonical_operations',case when not exists(select 1 from expected_audit_operations e where not exists(select 1 from audit_operation_actual a where a.value=e.value)) and not exists(select 1 from audit_operation_actual a where not exists(select 1 from expected_audit_operations e where e.value=a.value)) then 'PASS' else 'BLOCKER' end,'canonical audit operations plus PAYMENT_REVERSE are present'
), summary(check_group, check_name, status, details) as (
  select 'SUMMARY','verify_131_supplier_invoice_payments',case when count(*) filter(where status='BLOCKER')=0 then 'PASS' else 'BLOCKER' end,case when count(*) filter(where status='BLOCKER')=0 then 'all checks passed' else count(*) filter(where status='BLOCKER')::text||' checks failed' end from checks
)
select check_group, check_name, status, details from (select check_group,check_name,status,details from checks union all select check_group,check_name,status,details from summary) result
order by case when check_group='SUMMARY' then 1 else 0 end, check_group, check_name;
