-- Read-only structural verification for SUPPLIER-INVOICE-CORE-018.
-- Every row is an explicit PASS/BLOCKER result; this script never mutates data.
with expected_tables(table_name) as (values
  ('supplier_invoices'), ('supplier_invoice_lines'), ('supplier_invoice_allocations')
), expected_columns(table_name, column_name, udt_name, is_nullable, default_fragment) as (values
  ('supplier_invoices','id','uuid','NO',null), ('supplier_invoices','company_id','uuid','NO',null), ('supplier_invoices','code','text','NO',null), ('supplier_invoices','supplier_id','uuid','NO',null), ('supplier_invoices','supplier_invoice_number','text','YES',null), ('supplier_invoices','invoice_date','date','NO','CURRENT_DATE'), ('supplier_invoices','due_date','date','YES',null), ('supplier_invoices','status','text','NO','''draft'''), ('supplier_invoices','currency_code','text','NO','''EUR'''), ('supplier_invoices','subtotal','numeric','NO','0'), ('supplier_invoices','tax_amount','numeric','NO','0'), ('supplier_invoices','total_amount','numeric','NO','0'), ('supplier_invoices','notes','text','YES',null), ('supplier_invoices','created_at','timestamptz','NO','now()'), ('supplier_invoices','created_by','uuid','NO',null), ('supplier_invoices','updated_at','timestamptz','NO','now()'), ('supplier_invoices','updated_by','uuid','YES',null), ('supplier_invoices','cancelled_at','timestamptz','YES',null), ('supplier_invoices','cancelled_by','uuid','YES',null), ('supplier_invoices','cancellation_reason','text','YES',null),
  ('supplier_invoice_lines','id','uuid','NO',null), ('supplier_invoice_lines','company_id','uuid','NO',null), ('supplier_invoice_lines','supplier_invoice_id','uuid','NO',null), ('supplier_invoice_lines','description','text','NO',null), ('supplier_invoice_lines','material_id','uuid','YES',null), ('supplier_invoice_lines','quantity','numeric','NO',null), ('supplier_invoice_lines','unit_price','numeric','NO',null), ('supplier_invoice_lines','tax_rate','numeric','NO','21'), ('supplier_invoice_lines','net_amount','numeric','NO','0'), ('supplier_invoice_lines','tax_amount','numeric','NO','0'), ('supplier_invoice_lines','total_amount','numeric','NO','0'), ('supplier_invoice_lines','created_at','timestamptz','NO','now()'), ('supplier_invoice_lines','updated_at','timestamptz','NO','now()'),
  ('supplier_invoice_allocations','id','uuid','NO',null), ('supplier_invoice_allocations','company_id','uuid','NO',null), ('supplier_invoice_allocations','supplier_invoice_id','uuid','NO',null), ('supplier_invoice_allocations','supplier_invoice_line_id','uuid','NO',null), ('supplier_invoice_allocations','purchase_order_id','uuid','YES',null), ('supplier_invoice_allocations','purchase_order_line_id','uuid','YES',null), ('supplier_invoice_allocations','purchase_receipt_id','uuid','YES',null), ('supplier_invoice_allocations','purchase_receipt_line_id','uuid','YES',null), ('supplier_invoice_allocations','allocated_quantity','numeric','YES',null), ('supplier_invoice_allocations','allocated_amount','numeric','NO',null), ('supplier_invoice_allocations','created_at','timestamptz','NO','now()'), ('supplier_invoice_allocations','created_by','uuid','NO',null)
), expected_fks(conname, relname, referenced, local_cols, referenced_cols) as (values
  ('supplier_invoices_supplier_company_fk','supplier_invoices','suppliers',array['company_id','supplier_id']::text[],array['company_id','id']::text[]), ('supplier_invoice_lines_invoice_company_fk','supplier_invoice_lines','supplier_invoices',array['company_id','supplier_invoice_id']::text[],array['company_id','id']::text[]), ('supplier_invoice_lines_material_company_fk','supplier_invoice_lines','materials',array['company_id','material_id']::text[],array['company_id','id']::text[]), ('supplier_invoice_allocations_invoice_company_fk','supplier_invoice_allocations','supplier_invoices',array['company_id','supplier_invoice_id']::text[],array['company_id','id']::text[]), ('supplier_invoice_allocations_line_company_fk','supplier_invoice_allocations','supplier_invoice_lines',array['company_id','supplier_invoice_line_id']::text[],array['company_id','id']::text[]), ('supplier_invoice_allocations_order_company_fk','supplier_invoice_allocations','purchase_orders',array['company_id','purchase_order_id']::text[],array['company_id','id']::text[]), ('supplier_invoice_allocations_order_line_company_fk','supplier_invoice_allocations','purchase_order_lines',array['company_id','purchase_order_line_id']::text[],array['company_id','id']::text[]), ('supplier_invoice_allocations_receipt_company_fk','supplier_invoice_allocations','purchase_receipts',array['company_id','purchase_receipt_id']::text[],array['company_id','id']::text[]), ('supplier_invoice_allocations_receipt_line_company_fk','supplier_invoice_allocations','purchase_receipt_lines',array['company_id','purchase_receipt_line_id']::text[],array['company_id','id']::text[])
), expected_checks(conname, required_tokens) as (values
  ('supplier_invoices_status_check',array['status','draft','registered','cancelled']::text[]), ('supplier_invoices_number_check',array['supplier_invoice_number']::text[]), ('supplier_invoices_dates_check',array['due_date']::text[]), ('supplier_invoice_lines_values_check',array['quantity','unit_price','tax_rate','0']::text[]), ('supplier_invoice_allocations_target_check',array['purchase_order_line_id','purchase_receipt_line_id']::text[]), ('supplier_invoice_allocations_amount_check',array['allocated_amount','0']::text[])
), expected_policies(policyname, tablename, cmd, using_fragment, check_fragment, permission_fragment, require_platform) as (values
  ('supplier_invoices_select_permissions','supplier_invoices','SELECT','current_company_id',null,'supplier_invoices.read',true), ('supplier_invoices_insert_permissions','supplier_invoices','INSERT',null,'company_id','supplier_invoices.create',true), ('supplier_invoices_update_permissions','supplier_invoices','UPDATE','status = ''draft''','status = ''draft''','supplier_invoices.update',true),
  ('supplier_invoice_lines_select_permissions','supplier_invoice_lines','SELECT','current_company_id',null,'supplier_invoices.read',true), ('supplier_invoice_lines_insert_permissions','supplier_invoice_lines','INSERT',null,'company_id','supplier_invoices.update',true), ('supplier_invoice_lines_update_permissions','supplier_invoice_lines','UPDATE','status = ''draft''','status = ''draft''','supplier_invoices.update',true), ('supplier_invoice_lines_delete_permissions','supplier_invoice_lines','DELETE','status = ''draft''',null,'supplier_invoices.update',true),
  ('supplier_invoice_allocations_select_permissions','supplier_invoice_allocations','SELECT','current_company_id',null,'supplier_invoices.read',true), ('supplier_invoice_allocations_insert_permissions','supplier_invoice_allocations','INSERT',null,'company_id','supplier_invoices.update',true), ('supplier_invoice_allocations_delete_permissions','supplier_invoice_allocations','DELETE','status = ''draft''',null,'supplier_invoices.update',true)
), expected_functions(signature, require_security_definer) as (values
  ('public.dmp_register_supplier_invoice(uuid)',true), ('public.dmp_cancel_supplier_invoice(uuid,text)',true), ('public.dmp_supplier_invoice_recalculate(uuid)',true), ('public.dmp_supplier_invoice_guard()',true), ('public.dmp_supplier_invoice_line_guard()',true), ('public.dmp_supplier_invoice_line_totals()',true), ('public.dmp_supplier_invoice_allocation_guard()',true)
), expected_triggers(trigger_name, table_name, function_name, event_mask) as (values
  ('supplier_invoice_guard_trigger','supplier_invoices','dmp_supplier_invoice_guard',16), ('supplier_invoice_line_guard_trigger','supplier_invoice_lines','dmp_supplier_invoice_line_guard',28), ('supplier_invoice_line_totals_trigger','supplier_invoice_lines','dmp_supplier_invoice_line_totals',28), ('supplier_invoice_allocation_guard_trigger','supplier_invoice_allocations','dmp_supplier_invoice_allocation_guard',28)
), expected_unique_indexes(index_name, key_cols, predicate) as (values
  ('supplier_invoice_allocations_order_only_unique',array['company_id','supplier_invoice_line_id','purchase_order_line_id']::text[],'purchase_order_line_id is not null and purchase_receipt_line_id is null'), ('supplier_invoice_allocations_receipt_only_unique',array['company_id','supplier_invoice_line_id','purchase_receipt_line_id']::text[],'purchase_order_line_id is null and purchase_receipt_line_id is not null'), ('supplier_invoice_allocations_order_receipt_unique',array['company_id','supplier_invoice_line_id','purchase_order_line_id','purchase_receipt_line_id']::text[],'purchase_order_line_id is not null and purchase_receipt_line_id is not null')
), expected_document_types(value) as (values
  ('Manual de instalacion'),('Manual de mantenimiento'),('Manual de motor'),('Manual de cuadro'),('Esquema electrico'),('Despiece'),('Declaracion CE'),('Instrucciones de desbloqueo'),('Procedimiento interno'),('Ficha tecnica'),('Factura proveedor')
), expected_document_link_types(value) as (values
  ('Cliente'),('Centro'),('Equipo'),('Tipo de equipo'),('Marca'),('Modelo'),('Motor'),('Cuadro'),('Expediente'),('Parte'),('Check'),('Factura proveedor')
), expected_audit_operations(value) as (values
  ('INSERT'),('UPDATE'),('DELETE'),('SOFT_DELETE'),('OPERATIONAL_UPDATE'),('TECHNICAL_FINALIZE'),('TECHNICAL_FINALIZE_PENDING_OFFICE'),('OFFICE_VALIDATE'),('OFFICE_REJECT'),('INVOICE_DRAFT_CREATE'),('INVOICE_DRAFT_UPDATE'),('INVOICE_ISSUE'),('INVOICE_ISSUE_OVERRIDE'),('PAYMENT_RECORD'),('MATERIAL_CREATE'),('WAREHOUSE_STOCK_RECONCILE'),('ECONOMIC_REVIEW_APPROVE'),('ECONOMIC_REVIEW_REOPEN')
), document_type_actual(value) as (select m[1] from pg_constraint c cross join lateral regexp_matches(pg_get_constraintdef(c.oid), '''([^'']+)''','g') m where c.conname='documents_type_check'), document_link_type_actual(value) as (select m[1] from pg_constraint c cross join lateral regexp_matches(pg_get_constraintdef(c.oid), '''([^'']+)''','g') m where c.conname='document_links_related_type_check'), audit_operation_actual(value) as (select m[1] from pg_constraint c cross join lateral regexp_matches(pg_get_constraintdef(c.oid), '''([^'']+)''','g') m where c.conname='audit_log_operation_check'), checks(check_group, check_name, status, details) as (
  select 'TABLES','three_tables',case when (select count(*) from information_schema.tables t join expected_tables e on e.table_name=t.table_name where t.table_schema='public')=3 then 'PASS' else 'BLOCKER' end,(select coalesce(string_agg(e.table_name,', ' order by e.table_name),'none') from expected_tables e where not exists (select 1 from information_schema.tables t where t.table_schema='public' and t.table_name=e.table_name))
  union all select 'COLUMNS','types_nullability_defaults',case when count(*)=0 then 'PASS' else 'BLOCKER' end,coalesce(string_agg(e.table_name||'.'||e.column_name,', ' order by e.table_name,e.column_name),'no mismatches') from expected_columns e left join information_schema.columns c on c.table_schema='public' and c.table_name=e.table_name and c.column_name=e.column_name where c.column_name is null or c.udt_name<>e.udt_name or c.is_nullable<>e.is_nullable or (e.default_fragment is not null and position(lower(e.default_fragment) in lower(coalesce(c.column_default,'')))=0)
  union all select 'FKS','exact_composite_columns',case when count(*)=0 then 'PASS' else 'BLOCKER' end,coalesce(string_agg(e.conname,', ' order by e.conname),'all expected composite FKs match attnums') from expected_fks e left join pg_constraint c on c.conname=e.conname and c.contype='f' and c.convalidated and c.conrelid=to_regclass('public.'||e.relname) and c.confrelid=to_regclass('public.'||e.referenced) and c.conkey=ARRAY(select a.attnum from pg_attribute a where a.attrelid=c.conrelid and a.attname=any(e.local_cols) and not a.attisdropped order by array_position(e.local_cols,a.attname))::smallint[] and c.confkey=ARRAY(select a.attnum from pg_attribute a where a.attrelid=c.confrelid and a.attname=any(e.referenced_cols) and not a.attisdropped order by array_position(e.referenced_cols,a.attname))::smallint[] where c.oid is null
  union all select 'CHECKS','named_checks',case when count(*)=0 then 'PASS' else 'BLOCKER' end,coalesce(string_agg(e.conname,', ' order by e.conname),'all expected checks match normalized semantic tokens') from expected_checks e left join pg_constraint c on c.conname=e.conname and c.contype='c' and c.convalidated and (select bool_and(position(regexp_replace(lower(token),'[^a-z0-9_]','','g') in regexp_replace(lower(pg_get_constraintdef(c.oid)),'[^a-z0-9_]','','g'))>0) from unnest(e.required_tokens) tokens(token)) where c.oid is null
  union all select 'INDEXES','code_index',case when exists (select 1 from pg_constraint where conname='supplier_invoices_company_code_unique' and contype='u' and convalidated) then 'PASS' else 'BLOCKER' end,'company + code unique constraint'
  union all select 'INDEXES','allocation_null_safe_definitions',case when count(*)=0 then 'PASS' else 'BLOCKER' end,coalesce(string_agg(e.index_name,', ' order by e.index_name),'all unique keys and predicates match') from expected_unique_indexes e left join pg_index i on i.indexrelid=to_regclass('public.'||e.index_name) and i.indisunique and regexp_replace(regexp_replace(regexp_replace(lower(coalesce(pg_get_expr(i.indpred,i.indrelid),'')),'\s+','','g'),'::[a-z0-9_\.\[\]]+','','g'),'[()]','','g')=regexp_replace(regexp_replace(regexp_replace(lower(e.predicate),'\s+','','g'),'::[a-z0-9_\.\[\]]+','','g'),'[()]','','g') and (select array_agg(pg_get_indexdef(i.indexrelid,n,true) order by n) from generate_series(1,i.indnkeyatts) n)=e.key_cols where i.indexrelid is null
  union all select 'INDEXES','operational_indexes',case when (select count(*) from pg_indexes where schemaname='public' and indexname in ('supplier_invoices_supplier_date_idx','supplier_invoices_supplier_number_idx','supplier_invoices_status_idx','supplier_invoice_lines_invoice_idx','supplier_invoice_allocations_invoice_idx','supplier_invoice_allocations_order_idx','supplier_invoice_allocations_receipt_idx'))=7 then 'PASS' else 'BLOCKER' end,'supplier/status/line/allocation lookup indexes'
  union all select 'RLS','all_tables_enabled',case when (select count(*) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname in ('supplier_invoices','supplier_invoice_lines','supplier_invoice_allocations') and c.relrowsecurity)=3 then 'PASS' else 'BLOCKER' end,'relrowsecurity=true on all three tables'
  union all select 'POLICIES','exact_using_with_check_permissions',case when (select count(*) from expected_policies e join pg_policies p on p.schemaname='public' and p.tablename=e.tablename and p.policyname=e.policyname and p.cmd=e.cmd and p.roles=array['authenticated']::name[] and (e.using_fragment is null or position(e.using_fragment in coalesce(p.qual,''))>0) and (e.check_fragment is null or position(e.check_fragment in coalesce(p.with_check,''))>0) and position(e.permission_fragment in coalesce(p.qual,'')||coalesce(p.with_check,''))>0 and (not e.require_platform or position('is_platform_superadmin' in coalesce(p.qual,'')||coalesce(p.with_check,''))>0) and ((e.cmd in ('SELECT','DELETE') and p.with_check is null) or (e.cmd in ('INSERT','UPDATE') and p.with_check is not null)))=(select count(*) from expected_policies) then 'PASS' else 'BLOCKER' end,'SELECT/DELETE use USING only; INSERT/UPDATE use WITH CHECK and exact permission'
  union all select 'LIFECYCLE','direct_update_stays_draft',case when exists (select 1 from pg_policies where schemaname='public' and policyname='supplier_invoices_update_permissions' and position('status = ''draft''' in qual)>0 and position('status = ''draft''' in with_check)>0) then 'PASS' else 'BLOCKER' end,'direct header UPDATE requires old and new draft'
  union all select 'LIFECYCLE','guard_requires_rpc_context',case when position('dmp.supplier_invoice_lifecycle' in pg_get_functiondef(to_regprocedure('public.dmp_supplier_invoice_guard()')))>0 and position('dmp.supplier_invoice_lifecycle' in pg_get_functiondef(to_regprocedure('public.dmp_supplier_invoice_allocation_guard()')))=0 then 'PASS' else 'BLOCKER' end,'registered/cancelled transitions are guarded by RPC context'
  union all select 'LIFECYCLE','allocation_parent_lock',case when position('for update' in lower(pg_get_functiondef(to_regprocedure('public.dmp_supplier_invoice_allocation_guard()'))))>0 and position('v_invoice.status <> ''draft''' in lower(pg_get_functiondef(to_regprocedure('public.dmp_supplier_invoice_allocation_guard()'))))>0 then 'PASS' else 'BLOCKER' end,'allocation INSERT/UPDATE/DELETE locks parent invoice before status validation'
  union all select 'LIFECYCLE','bidirectional_allocation_invariant',case when position('supplier_invoice_allocations' in lower(pg_get_functiondef(to_regprocedure('public.dmp_supplier_invoice_line_guard()'))))>0 and position('v_existing_allocated' in lower(pg_get_functiondef(to_regprocedure('public.dmp_supplier_invoice_line_guard()'))))>0 and position('new.total_amount' in lower(pg_get_functiondef(to_regprocedure('public.dmp_supplier_invoice_line_guard()'))))>0 then 'PASS' else 'BLOCKER' end,'line UPDATE rejects totals below existing allocations'
  union all select 'LIFECYCLE','allocation_lock_order',case when position('supplier_invoice_lineswhere' in regexp_replace(lower(pg_get_functiondef(to_regprocedure('public.dmp_supplier_invoice_allocation_guard()'))),'\s+','','g'))>0 and (length(lower(pg_get_functiondef(to_regprocedure('public.dmp_supplier_invoice_allocation_guard()'))))-length(replace(lower(pg_get_functiondef(to_regprocedure('public.dmp_supplier_invoice_allocation_guard()'))),'for update','')))=length('for update') then 'PASS' else 'BLOCKER' end,'allocation locks invoice header and reads line without a line-row lock'
  union all select 'LIFECYCLE','common_invoice_serialization',case when position('for update' in lower(pg_get_functiondef(to_regprocedure('public.dmp_register_supplier_invoice(uuid)'))))>0 and position('for update' in lower(pg_get_functiondef(to_regprocedure('public.dmp_supplier_invoice_line_guard()'))))>0 and position('for update' in lower(pg_get_functiondef(to_regprocedure('public.dmp_supplier_invoice_allocation_guard()'))))>0 then 'PASS' else 'BLOCKER' end,'register, line and allocation mutations serialize on invoice header'
  union all select 'PERMISSIONS','permission_keys',case when (select count(*) from public.permissions where code in ('supplier_invoices.read','supplier_invoices.create','supplier_invoices.update','supplier_invoices.register','supplier_invoices.cancel'))=5 then 'PASS' else 'BLOCKER' end,'all five permission rows exist'
  union all select 'ROLE_GRANTS','selected_roles',case when (select count(*) from public.role_permissions rp join public.roles r on r.id=rp.role_id join public.permissions p on p.id=rp.permission_id where r.name in ('superadmin','Gerencia','Oficina') and p.code like 'supplier_invoices.%')=15 then 'PASS' else 'BLOCKER' end,'superadmin, Gerencia and Oficina each receive five permissions'
  union all select 'MODULE','app_module',case when exists (select 1 from public.app_modules where code='supplier_invoices' and label='Facturas de proveedor' and active) then 'PASS' else 'BLOCKER' end,'supplier_invoices module is active'
  union all select 'FUNCTIONS','required_signatures_security',case when (select count(*) from expected_functions e join pg_proc p on p.oid=to_regprocedure(e.signature) where (not e.require_security_definer or p.prosecdef) and coalesce(array_to_string(p.proconfig,','),'') like '%search_path=public%')=7 then 'PASS' else 'BLOCKER' end,'OID signatures, SECURITY DEFINER and fixed public search_path'
  union all select 'TRIGGERS','required_triggers',case when (select count(*) from expected_triggers e join pg_trigger t on t.tgname=e.trigger_name and not t.tgisinternal and (t.tgtype & e.event_mask)=e.event_mask join pg_class r on r.oid=t.tgrelid and r.relname=e.table_name join pg_proc f on f.oid=t.tgfoid and f.proname=e.function_name)=4 then 'PASS' else 'BLOCKER' end,'all four triggers attach to the expected table/function and event mask'
  union all select 'ACL','public_supplier_invoice_rpcs',case when (select count(*) from (select e.signature,coalesce(bool_or(x.grantee='authenticated'::regrole and x.privilege_type='EXECUTE'),false) as auth_exec,coalesce(bool_or(x.grantee='anon'::regrole and x.privilege_type='EXECUTE'),false) as anon_exec,coalesce(bool_or(x.grantee=0 and x.privilege_type='EXECUTE'),false) as public_exec from (values ('public.dmp_register_supplier_invoice(uuid)'),('public.dmp_cancel_supplier_invoice(uuid,text)'),('public.next_dmp_code(uuid,text,text,boolean,integer)')) e(signature) join pg_proc p on p.oid=to_regprocedure(e.signature) left join lateral aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) x on true group by e.signature) a where auth_exec and not anon_exec and not public_exec)=3 then 'PASS' else 'BLOCKER' end,'authenticated EXECUTE only for the contracted public RPCs; anon/PUBLIC denied'
  union all select 'ACL','internal_functions_not_executable',case when (select count(*) from (select e.signature,coalesce(bool_or(x.grantee='authenticated'::regrole and x.privilege_type='EXECUTE'),false) as auth_exec,coalesce(bool_or(x.grantee='anon'::regrole and x.privilege_type='EXECUTE'),false) as anon_exec,coalesce(bool_or(x.grantee=0 and x.privilege_type='EXECUTE'),false) as public_exec from (values ('public.dmp_supplier_invoice_recalculate(uuid)'),('public.dmp_supplier_invoice_guard()'),('public.dmp_supplier_invoice_line_guard()'),('public.dmp_supplier_invoice_line_totals()'),('public.dmp_supplier_invoice_allocation_guard()')) e(signature) join pg_proc p on p.oid=to_regprocedure(e.signature) left join lateral aclexplode(coalesce(p.proacl,acldefault('f',p.proowner))) x on true group by e.signature) a where not auth_exec and not anon_exec and not public_exec)=5 then 'PASS' else 'BLOCKER' end,'internal SECURITY DEFINER functions are not executable by authenticated, anon or PUBLIC'
  union all select 'DOCUMENTS','document_type_set_exact',case when not exists (select 1 from expected_document_types e where not exists (select 1 from document_type_actual a where a.value=e.value)) and not exists (select 1 from document_type_actual a where not exists (select 1 from expected_document_types e where e.value=a.value)) then 'PASS' else 'BLOCKER' end,'PRE-130 document types plus Factura proveedor; removed=NONE'
  union all select 'DOCUMENTS','link_type_set_exact',case when not exists (select 1 from expected_document_link_types e where not exists (select 1 from document_link_type_actual a where a.value=e.value)) and not exists (select 1 from document_link_type_actual a where not exists (select 1 from expected_document_link_types e where e.value=a.value)) then 'PASS' else 'BLOCKER' end,'PRE-130 link types plus Factura proveedor; removed=NONE'
  union all select 'AUDIT','canonical_constraint_untouched',case when not exists (select 1 from expected_audit_operations e where not exists (select 1 from audit_operation_actual a where a.value=e.value)) and not exists (select 1 from audit_operation_actual a where not exists (select 1 from expected_audit_operations e where e.value=a.value)) then 'PASS' else 'BLOCKER' end,'130 leaves the complete canonical audit operation set untouched'
  union all select 'CODE_GENERATION','allowlist',case when to_regprocedure('public.next_dmp_code(uuid,text,text,boolean,integer)') is not null and position('supplier_invoices' in pg_get_functiondef(to_regprocedure('public.next_dmp_code(uuid,text,text,boolean,integer)')))>0 then 'PASS' else 'BLOCKER' end,'OID signature exists and allowlist includes supplier_invoices'
), summary(check_group, check_name, status, details) as (
  select 'SUMMARY', 'verify_130_supplier_invoice_core',
    case when count(*) filter (where status = 'BLOCKER') = 0 then 'PASS' else 'BLOCKER' end,
    case when count(*) filter (where status = 'BLOCKER') = 0 then 'all checks passed' else count(*) filter (where status = 'BLOCKER')::text || ' checks failed' end
  from checks
)
select check_group, check_name, status, details
from (
  select check_group, check_name, status, details from checks
  union all
  select check_group, check_name, status, details from summary
) result
order by case when check_group = 'SUMMARY' then 1 else 0 end, check_group, check_name;
