-- Strict structural verification for supplier details. No data changes.
do $$
declare
  v_item text[];
  v_index oid;
  v_table text;
  v_privilege text;
  v_expression text;
begin
  foreach v_item slice 1 in array array[
    ['trade_name','text','false'], ['internal_code','text','false'], ['contact_name','text','false'], ['website','text','false'],
    ['fiscal_address','text','false'], ['postal_code','text','false'], ['city','text','false'], ['province','text','false'], ['country','text','false'],
    ['payment_method','text','false'], ['payment_terms_days','integer','false'], ['payment_due_day','integer','false'], ['currency_code','text','false'],
    ['usual_discount','numeric(5,2)','false'], ['supplier_customer_reference','text','false'], ['billing_email','text','false'], ['billing_notes','text','false'], ['internal_notes','text','false']
  ]::text[][] loop
    if not exists (
      select 1 from pg_attribute a join pg_class c on c.oid = a.attrelid join pg_namespace n on n.oid = c.relnamespace
      where n.nspname = 'public' and c.relname = 'suppliers' and a.attname = v_item[1] and not a.attisdropped
        and format_type(a.atttypid, a.atttypmod) = v_item[2] and not a.attnotnull
    ) then raise exception '121 contract failed: suppliers.% has wrong type/nullability', v_item[1]; end if;
  end loop;

  select regexp_replace(regexp_replace(lower(regexp_replace(pg_get_constraintdef(con.oid, true), '\s+', ' ', 'g')), '::(text|numeric)(\[\])?', '', 'g'), '\(([0-9]+)\)', '\1', 'g') into v_expression
  from pg_constraint con join pg_class c on c.oid = con.conrelid join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relname = 'suppliers' and con.conname = 'suppliers_payment_method_check' and con.contype = 'c';
  if v_expression is null or position('payment_method is null' in v_expression) = 0 or not (v_expression ~ $re$payment_method\s+in\s*\(\s*'transferencia'(::text)?\s*,\s*'domiciliacion'(::text)?\s*,\s*'confirming'(::text)?\s*,\s*'tarjeta'(::text)?\s*,\s*'efectivo'(::text)?\s*,\s*'otra'(::text)?\s*\)$re$ or v_expression ~ $re$payment_method\s*=\s*any\s*\(\s*array\s*\[\s*'transferencia'(::text)?\s*,\s*'domiciliacion'(::text)?\s*,\s*'confirming'(::text)?\s*,\s*'tarjeta'(::text)?\s*,\s*'efectivo'(::text)?\s*,\s*'otra'(::text)?\s*\]\s*\)$re$) then raise exception '121 contract failed: payment method constraint is invalid'; end if;

  select regexp_replace(regexp_replace(lower(regexp_replace(pg_get_constraintdef(con.oid, true), '\s+', ' ', 'g')), '::(text|numeric)(\[\])?', '', 'g'), '\(([0-9]+)\)', '\1', 'g') into v_expression
  from pg_constraint con join pg_class c on c.oid = con.conrelid join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relname = 'suppliers' and con.conname = 'suppliers_payment_terms_days_check' and con.contype = 'c';
  if v_expression is null or position('payment_terms_days is null' in v_expression) = 0 or position('payment_terms_days >= 0' in v_expression) = 0 then raise exception '121 contract failed: payment days constraint is invalid'; end if;

  select regexp_replace(regexp_replace(lower(regexp_replace(pg_get_constraintdef(con.oid, true), '\s+', ' ', 'g')), '::(text|numeric)(\[\])?', '', 'g'), '\(([0-9]+)\)', '\1', 'g') into v_expression
  from pg_constraint con join pg_class c on c.oid = con.conrelid join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relname = 'suppliers' and con.conname = 'suppliers_payment_due_day_check' and con.contype = 'c';
  if v_expression is null or position('payment_due_day is null' in v_expression) = 0 or not (v_expression ~ 'payment_due_day\s+between\s+1\s+and\s+31' or (position('payment_due_day >= 1' in v_expression) > 0 and position('payment_due_day <= 31' in v_expression) > 0)) then raise exception '121 contract failed: payment due day constraint is invalid'; end if;

  select regexp_replace(regexp_replace(lower(regexp_replace(pg_get_constraintdef(con.oid, true), '\s+', ' ', 'g')), '::(text|numeric)(\[\])?', '', 'g'), '\(([0-9]+)\)', '\1', 'g') into v_expression
  from pg_constraint con join pg_class c on c.oid = con.conrelid join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relname = 'suppliers' and con.conname = 'suppliers_currency_code_check' and con.contype = 'c';
  if v_expression is null or position('currency_code is null' in v_expression) = 0 or v_expression !~ 'currency_code\s*~' or v_expression !~ '\[a-z\]\{3\}' then raise exception '121 contract failed: currency constraint is invalid'; end if;

  select regexp_replace(regexp_replace(lower(regexp_replace(pg_get_constraintdef(con.oid, true), '\s+', ' ', 'g')), '::(text|numeric)(\[\])?', '', 'g'), '\(([0-9]+)\)', '\1', 'g') into v_expression
  from pg_constraint con join pg_class c on c.oid = con.conrelid join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relname = 'suppliers' and con.conname = 'suppliers_usual_discount_check' and con.contype = 'c';
  if v_expression is null or position('usual_discount is null' in v_expression) = 0 or not (v_expression ~ 'usual_discount\s+between\s+0\s+and\s+100' or (position('usual_discount >= 0' in v_expression) > 0 and position('usual_discount <= 100' in v_expression) > 0)) then raise exception '121 contract failed: discount constraint is invalid'; end if;

  select i.indexrelid into v_index from pg_index i join pg_class idx on idx.oid = i.indexrelid join pg_namespace idx_ns on idx_ns.oid = idx.relnamespace where i.indrelid = 'public.suppliers'::regclass and idx_ns.nspname = 'public' and idx.relname = 'suppliers_company_internal_code_unique' and i.indisunique and i.indnkeyatts = 2 and i.indkey[0] = (select attnum from pg_attribute where attrelid = 'public.suppliers'::regclass and attname = 'company_id') and i.indkey[1] = (select attnum from pg_attribute where attrelid = 'public.suppliers'::regclass and attname = 'internal_code') and i.indpred is not null;
  if v_index is null or lower(regexp_replace(pg_get_expr((select indpred from pg_index where indexrelid=v_index), 'public.suppliers'::regclass), '\s+', ' ', 'g')) not like '%internal_code is not null%' or lower(regexp_replace(pg_get_expr((select indpred from pg_index where indexrelid=v_index), 'public.suppliers'::regclass), '\s+', ' ', 'g')) not like '%deleted_at is null%' then raise exception '121 contract failed: internal code unique index is invalid'; end if;

  if to_regclass('public.supplier_bank_accounts') is null then raise exception '121 contract failed: supplier_bank_accounts is missing'; end if;
  if not exists (select 1 from pg_class where oid='public.supplier_bank_accounts'::regclass and relrowsecurity) then raise exception '121 contract failed: supplier_bank_accounts RLS is missing'; end if;
  foreach v_item slice 1 in array array[
    ['id','uuid','true'], ['company_id','uuid','true'], ['supplier_id','uuid','true'], ['account_holder','text','false'], ['iban','text','false'], ['bic_swift','text','false'], ['is_primary','boolean','true'], ['active','boolean','true'], ['notes','text','false'], ['created_by','uuid','false'], ['created_at','timestamp with time zone','true'], ['updated_at','timestamp with time zone','true']
  ]::text[][] loop
    if not exists (select 1 from pg_attribute a join pg_class c on c.oid=a.attrelid join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname='supplier_bank_accounts' and a.attname=v_item[1] and not a.attisdropped and format_type(a.atttypid,a.atttypmod)=v_item[2] and a.attnotnull=(v_item[3]='true')) then raise exception '121 contract failed: bank column % has wrong type/nullability', v_item[1]; end if;
  end loop;
  if not exists (select 1 from pg_attrdef d join pg_attribute a on a.attrelid=d.adrelid and a.attnum=d.adnum where d.adrelid='public.supplier_bank_accounts'::regclass and a.attname='is_primary' and pg_get_expr(d.adbin,d.adrelid)='false') then raise exception '121 contract failed: is_primary default is invalid'; end if;
  if not exists (select 1 from pg_attrdef d join pg_attribute a on a.attrelid=d.adrelid and a.attnum=d.adnum where d.adrelid='public.supplier_bank_accounts'::regclass and a.attname='active' and pg_get_expr(d.adbin,d.adrelid)='true') then raise exception '121 contract failed: active default is invalid'; end if;
  if not exists (select 1 from pg_constraint where conrelid='public.supplier_bank_accounts'::regclass and contype='p' and conkey=array[(select attnum from pg_attribute where attrelid='public.supplier_bank_accounts'::regclass and attname='id')]::smallint[]) then raise exception '121 contract failed: bank primary key is invalid'; end if;
  if not exists (select 1 from pg_constraint where conrelid='public.supplier_bank_accounts'::regclass and contype='f' and conkey=array[(select attnum from pg_attribute where attrelid='public.supplier_bank_accounts'::regclass and attname='company_id'),(select attnum from pg_attribute where attrelid='public.supplier_bank_accounts'::regclass and attname='supplier_id')]::smallint[] and confrelid='public.suppliers'::regclass and confkey=array[(select attnum from pg_attribute where attrelid='public.suppliers'::regclass and attname='company_id'),(select attnum from pg_attribute where attrelid='public.suppliers'::regclass and attname='id')]::smallint[]) then raise exception '121 contract failed: supplier bank tenant FK is incorrect'; end if;
  if not exists (select 1 from pg_constraint where conrelid='public.supplier_bank_accounts'::regclass and contype='f' and conkey=array[(select attnum from pg_attribute where attrelid='public.supplier_bank_accounts'::regclass and attname='created_by')]::smallint[] and confrelid='public.profiles'::regclass and confkey=array[(select attnum from pg_attribute where attrelid='public.profiles'::regclass and attname='id')]::smallint[]) then raise exception '121 contract failed: bank created_by FK is incorrect'; end if;

  if not exists (select 1 from pg_index i join pg_class idx on idx.oid = i.indexrelid join pg_namespace idx_ns on idx_ns.oid = idx.relnamespace where i.indrelid='public.supplier_bank_accounts'::regclass and idx_ns.nspname='public' and idx.relname='supplier_bank_accounts_primary_unique' and i.indisunique and i.indnkeyatts=2 and i.indkey[0]=(select attnum from pg_attribute where attrelid='public.supplier_bank_accounts'::regclass and attname='company_id') and i.indkey[1]=(select attnum from pg_attribute where attrelid='public.supplier_bank_accounts'::regclass and attname='supplier_id') and lower(pg_get_expr(i.indpred,i.indrelid)) like '%is_primary = true%' and lower(pg_get_expr(i.indpred,i.indrelid)) like '%active = true%') then raise exception '121 contract failed: primary bank index is invalid'; end if;
  if not exists (select 1 from pg_index i join pg_class idx on idx.oid = i.indexrelid join pg_namespace idx_ns on idx_ns.oid = idx.relnamespace where i.indrelid='public.supplier_bank_accounts'::regclass and idx_ns.nspname='public' and idx.relname='supplier_bank_accounts_iban_unique' and i.indisunique and i.indnkeyatts=3 and i.indkey[0]=(select attnum from pg_attribute where attrelid='public.supplier_bank_accounts'::regclass and attname='company_id') and i.indkey[1]=(select attnum from pg_attribute where attrelid='public.supplier_bank_accounts'::regclass and attname='supplier_id') and i.indkey[2]=0 and i.indexprs is not null and lower(pg_get_indexdef(i.indexrelid)) like '%upper(regexp_replace(iban%' and lower(pg_get_expr(i.indpred,i.indrelid)) like '%iban is not null%') then raise exception '121 contract failed: normalized IBAN index is invalid'; end if;
  if not exists (select 1 from pg_index i join pg_class idx on idx.oid = i.indexrelid join pg_namespace idx_ns on idx_ns.oid = idx.relnamespace where i.indrelid='public.supplier_bank_accounts'::regclass and idx_ns.nspname='public' and idx.relname='supplier_bank_accounts_supplier_idx' and i.indnkeyatts=3 and i.indkey[0]=(select attnum from pg_attribute where attrelid='public.supplier_bank_accounts'::regclass and attname='company_id') and i.indkey[1]=(select attnum from pg_attribute where attrelid='public.supplier_bank_accounts'::regclass and attname='supplier_id') and i.indkey[2]=(select attnum from pg_attribute where attrelid='public.supplier_bank_accounts'::regclass and attname='active')) then raise exception '121 contract failed: supplier bank lookup index is invalid'; end if;
  if not exists (select 1 from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_proc p on p.oid=t.tgfoid join pg_namespace n on n.oid=p.pronamespace where c.oid='public.supplier_bank_accounts'::regclass and t.tgname='supplier_bank_account_guard_trigger' and not t.tgisinternal and (t.tgtype & 1)=1 and (t.tgtype & 2)=2 and (t.tgtype & 4)=4 and (t.tgtype & 16)=16 and n.nspname='public' and p.proname='dmp_supplier_bank_account_guard') then raise exception '121 contract failed: bank identity/update trigger is invalid'; end if;
  if not exists (select 1 from pg_trigger t join pg_class c on c.oid=t.tgrelid join pg_proc p on p.oid=t.tgfoid join pg_namespace n on n.oid=p.pronamespace where c.oid='public.supplier_bank_accounts'::regclass and t.tgname='supplier_bank_account_updated_at_trigger' and not t.tgisinternal and (t.tgtype & 1)=1 and (t.tgtype & 2)=2 and (t.tgtype & 16)=16 and n.nspname='public' and p.proname='set_updated_at') then raise exception '121 contract failed: canonical updated_at trigger is invalid'; end if;
  select pg_get_functiondef(p.oid) into v_expression from pg_trigger t join pg_proc p on p.oid=t.tgfoid where t.tgname='supplier_bank_account_guard_trigger' and t.tgrelid='public.supplier_bank_accounts'::regclass and p.pronamespace='public'::regnamespace;
  if position('current_profile_id()' in lower(v_expression)) = 0 or position('new.created_by := public.current_profile_id()' in lower(v_expression)) = 0 or position('new.created_by is null' in lower(v_expression)) = 0 or position('new.created_by is distinct from old.created_by' in lower(v_expression)) = 0 or position('new.id is distinct from old.id' in lower(v_expression)) = 0 or position('new.company_id is distinct from old.company_id' in lower(v_expression)) = 0 or position('new.supplier_id is distinct from old.supplier_id' in lower(v_expression)) = 0 or position('new.created_at is distinct from old.created_at' in lower(v_expression)) = 0 then raise exception '121 contract failed: bank actor/identity guard is incomplete'; end if;
  if position('new.is_primary and new.active' in lower(v_expression)) = 0 or position('company_id = new.company_id' in lower(v_expression)) = 0 or position('supplier_id = new.supplier_id' in lower(v_expression)) = 0 or position('id is distinct from new.id' in lower(v_expression)) = 0 or position('set is_primary = false' in lower(v_expression)) = 0 then raise exception '121 contract failed: primary switching guard is incomplete'; end if;

  foreach v_item slice 1 in array array[
    ['supplier_bank_accounts','supplier_bank_accounts_select_admin','SELECT','qual'], ['supplier_bank_accounts','supplier_bank_accounts_insert_admin','INSERT','with_check'], ['supplier_bank_accounts','supplier_bank_accounts_update_admin','UPDATE','qual'], ['supplier_bank_accounts','supplier_bank_accounts_platform_superadmin_select','SELECT','qual'], ['supplier_bank_accounts','supplier_bank_accounts_platform_superadmin_insert','INSERT','with_check'], ['supplier_bank_accounts','supplier_bank_accounts_platform_superadmin_update','UPDATE','qual']
  ]::text[][] loop
    if not exists (select 1 from pg_policies where schemaname='public' and tablename=v_item[1] and policyname=v_item[2] and cmd=v_item[3] and roles=array['authenticated']::name[]) then raise exception '121 contract failed: policy % is invalid', v_item[2]; end if;
  end loop;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='supplier_bank_accounts' and policyname='supplier_bank_accounts_select_admin' and cmd='SELECT' and roles=array['authenticated']::name[] and qual is not null and lower(replace(qual,'public.','')) like '%company_id%current_company_id()%' and lower(qual) like '%has_any_role%' and qual ~* $re$has_any_role\s*\(\s*array\s*\[\s*'superadmin'(::text)?\s*,\s*'gerencia'(::text)?\s*,\s*'oficina'(::text)?\s*\]$re$ and lower(qual) not like '%sat%' and lower(qual) not like '% or %') then raise exception '121 contract failed: bank SELECT tenant/roles are invalid'; end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='supplier_bank_accounts' and policyname='supplier_bank_accounts_insert_admin' and cmd='INSERT' and roles=array['authenticated']::name[] and with_check is not null and lower(replace(with_check,'public.','')) like '%company_id%current_company_id()%' and lower(with_check) like '%has_any_role%' and with_check ~* $re$has_any_role\s*\(\s*array\s*\[\s*'superadmin'(::text)?\s*,\s*'gerencia'(::text)?\s*,\s*'oficina'(::text)?\s*\]$re$ and lower(with_check) not like '%sat%' and lower(with_check) not like '% or %') then raise exception '121 contract failed: bank INSERT tenant/roles are invalid'; end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='supplier_bank_accounts' and policyname='supplier_bank_accounts_update_admin' and cmd='UPDATE' and roles=array['authenticated']::name[] and qual is not null and with_check is not null and lower(replace(qual,'public.','')) like '%company_id%current_company_id()%' and lower(replace(with_check,'public.','')) like '%company_id%current_company_id()%' and qual ~* $re$has_any_role\s*\(\s*array\s*\[\s*'superadmin'(::text)?\s*,\s*'gerencia'(::text)?\s*,\s*'oficina'(::text)?\s*\]$re$ and with_check ~* $re$has_any_role\s*\(\s*array\s*\[\s*'superadmin'(::text)?\s*,\s*'gerencia'(::text)?\s*,\s*'oficina'(::text)?\s*\]$re$ and lower(qual || with_check) not like '%sat%' and lower(qual || with_check) not like '% or %') then raise exception '121 contract failed: bank UPDATE tenant/roles are invalid'; end if;
  if exists (select 1 from pg_policies where schemaname='public' and tablename='supplier_bank_accounts' and lower(coalesce(qual,'') || ' ' || coalesce(with_check,'')) like '%sat%') then raise exception '121 contract failed: SAT can access supplier bank accounts'; end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='supplier_bank_accounts' and policyname='supplier_bank_accounts_platform_superadmin_select' and cmd='SELECT' and roles=array['authenticated']::name[] and replace(lower(regexp_replace(coalesce(qual,''),'\s+','','g')),'public.','') ~ '^\(*is_platform_superadmin\(\)\)*$') then raise exception '121 contract failed: platform SELECT policy is invalid'; end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='supplier_bank_accounts' and policyname='supplier_bank_accounts_platform_superadmin_insert' and cmd='INSERT' and roles=array['authenticated']::name[] and replace(lower(regexp_replace(coalesce(with_check,''),'\s+','','g')),'public.','') ~ '^\(*is_platform_superadmin\(\)\)*$') then raise exception '121 contract failed: platform INSERT policy is invalid'; end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='supplier_bank_accounts' and policyname='supplier_bank_accounts_platform_superadmin_update' and cmd='UPDATE' and roles=array['authenticated']::name[] and replace(lower(regexp_replace(coalesce(qual,''),'\s+','','g')),'public.','') ~ '^\(*is_platform_superadmin\(\)\)*$' and replace(lower(regexp_replace(coalesce(with_check,''),'\s+','','g')),'public.','') ~ '^\(*is_platform_superadmin\(\)\)*$') then raise exception '121 contract failed: platform UPDATE policy is invalid'; end if;
  if exists (select 1 from pg_policies where schemaname='public' and tablename='supplier_bank_accounts' and cmd='DELETE') then raise exception '121 contract failed: bank DELETE policy exists'; end if;

  foreach v_table in array array['supplier_bank_accounts'] loop
    foreach v_privilege in array array['SELECT','INSERT','UPDATE','DELETE','TRUNCATE','REFERENCES','TRIGGER'] loop
      if has_table_privilege('anon','public.' || v_table,v_privilege) then raise exception '121 contract failed: anon has % on %',v_privilege,v_table; end if;
    end loop;
    foreach v_privilege in array array['SELECT','INSERT','UPDATE'] loop
      if not has_table_privilege('authenticated','public.' || v_table,v_privilege) then raise exception '121 contract failed: authenticated lacks % on %',v_privilege,v_table; end if;
    end loop;
    foreach v_privilege in array array['DELETE','TRUNCATE','REFERENCES','TRIGGER'] loop
      if has_table_privilege('authenticated','public.' || v_table,v_privilege) then raise exception '121 contract failed: authenticated has forbidden % on %',v_privilege,v_table; end if;
    end loop;
  end loop;
  if exists (select 1 from information_schema.columns where table_schema='public' and table_name='suppliers' and column_name in ('supplier_balance','outstanding_balance','total_paid','paid_amount')) then raise exception '121 contract failed: editable supplier balance column exists'; end if;
end;
$$;
select 'verify_121_supplier_details: PASS' as result;
