-- DoorManager Pro - harden billing RPC identifiers without changing behavior.
begin;

create or replace function public.dmp_update_invoice_draft(p_invoice_id uuid,p_lines jsonb,p_due_date date default null,p_notes text default null,p_tax_rate numeric default null)
returns void language plpgsql security definer set search_path=public as $$
declare v_actor public.profiles:=public.dmp024_active_profile(); v_invoice public.invoices; v_line jsonb; v_qty numeric; v_price numeric; v_discount numeric; v_tax numeric; v_subtotal numeric; v_tax_amount numeric; v_total numeric; v_work_id uuid; v_source_work_id uuid; v_expected numeric; v_actual numeric; v_status text:='complete'; v_work_count integer; v_manual_line_count integer; v_strict_single boolean;
begin
  if not public.has_any_role(array['superadmin','Gerencia','Oficina']) then raise exception 'permiso: no tienes permiso para editar borradores'; end if;
  if jsonb_typeof(p_lines)<>'array' then raise exception 'factura: las lineas deben ser un array'; end if;
  select * into v_invoice from public.invoices where id=p_invoice_id for update; if v_invoice.id is null then raise exception 'factura: factura no encontrada'; end if; perform public.assert_member_of_current_company(v_invoice.company_id);
  if v_invoice.status<>'borrador' then raise exception 'factura: solo se pueden editar borradores'; end if;
  v_tax:=coalesce(p_tax_rate,v_invoice.tax_rate); if v_tax<0 then raise exception 'factura: IVA no valido'; end if;
  delete from public.invoice_work_orders where invoice_id=v_invoice.id and deleted_at is null;
  for v_line in select decision_line.value from jsonb_array_elements(p_lines) as decision_line(value) loop
    if trim(coalesce(v_line->>'description',''))='' then raise exception 'factura: cada linea necesita descripcion'; end if;
    v_qty:=coalesce(nullif(v_line->>'quantity','')::numeric,1); v_price:=coalesce(nullif(v_line->>'unit_price','')::numeric,0); v_discount:=coalesce(nullif(v_line->>'discount','')::numeric,0); v_work_id:=nullif(v_line->>'work_order_id','')::uuid;
    if v_qty<0 or v_price<0 or v_discount<0 or v_discount>100 or coalesce(nullif(v_line->>'tax_rate','')::numeric,v_tax)<0 then raise exception 'factura: importe, cantidad, descuento o IVA no valido'; end if;
    if v_work_id is not null and not public.dmp_guided_billing_eligible(v_work_id) then raise exception 'factura: parte asociado no valido para este borrador'; end if;
    if v_work_id is not null and not exists(select 1 from public.work_orders as work_order_record where work_order_record.id=v_work_id and work_order_record.company_id=v_invoice.company_id and work_order_record.deleted_at is null) then raise exception 'factura: parte asociado no pertenece a la empresa'; end if;
    v_subtotal:=round(v_qty*v_price*(1-v_discount/100),2); v_tax_amount:=round(v_subtotal*coalesce(nullif(v_line->>'tax_rate','')::numeric,v_tax)/100,2); v_total:=round(v_subtotal+v_tax_amount,2);
    insert into public.invoice_work_orders(company_id,invoice_id,work_order_id,description,quantity,unit_price,discount,subtotal,tax_rate,tax_amount,total_amount) values(v_invoice.company_id,v_invoice.id,v_work_id,trim(v_line->>'description'),v_qty,v_price,v_discount,v_subtotal,coalesce(nullif(v_line->>'tax_rate','')::numeric,v_tax),v_tax_amount,v_total);
  end loop;
  select round(coalesce(sum(billing_entry.subtotal),0),2) into v_actual from public.invoice_work_orders as billing_entry where billing_entry.invoice_id=v_invoice.id and billing_entry.deleted_at is null;
  select count(distinct billing_entry.work_order_id) into v_work_count from public.invoice_work_orders as billing_entry where billing_entry.invoice_id=v_invoice.id and billing_entry.deleted_at is null and billing_entry.work_order_id is not null;
  select count(*) into v_manual_line_count from public.invoice_work_orders as billing_entry where billing_entry.invoice_id=v_invoice.id and billing_entry.deleted_at is null and billing_entry.work_order_id is null;
  v_strict_single:=v_work_count=1 and v_manual_line_count=0; v_expected:=null;
  if v_strict_single then
    select round(coalesce(sum(work_order_record.sale_amount),0),2) into v_expected from public.work_orders as work_order_record join (select distinct billing_entry.work_order_id from public.invoice_work_orders as billing_entry where billing_entry.invoice_id=v_invoice.id and billing_entry.deleted_at is null and billing_entry.work_order_id is not null) as associated_work_orders on associated_work_orders.work_order_id=work_order_record.id;
    if round(v_actual,2)<>round(v_expected,2) then v_status:='inconsistent'; end if;
  end if;
  -- Non-strict invoices are compatible by composition, not against a synthetic work-order total.
  update public.invoices as invoice_record set due_date=p_due_date,notes=nullif(trim(p_notes),''),tax_rate=v_tax,subtotal=v_actual,tax_amount=round(v_actual*v_tax/100,2),total_amount=round(v_actual*(1+v_tax/100),2),economic_expected_amount=v_expected,economic_actual_amount=v_actual,economic_detail_status=v_status,economic_override_reason=null,economic_override_by=null,economic_override_at=null,updated_by=v_actor.id,updated_at=now() where invoice_record.id=v_invoice.id;
  insert into public.audit_log(company_id,table_name,record_id,operation,changed_by,old_data,new_data) values(v_invoice.company_id,'invoices',v_invoice.id,'INVOICE_DRAFT_UPDATE',v_actor.id,to_jsonb(v_invoice),jsonb_build_object('actual_amount',v_actual,'economic_detail_status',v_status));
end $$;

create or replace function public.dmp_issue_invoice(p_invoice_id uuid,p_override boolean default false,p_override_reason text default null)
returns uuid language plpgsql security definer set search_path=public as $$
declare v_actor public.profiles:=public.dmp024_active_profile(); v_invoice public.invoices; v_work public.work_orders; v_client public.clients; v_company public.companies; v_site public.sites; v_quote public.quotes; v_line record; v_base text; v_next_no integer; v_subtotal numeric; v_tax numeric; v_total numeric; v_invalid integer; v_snapshot jsonb; v_reason text:=trim(coalesce(p_override_reason,'')); v_work_count integer; v_manual_line_count integer; v_strict_single boolean; v_sale numeric; v_stale boolean:=false;
begin
  if not public.has_any_role(array['superadmin','Gerencia','Oficina']) then raise exception 'permiso: no tienes permiso para emitir facturas'; end if;
  select * into v_invoice from public.invoices where id=p_invoice_id for update; if v_invoice.id is null then raise exception 'factura: factura no encontrada'; end if; perform public.assert_member_of_current_company(v_invoice.company_id);
  if v_invoice.status<>'borrador' then raise exception 'factura: solo se pueden emitir borradores'; end if;
  select count(*) filter(where billing_entry.total_amount<=0 or billing_entry.subtotal<0 or billing_entry.tax_amount<0),round(coalesce(sum(billing_entry.subtotal),0),2),round(coalesce(sum(billing_entry.tax_amount),0),2),round(coalesce(sum(billing_entry.total_amount),0),2) into v_invalid,v_subtotal,v_tax,v_total from public.invoice_work_orders as billing_entry where billing_entry.invoice_id=v_invoice.id and billing_entry.deleted_at is null;
  if not exists(select 1 from public.invoice_work_orders as billing_entry where billing_entry.invoice_id=v_invoice.id and billing_entry.deleted_at is null) or v_invalid>0 or v_total<=0 then raise exception 'factura: el borrador necesita al menos una linea valida y un total mayor que cero'; end if;
  select count(distinct billing_entry.work_order_id) into v_work_count from public.invoice_work_orders as billing_entry where billing_entry.invoice_id=v_invoice.id and billing_entry.deleted_at is null and billing_entry.work_order_id is not null;
  select count(*) into v_manual_line_count from public.invoice_work_orders as billing_entry where billing_entry.invoice_id=v_invoice.id and billing_entry.deleted_at is null and billing_entry.work_order_id is null;
  v_strict_single:=v_work_count=1 and v_manual_line_count=0;
  for v_line in select billing_entry.work_order_id,round(sum(billing_entry.subtotal),2) subtotal from public.invoice_work_orders as billing_entry where billing_entry.invoice_id=v_invoice.id and billing_entry.deleted_at is null and billing_entry.work_order_id is not null group by billing_entry.work_order_id loop
    if not public.dmp_guided_billing_eligible(v_line.work_order_id) then raise exception 'factura: existe un parte asociado no valido'; end if;
    select round(coalesce(work_order_record.sale_amount,0),2) into v_sale from public.work_orders as work_order_record where work_order_record.id=v_line.work_order_id;
    if v_strict_single and round(v_line.subtotal,2)<>v_sale then v_stale:=true; end if;
  end loop;
  if v_strict_single and (v_invoice.economic_expected_amount is null or round(v_invoice.economic_expected_amount,2)<>v_subtotal) then v_stale:=true; end if;
  if v_stale and not p_override then raise exception 'factura: el borrador esta obsoleto respecto a la economia aprobada; requiere excepcion autorizada'; end if;
  if p_override and v_reason='' then raise exception 'factura: el motivo de excepcion es obligatorio'; end if;
  if p_override and not v_stale then raise exception 'factura: la excepcion solo aplica a una inconsistencia economica real'; end if;
  v_base:='FAC-'||to_char(current_date,'YYYY-'); perform pg_advisory_xact_lock(hashtextextended(v_invoice.company_id::text||':invoice:'||v_base,0));
  select coalesce(max(substring(invoice_record.code from length(v_base)+1)::integer),0)+1 into v_next_no from public.invoices as invoice_record where invoice_record.company_id=v_invoice.company_id and invoice_record.code like v_base||'%' and substring(invoice_record.code from length(v_base)+1)~'^[0-9]+$';
  select work_order_record.* into v_work from public.invoice_work_orders as billing_entry join public.work_orders as work_order_record on work_order_record.id=billing_entry.work_order_id where billing_entry.invoice_id=v_invoice.id and billing_entry.deleted_at is null and billing_entry.work_order_id is not null order by billing_entry.id limit 1;
  select company_record.* into v_company from public.companies as company_record where company_record.id=v_invoice.company_id; select client_record.* into v_client from public.clients as client_record where client_record.id=v_invoice.client_id; select site_record.* into v_site from public.sites as site_record where site_record.id=v_work.site_id; select quote_record.* into v_quote from public.quotes as quote_record where quote_record.id=v_work.quote_id;
  v_snapshot:=jsonb_build_object('emitter',jsonb_build_object('name',v_company.name,'trade_name',v_company.trade_name,'tax_id',v_company.tax_id,'address',v_company.address,'postal_code',v_company.postal_code,'city',v_company.city,'province',v_company.province,'country',v_company.country,'phone',v_company.phone,'email',v_company.email,'website',v_company.website),'client',jsonb_build_object('legal_name',v_client.legal_name,'trade_name',v_client.trade_name,'tax_id',v_client.tax_id,'address',v_client.address,'postal_code',v_client.postal_code,'city',v_client.city,'province',v_client.province,'country',v_client.country,'phone',v_client.phone,'email',v_client.email),'work',case when v_work.id is null then '{}'::jsonb else jsonb_build_object('code',v_work.code,'title',v_work.title,'site_name',v_site.name,'site_code',v_site.code,'quote_code',v_quote.code) end,'works',coalesce((select jsonb_agg(jsonb_build_object('work_order_id',works_source.work_order_id,'code',works_record.code,'title',works_record.title) order by works_source.work_order_id) from (select distinct billing_entry.work_order_id from public.invoice_work_orders as billing_entry where billing_entry.invoice_id=v_invoice.id and billing_entry.deleted_at is null and billing_entry.work_order_id is not null) as works_source join public.work_orders as works_record on works_record.id=works_source.work_order_id),'[]'::jsonb),'lines',coalesce((select jsonb_agg(jsonb_build_object('work_order_id',billing_entry.work_order_id,'description',billing_entry.description,'quantity',billing_entry.quantity,'unit_price',billing_entry.unit_price,'discount',billing_entry.discount,'subtotal',billing_entry.subtotal,'tax_rate',billing_entry.tax_rate,'tax_amount',billing_entry.tax_amount,'total_amount',billing_entry.total_amount) order by billing_entry.id) from public.invoice_work_orders as billing_entry where billing_entry.invoice_id=v_invoice.id and billing_entry.deleted_at is null),'[]'::jsonb),'totals',jsonb_build_object('subtotal',v_subtotal,'tax_amount',v_tax,'total_amount',v_total,'issue_date',current_date));
  update public.invoices as invoice_record set code=v_base||lpad(v_next_no::text,6,'0'),status='emitida',issue_date=current_date,subtotal=v_subtotal,tax_amount=v_tax,total_amount=v_total,fiscal_snapshot=v_snapshot,economic_expected_amount=case when v_strict_single then v_sale else null end,economic_actual_amount=v_subtotal,economic_detail_status=case when p_override then 'overridden' else 'complete' end,economic_override_reason=case when p_override then v_reason end,economic_override_by=case when p_override then v_actor.id end,economic_override_at=case when p_override then now() end,updated_by=v_actor.id,updated_at=now() where invoice_record.id=v_invoice.id;
  update public.work_orders as work_order_record set invoiced_amount=totals.subtotal,paid_amount=0,economic_status='facturado',updated_by=v_actor.id,updated_at=now() from (select billing_entry.work_order_id,round(sum(billing_entry.subtotal),2) subtotal from public.invoice_work_orders as billing_entry where billing_entry.invoice_id=v_invoice.id and billing_entry.deleted_at is null and billing_entry.work_order_id is not null group by billing_entry.work_order_id) as totals where totals.work_order_id=work_order_record.id;
  insert into public.audit_log(company_id,table_name,record_id,operation,changed_by,old_data,new_data) values(v_invoice.company_id,'invoices',v_invoice.id,case when p_override then 'INVOICE_ISSUE_OVERRIDE' else 'INVOICE_ISSUE' end,v_actor.id,to_jsonb(v_invoice),jsonb_build_object('subtotal',v_subtotal,'tax_amount',v_tax,'total_amount',v_total,'fiscal_snapshot',true,'invoice_mode',case when v_strict_single then 'strict_single' when v_work_count=0 then 'manual' when v_manual_line_count>0 then 'hybrid' else 'multi' end,'expected_amount',case when v_strict_single then v_sale else null end,'actual_amount',v_subtotal));
  return v_invoice.id;
end $$;

grant execute on function public.dmp_update_invoice_draft(uuid,jsonb,date,text,numeric) to authenticated;
grant execute on function public.dmp_issue_invoice(uuid,boolean,text) to authenticated;

commit;
